<?php
/***************************************************************************
 *               lang_faq.php [Bosnia-Croatia-Serbia-Montenegro]
 *                            -------------------
 *   begin                : Wednesday Oct 3, 2001
 *   copyright            : (C) 2001 The phpBB Group
 *   email                : support@phpbb.com
 *   $Id$
 *
 *
 ***************************************************************************/

/***************************************************************************
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 ***************************************************************************/
 
/***************************************************************************
 *     Prevod s italijanske verzije phpBB Foruma: Golac Željko, Alen Ruvic *
 *     pocetak prevoda      : Petak, 20. septembar 2002                    *
 *     web                  : http://www.maglaj.info                       *
 *     e-mail               : mrmot@vizzavi.it, ruval@gmx.ch               *
 ***************************************************************************/
 
 
 
// 
// Da biste unijeli jednu novu stavku koja bi trebala biti sastavni dio FAQ ucinite to u ovom formatu:
// $faq[] = array("pitanje", "odgovor");
// Za odvajanje posebnih sekcija ubacite
// $faq[] = array("--","Ovdje ide naslov sekcije");
// Linkovi ce biti automatski kreirani
//
// NE ZABORAVITE ; na kraju linije.
// Ne ubacujete navodnike  (") u Vas FAQ, a ukoliko bas morate ucinite to na ovaj nacin:\"tekst u navodnicima\";
//
// Pitanja i odgovori u Vasem vodicu ce se pojaviti u istom reosljedu kao u ovom file-u
//
 
  
$faq[] = array("--","Registracija i ulazak na Forum");
$faq[] = array("Zašto ne mogu pristupiti Forumu?", "U zavisnosti od toga kako je administrator uredio pravila korištenja Foruma može se desiti da je za uèešæe u diskusijama potrebno biti èlan Foruma (registrovati se). Ukoliko je Vaša registracija protekla uredno, za aktivno uèestvovanje u diskusijama potrebno je <b>logirati se</b> (<i>prijava posredstvom vlastite lozinke i nadimka koje ste prethodno odabrali</i>). U sluèaju da Vam je zabranjen pristup Forumu administrator je taj koji æe Vam objasniti razloge zabrane. Takodje, vrlo èesto se dešava da dodje i do greške prilikom upisivanja lozinke i nadimka. U sluèaju zaborava lozinke za pristup Forumu, neophodno je kreirati novu.");
$faq[] = array("Da li je registracija obavezna?", "Registracija je neophodna samo ukoliko je administrator odredio da za uèestvovanje u diskusijama morate biti èlan. Registracijom dobijate niz pogodnosti koje obièan posjetitelj Foruma nema: <i>niko se ne može predstavljati Vašim nadimkom; moguæe je personaliziranje vašeg profila; slanje direktnih poruka drugim uèesnicima (nisu javne); korištenje avatara (slièice koje odslikavaju Vaš profil); sudjelovanje u povlaštenim grupama; glasanje; slanje e-maila drugim èlanovima posredstvom Foruma </i> i slièno. Ukoliko je Forum otvorenog tipa nije potrebna nikava registracija.");
$faq[] = array("Zbog èega me Forum ponekad <i>izbaci</i>?", "U zavisnosti od toga koliko je vremena administrator Foruma odredio za svaku Vašu pojedinaènu sesiju može se desiti da Vas Forum iznenada izbaci ukoliko ste prekoraèili taj limit. Da se to ne bi dešavalo možete izabrati opciju <i><u>Prijavi me automatski</u></i>. <b>Skreæemo Vam pažnju da ovu opciju izbjegavate ukoliko Vaš kompjuter koriste i druge osobe (<i>u školi, fakultetu, radnom mjestu, Internet-kafiæ </i>) jer bi se moglo desiti da neko drugi pri dolasku na Forum bude automatski prepoznat kao da se radi o Vama.</b> ");
$faq[] = array("Kako onemoguæiti da drugi uèesnici znaju da sam istovremeno sa njima na Forumu?", "Vrlo jednostavno! Otvorite Vaš <b>Profil</b> i izaberite opciju <i><u>Sakrij moje prisustvo na Forumu</u></i>. Tada æete se voditi kao anoniman posjetilac.");
$faq[] = array("Zaboravljen password", "Kako se vrlo èesto desi da se zaboravi password koji potreban kako biste se prijavili (ušli na forum), potrebno je aktivirati novi. Procedura je vrlo jednostavna - dovoljno je otiæi na <b>login</b> sekciju i izabrati opciju <i><u>Zaboravljen password</u></i>, nakon èega æe Vam automatski biti dodijeljena nova password. Napominjemo da administratori Foruma nisu u moguænosti saznati vašu lozinku pošto se ista kodifikuje u data-bazi Foruma.");
$faq[] = array("Registracija je obavljena ali opet ne mogu uæi na Forum!", "Najèešæa greška je pogrešno upisana <i>password</i> ili <i>nadimak</i> koji ste izabrali za uèešæe na Forumu. Pored ovog, postoji još niz drugih razloga zbog kojih se ne možete prijaviti i pored uredno obavljenje registracije. Ukoliko je administrator Foruma aktivirao tzv. <u><i>COPPA</i></u> opciju i ukoliko ste prilikom registracije potvrdili da imate <b>manje od 13 godina</b>, potrebna je saglasnost roditelja za uèešæe na forumu (roditelji moraju potpisati i poslati na adresu/FAX administratora odobrenje za Vaše uèešæe na Forumu). Drugi razlog, koji takoðe zavisi od administratora, jeste da je potrebno aktivirati Vaš korisnièki raèun (account). Nakon registracije æete od administratora primiti e-mail u kojem su upute kako aktivirati account. Tek nakon što je obavljena i ova operacija možete uæi na Forum. Aktivacijom accounta od strane administratora nastoji se smanjiti moguænost zloupotreba Foruma. Ukoliko ste sve obavili kako treba pa ipak i dalje ne možete uæi, savjetujemo Vam da kontaktirate administratora i tražite objašnjenja. ");
$faq[] = array("Davno sam registrovan èlan ali ne mogu uæi na Forum!", "Najèešæi razlozi su: <li>pogrešno upisan <i><u>nadimak</u></i> ili <i><u>password</u></i> (provjerite e-mail koji ste primili od administratora prilikom registracije)</li> <li> administrator je obrisao Vaš korisnièki raèun (account). Najèešæi razlog tome je Vaša neaktivnost na Forumu (možda niste ostavili nikakvu poruku).</li>.");


$faq[] = array("--","Personaliziranje Foruma");
$faq[] = array("Kako personalizirati Forum prema svojim željama?", "Jedna od pogodnosti koje phpBB Forum nudi svojim korisnicima je njegovo <i>personaliziranje</i>. Pored <b>zvaniène</b> teme (grafièki prikaz Foruma) koju je odredio administrator moguæe je koristiti i druge teme (naravno, ukoliko je administrator aktivirao tu opciju). Svi elementi Vaše teme (ukoliko ste registrovan èlan Foruma) se èuvaju u data-bazi foruma. Sve prepravke moguæe je obaviti posredstvom  Vašeg <b>Profila</b>.");
$faq[] = array("Prikazano mi je pogrešno vrijeme?!", "Vrijeme je taèno, samo što zavisi od vremenske zone koja je vezana za Vaš <b>Profil</b>. Odabir vremenske zone u kojoj se Vi nalazite obavlja se posredstvom kontrolnog panela <b>Profil</b> (samo ukoliko ste registrovan èlan Foruma).");
$faq[] = array("Promijenio sam vremensku zonu i vrijeme još uvijek nije taèno!", "Kao što znate, u Evropi, tokom godine postoje dva raèunanja vremena - zimsko i ljetno. Tokom ljetnih mjeseci dolazi do razlike od jednog sata u odnosu na GMT a u zimskom dva. Forum nije programiran za automatsko kalkulisanje ovih perioda te se može desiti da upravo zbog toga lokalno vrijeme koje ste izabrali (npr. <i>Maglaj, Doboj, Sarajevo, Zagreb, Beograd</i>) ne odgovara realnom vremenu.");
$faq[] = array("Jezik koji želim koristiti nije naveden!", "Najvjerovatniji razlog tome je što administrator nije instalirao željeni jezik kao jedan od opcionalnih jezika Foruma ili što možda phpBB Forum još uvijek nije preveden na taj jezik. Obratite se administratoru ukoliko želite koristiti neki drugi jezik. Više informacija se može naæi na zvaniènom site-u <a href=\"http://www.phpbb.com/\" target=\"_blank\">phpBB grupe</a>.");
$faq[] = array("Prikazivanje slièica uz vlastiti nadimak.", "Jedna od pogodnosti koje phpBB Forum nudi <u>registrovanim èlanovima</u> je personaliziranje njihovog profila pomoæu raznih slièica koje æe se pojavljivati uz nadimak i tako Vas uèiniti prepoznatljivim. Jedna od tih slièica daje informacije o Vašem <b>rangu</b> i obièno su to ikone koje odredi administrator foruma. Zavisno od Vaše aktivnosti na Forumu odreðuje se i Vaš rang kao èlana - ukoliko se èešæe javljate utoliko æe i Vaš rang biti viši.<br>Druga slièica je tzv. <b>Avatar</b> i ona je Vaša <i>virtualna fotografija</i> koja Vas èini prepoznatljivim. U zavisnosti od toga kako je administrator konfigurirao forum, moguæe je koristiti Avatar iz galerije foruma, kopirati avatar s neke druge internet sranice ili pak koristiti jednu slièicu koju ste sami kreirali. Ukoliko želite, moguæe je koristiti i vlastitu fotografiju koja æe stajati pored Vašeg nadimka. Vodite raèuna o dozvoljenim velièinama slièica koje želite koristiti. Ukratko, sve zavisi od Vaše mašte.");
$faq[] = array("Kako dobiti viši rang?", "Rang koji neki korisnik ima zavisi, uglavnom, od Vaše aktivnosti na Forumu. Vezan je pretežno za broj komentara koje ostavljate i kada preðete jedan odreðeni prag, odreðen od strane administratora, dobijate viši rang. <u>Ne savjetujemo Vam upisivanje besmislenih komentara kako bi dobili viši rang jer budite sigurni da æe Vam administrator to onemoguæiti pošto na taj naèin optereæujete data-bazu na koji se <i>naslanja</i> Forum kao konstrukcija.</u> Postoji moguænost i specijalnog rangiranja. Ukoliko administrator smatra da svojim ponašanjem na forumu to zaslužujete, može se desiti da Vam dodijeli status <i>moderatora</i> i na taj naèin uèestvujete u <i>upravljanju</i> Foruma.");
$faq[] = array("Kada kliknem na ikonu za slanje e-maila nekom korisniku traži se moje logiranje (prijava)?", "Da biste mogli slati e-mail nekom korisniku posredstvom Foruma neophodno je da i sami budete <u>registrovani èlan</u>. Ovo je mjera zaštite od zloupotrebe od strane anonimnih korisnika. ");


$faq[] = array("--","Kako upisati komentar, otvoriti novu temu za diskusiju, glasati...");
$faq[] = array("Kako otvoriti novu temu za diskusiju?", "Vrlo jednostavno! Dovoljno je u indexu Foruma (popis tema i komentara) kliknuti na link (predstavljen slièicom) <u><i>Nova tema</i></u> i pratiti instrukcije. Ukoliko je Forum otvorenog tipa (svima je dozvoljeno uèešæe) registracija nije neophodna. U protivnom, potrebno je registrovati se kao èlan Foruma. Obièno se pri dnu popisa tema ili komentara unutar jedne teme nalaze navedene operacije koje možete obaviti unutar Foruma (npr. <i>Možeš ostaviti svoj komentar u ovom forumu; Možeš odgovoriti na teme ili komentare u ovom forumu;  Možeš prepraviti vlastite poruke; Možeš obrisati vlastite komentare u ovom forumu; Možeš glasati u anketama foruma;) </i>");
$faq[] = array("Kako prepraviti ili obrisati jedan komentar?", "Kao <u>registrovanom èlanu</u> Foruma dozvoljena Vam je ispravka ili brisanje <u><b>samo vlastitih</b></u> komentara. Komande za manipulisanje predstavljene su odgovarajuæim dugmadima koja se nalaze u zaglavlju svakog komentara. Ukoliko želite korigovati vlastiti komentar neophodno je kliknuti na dugme <i><u>ispravi</i></u> dok je za njegovu eliminaciju potrebno kliknuti na dugme  <b><i><u>X</u></i></b>. Treba napomenuti da se eventualno <u>brisanje</u> komentara može obaviti samo u jednom odreðenom periodu nakon èega to više nije moguæe (ukoliko neko poslije Vas upiše komentar u istu temu). Komentar možete prepraviti i nakon što se neko drugi upisao, samo što æe u tom sluèaju ostati informacije o izvršenim prepravkama pri dnu komentara.<br><i><u>Administrator i moderatori mogu obrisati ili modifikovati bilo èiji komentar te je poželjno da ostave jednu notu ukoliko to uèine pošto nakon njihovih intervencija ne ostaje nikakva automatska informacija o tome.</u></i>");
$faq[] = array("Kako potpisati vlasitu poruku?", "Ukoliko želite da Vašoj poruci bude dodan i potpis potrebno je <u>prvo</u> posredstvom <b>Profila</b> u polju <i><u>Potpis</u></i> upisati ono što želite kao potpis. Nakon toga, prilikom upisivanja komentara u formular a prije njegovog slanja izaberite opciju <i><u>Dodaj potpis</u></i>. Ukoliko želite da ova operacija bude automatska za sve Vaše komentare potrebno je posredstvom <b>Profila</b> potvrditi opciju <i><u>Dodaj uvijek moj potpis</u></i>.");
$faq[] = array("Kako kreirati anketu?", "U zavisnosti od toga da li je administrator osposobio ovu funkciju, <u>registrovanim èlanovima</u> Foruma omoguæeno je kreiranje anketa. Da biste kreirali anketu potrebno je <u>prvo otvoriti</u> novu temu i u formularu za upisivanje komentara (sekcija <i>anketa</i>) popuniti odgovarajuæa polja. Nakon upisanog pitanja potrebno je upisati željene odgovore <u>jedan po jedan</u> (<i>upisati jedan odgovor, potvrditi posredstvom komande <u>ubaci odgovor</u>, zatim upisati drugi odgovor, potvrditi i sve tako dok željena anketa ne bude kreirana</i>). Na kraju odrediti koliko dugo æe anketa biti aktuelna. Ukoliko ne želite kreirati anketu sva polja ostavite prazna. ");
$faq[] = array("Kako prepraviti ili obrisati anketu?", "Modifike ankete ili njeno brisanje je jednostavno kao i sve duge operacije unutar phpBB Foruma. Anketu mogu modifikovati ili obrisati administrator, moderator i sam autor ankete. Pošto je anketa vezana za prvi komentar unutar teme (kada kreirate anketu, automaski otvarate novu temu) neophodno je modifikovati upravo taj prvi komentar. Administrator i moderator Foruma mogu preurediti anketu u bilo kom momentu dok autor ankete to može uèiniti samo dok još niko nije glasao.");
$faq[] = array("Zašto ne mogu pristupiti pojedinim temama unutar Foruma?", "Zavisno od toga koje Vam je dozvole dodijelio administrator može se desiti da na nekim temama možete uèestvovati a na nekim drugim ne. Npr. u temama u kojima se govori o <i>kulturi</i> možete ravnopravno uèestvovati dok recimo u temi o kojoj se raspravlja o <i>kineskim leptirima</i> ne možete jer jednostavno nemate neophodne dozvole za pristup toj temi. Za u uèešæe u toj temi potrebna Vam je <em><u>posebna dozvola</u></em> od strane administratora ili moderatora.");
$faq[] = array("Zašto ne mogu glasati u anketi i pored toga što sam registrovan èlan?", "U principu, svi <u>registrovani èlanovi</u> imaju moguænost glasanja u anketama. Medjutim, može se desiti da zbog ogranièenih dozvola vezanih za Vaš korisnièki raèun (account) tu moguænost nemate. Kontaktirajte administratora za objašnjenja.");


$faq[] = array("--","Formatiranje i vrste Tema");
$faq[] = array("Šta je BBCode?", "BBCode je poseban tip HTML koda prilagodjen za potrebe foruma. Mogucnost korištenja BB-koda zavisi od toga da li je administrator foruma aktivirao ovu opciju. Ukoliko je korištenje BB-koda od strane administratora dozvoljeno ali Vi lièno ne želite da ga koristite postoji moguænost njegovog blokiranja u momentu pisanja željene poruke birajuæi opciju <u><i>Iskljuèi BB-kod u ovoj poruci</i></u>. Za razliku od HTML koda od kojeg potièe, tag-ovi su zatvoreni <b>[ ]</b> zagradama. Korištenjem BB-koda moguæe je personalizirati vlastite poruke odreðujuæi boju, velièinu, format... Za više informacja o BBCode konsultujte <a href=\"faq.php?mode=bbcode\" target=\"_blank\">poseban dio ovog vodiæa</a>. Vodiæ je takodjer moguæe konsultovati i u momentu pisanja komentara klikajuæi odgovarajuæi link (<i><b><u>BB-kod</u></b> je aktivan</i>) koji se nalazi obièno ispod liste smjehuljaka.");
$faq[] = array("Mogu li koristiti HTML?", "Zavisno od toga da li je administrator osposobio ovu opciju moguæno je i korištenje HTML-a. Medjutim, vrlo je vjerovatno da æe izbor komandi biti vrlo, vrlo sužen (samo par osnovnih komandi za formatiranje teksta). Ovo je jedna preventivna opcija zaštite jer u protivnom moglo bi doæi do konfliktnih situacija u izvršavanju naredbi foruma i HTML-a (ovo se posebno odnosi na zaglavlje kreiranih stranica). Ukoliko je dozvoljeno korištenje HTML-a ali Vi lièno ne želite izaberite opciju <i>Iskljuci HTML-kod u ovoj poruci</i>");
$faq[] = array("Šta su to Smileys (<i>smjehuljci</i>)?", "To su male slièice pomoæu kojih možete izraziti Vaše raspoloženje. Ukoliko u Vašoj poruci napišete  npr. <b>:)</b> znaèi da ste sretni ili ako upišete <b>:(</b> znaèi da ste tužni. Kombinaciju znakova interpukcije i slova Forum automatski interpretira kao <i>SMJEHULJKA</i> i iz svoje data-baze prikazuje slièicu vezanu za svaku posebnu kombinaciju. Ukoliko ne želite smjehuljak u Vašoj poruci izaberite opciju <i>Iskljuèi smjehuljke u ovoj poruci<i>. ");
$faq[] = array("Kako pokazati slike unutar vlastite poruke?", " Da biste željenu sliku pokazali u Vašem komentaru neophodno je da je ona veæ negdje objavljena na Internetu. Ono što Vi treba  da uradite je da samo ubacite taèan URL slike (da se '<i>linkujete'</i>). <br>Npr. ukoliko znate da se na Internet stranici <b><i>www.maglaj.info</i></b> nalazi jedna slièica sa imenom <b><i>maglaj.jpg </i></b> u direktoriju <b><i>slike</i></b> upisaæete sljedeæi BBcod (<i>ili odgovarajuæi HTML kod -pod uslovom da je dopušten</i>):<br><b><i>[img]http://www.maglaj.info/slike/maglaj.jpg[/img]</i></b><br>Link nije efikasan ukoliko vodi na sliku u Vašem kompjuteru (osim ako Vaš kompjuter nije Internet server); ukoliko se nalazi na stranicama zaštiæenim lozinkom; ukoliko se nalazi unutar mailing sistema (<i>Hotmail, Yahoo mail-boxes</i>) ");
$faq[] = array("Šta su Obavještenja?", "Obavještenja su teme u kojima možete naæi razne informacije. Predstavljene su posebnim ikonama kako bi što lakše privukle Vašu pažnju. Da li možete ostavljati poruke unutar takve teme zavisi od administratora. U ovoj verziji prevoda takve teme su naznaèene kao <b><i>Obavještenja</i></b>.");
$faq[] = array("Šta su <i>Važne informacije (Sticky Topics)</i>?", "To su takodje posebne teme predstavljene nekom karakteristiènom ikonom kako bi što lakše privukli Vašu pažnju. U listi tema se nalaze uvijek pri vrhu (obièno ispod eventualnih <i>Obavještenja</i>) te se preporuèuje da ih konsultujete. Da li možete ostavljati poruke unutar takve teme zavisi od administratora. U ovoj verziji prevoda takve teme su naznaèene kao <b><i>Ne propusti</i></b>.");
$faq[] = array("Šta su to <i>Zatvorene teme</i>?", "Zatvorene teme su one u koje nije moguæe upisati više nijedan komentar. Zatvaranje  neke teme je, kao i njeno eventualno ponovno otvaranje,  u nadležnosti moderatora i administratora.");


$faq[] = array("--","Grupe korisnika, administratori, moderatori...");
$faq[] = array("Ko je Administrator?", " Administrator je osoba koje se brine o pravilnom funkcionisanju Foruma. Nalazi se na vrhu piramide kontrolnog sistema Foruma i praktièno ima neogranièenu <i>vlast</i> <b> :)</b>. Oni odredjuju: <i>sve vrste dozvoljenih operacija na Forumu; kreiranje povlaštenih grupa; kreiranje glavnih kategorija tema; sve opcije kontrole pristupa <b>svim</b> korisnicima Foruma; dodjeljivanje <b>moderatorskog statusa</b>  pojedinim uèesnicima</i> te niz drugih operacija. Ukratko - <u>njegova rijeè je zadnja</u> u svemu onome šo se tièe Foruma. ");
$faq[] = array("Ko su moderatori?", "Moderatori su osobe kojima je taj status dodjeljen od strane administratora i imaju zadatak da prate i usmjeravaju diskusije na najbolji mogæi naèin. Ovlaštenja koja imaju dopuštaju im <i>prepravku tudjih komentara, brisanje tudjih komentara, zatvaranje i otvaranje tema, pomjeranje i dijeljenje pojedinih tema na više tema</i> i slièno.");
$faq[] = array("Šta su to <i>Grupe korisnika</i>?", "Grupe korisnika kreira administrator prema svojim vlastitim kriterijima. Svaki <u>registrovani èlan</u> može uèestvovati u više grupa i to phpBB Forum razlikuje od mnogih sliènih programa. Svaka grupa može imati razlièite dozvole i ovlaštenja, pristup odreðenim temama koji su zatvoreni za obiène korisnike i sl. Takodje, posredstvom <i>grupa</i> administrator lakše organizuje moderiranje pojedinih tema.");
$faq[] = array("Kako postati èlan jedne <i>grupe korisnika</i>?", "Da biste postali èlan jedne grupe korisnika neophodno je zatražiti prijem u èlanstvo. Posredstvom linka <i><b>Grupe korisnika</b></i> (<i>obièno je lociran u zaglavlju stranice - ovo zavisi od dizajna teme koji koristite</i>) potrebno je ispuniti odgovarajuæi formular i uputiti ga moderatoru ili administratoru koji kontroliše pristup željenoj grupi. Može se desiti da od Vas traže objašnjenja zbog èega želite biti èlan grupe. Konaèna odluka da li æete biti primljeni ili ne zavisi samo od moderatora/administratora te ukoliko eventualno odbiju Vaš zahtijev nemojte previše insistirati. Vjerovatno postoje razlozi za takvu odluku.");
$faq[] = array("Kako kreirati grupe korisnika?", "Kreiranje <i>grupa korisnika</i> i odreðivanje njihovih moderatora je <b><i>iskljuèivo</i></b> u kompetenciji administratora.  Ukoliko želite da bude kreirana jedna nova grupa neophodno je dobiti saglasnost administratora (zamoliti ga da kreira željenu grupu). Kao i u svemu ostalom i ovdje je odluka administratora konaèna.");
$faq[] = array("Kako postati moderator grupe korisnika?", "Ovo zavisi <b><i>iskljuèivo</i></b> od administratora pošto on kreira grupe korisnika i odreðuje njihove moderatore. Kao i u svemu ostalom i ovdje je odluka administratora konaèna.");


$faq[] = array("--","Privatne poruke");
$faq[] = array("Šta su to <i>privatne poruke</i>?", "Privatne poruke su poseban naèin komuniciranja izmeðu <u>registrovanih èlanova</u> Foruma. Svakom uèesniku prilikom registracije bude automatski dodijeljen jedan <i>pretinac</i> u koji dolaze privatne poruke drugih èlanova i posredstvom kojeg je moguæe poslati vlastite privatne poruke. Ove poruke nisu javne (<i>niko drugi osim Vas i Vašeg korespondenta ne može znati za njih</i>).");
$faq[] = array("Ne mogu poslati privatne poruke!", "Razlozi su vjerovatno sljedeæi:<br><li></li>niste registrovan èlan Foruma ili se možda niste <i>logirali</i> (<i>prijavili</i>)<li></li>administrator nije dozvolio korištenje ove moguænosti nikome <li></li>aministrator nije dozvolio baš Vama tu pogodnost. Ovo se može desiti kao sluèajan previd administratora, ali isto tako može postojati nekakav razlog za tako nešto. Zbog toga Vam savjetujemo da tražite objašnjenja ( <i>i da ne mislite odmah kako neko ima nešto protiv Vas</i> <b>:)</b> ).");
$faq[] = array("Stižu mi neželjene privatne poruke!", "U ovom sluèaju najbolje je obavijestiti administratora koji ima odgovarajuæe instrumente na raspolaganju za prevenciju ovakvih situacija.");
$faq[] = array("Kako se zaštiti od <i>spam-a</i> i uvredljivih privatnih poruka?", " Molimo Vas da se u ovom sluèaju <u><b>obavezno</b></u> obratite administratoru prilažuæi kopiju ovakvih poruka (<i>obavezno priložiti <b>zaglavlje poruke</b> koje sadrži informacije o pošiljaocu</i>). Administrator je u moguænosti, posredstvom instrumenata koji su mu na raspolaganju, preduzeti neophodne mjere Vaše zaštite.");

//
// These entries should remain in all languages and for all modifications
//
$faq[] = array("--","phpBB 2");
$faq[] = array("Ko je kreirao ovaj program?", "Ovaj program (u njegovom originalnom obliku) je kreirao, zaštitio  autorskim pravima i distribuira <a href=\"http://www.phpbb.com/\" target=\"_blank\">phpBB Group</a>. Molimo Vas da konsultujete uslove javne dozvole (<i><b>GNU - General Public Licence</b></i>) pod kojima je moguæe korištenje Foruma i eventualne modifike originalnog software-koda. Za više detalja konsultovati <a href=\"http://www.phpbb.com/\" target=\"_blank\">ovaj</a> link.");
$faq[] = array("Zbog èega u programu nema  \"X-funkcije\" <i>(pod ovim se podrazumijeva nešto što mislite da nedostaje Forumu kao programu)</i>?", "Ukoliko smatrate da bi Forumu trebalo dodati jednu novu funkcionalnost molimo Vas da posjetite stranicu <a href=\"http://www.phpbb.com/\" target=\"_blank\">phpBB grupe</a> i da èujete njihovo mišljenje, kao nosioca autorskih prava ovog software-a. Molimo Vas da konsultujete i Forum phpBB grupe jer  tamo se veæ eventualno nalazi rješenje Vašeg problema (želje). phpBB grupa se oslanja na <i>Sourceforge</i> u vezi kreiranja novih funkcionalnosti te Vas molimo da ne <i><u>preotereæujete</u></i> Forum Vašim zahtijevima (osim ako to zaista nije nužno neophodno).");
$faq[] = array("U sluèaju zloupotrebe Foruma ili pravnih problema koga kontaktirati?", "Ukoliko smatrate da je došlo do zloupotrebe Foruma od strane nekog od njegovih uèesnika obratite se direktno nekom od <b><i>moderatora</i></b>, <b><i>administratoru</i></b>, ili <b><i>vlasniku domain-a</i></b> koji je dozvolio ili lièno obavio instalaciju Foruma unutar svoje Internet stranice. Vlasnika domain-a je moguæe pronaæi koristeæi razne servise tipa <i><b>whois</b></i> koji su besplatni i koje možete pronaæi na internetu (jedan od najpoznatijih se nalazi na stranici <a href=\"http://www.whois.com/\" target=\"_blank\">www.whois.com</a>). U sluèaju da je Forum instaliran unutar servisa koji nude besplatan web-prostor korisnicima Interneta (npr. <i>yahoo, free.fr, f2s.com</i>) pokušajte kontaktirati administratore tih servisa.<br> Imajte na umu da sve eventalne zloupotrebe (npr: <i>odgovornost za upisane komentare, klevete i sl</i>.)  koje se dešavaju unutar Foruma <b><u>nisu stvar koja se tièe phpBB grupe</u></b> te nema smisla kontaktirati ih u vezi toga. Neæete dobiti nikakav odgovor!<br>  <b><u>phpBB grupa ne prihvata bilo kakvu legalnu odgovornost za zloupotrebe njenog software-a</u></b>!  Sve ono što nije <b><u>direktno</u></b> vezano za <a href=\"http://www.phpbb.com/\" target=\"_blank\">internet stranicu</a> phpBB grupe ili njihov software (kršenje uslova javne dozvole (<i><b>GNU - General Public Licence</b></i>) je <b><u>samo Vaš problem</u></b>!");


$faq[] = array("--","Prevod");
$faq[] = array("Informacije u vezi prevoda.","Prevod za južnoslavenske jezike obezbjedio je <a href=\"http://www.maglaj.info/\" target=\"_blank\"> www.maglaj.info</a> koristeæi italijansku verziju phpBB Foruma a na èemu zahvaljujemo <a href=\"http://www.snowbox.it//\" target=\"_blank\"> www.snowbox.it</a>.  <b><i>Grazie ragazzi!</i></b><br><br>Ukoliko želite koristiti ovaj prevod dovoljno je da nas kontaktirate na jedan od sljedeæih e-mailova:<li> <a href=\"mailto:mrmot@vizzavi.it\">Golac Željko</a></li><li><a href=\"mailto:ruval@gmx.ch\">Ruviæ Alen</a></li><li><a href=\"mailto:webmaster@maglaj.info\">Info.team</a></li><br>Jednu kopiju prevoda za potrebe Vašeg Foruma možete dobiti <a href=\"http://www.maglaj.info/download/lang_bosnia.zip\" target=\"_blank\"><b>ovdje</b></a>.<br> Ukoliko primjetite da u bilo kom dijelu prevoda postoje nejasnoæe ili greške molimo Vas da nam na to skrenete pažnju. I za kraj, jedna poruka autora prevoda:<br> <i><u>Sve je ovo samo igra! Nema tog foruma koji je vrijedan Vaših živaca!</u></i>");

//
// This ends the FAQ entries
//

?>