<?php
/***************************************************************************
 *          lang_bbcode.php [Bosnia-Croatia-Serbia-Montenegro]
 *                            -------------------
 *   begin                : Wednesday Oct 3, 2001
 *   copyright            : (C) 2001 The phpBB Group
 *   email                : support@phpbb.com
 *   $Id$
 *
 *
 ***************************************************************************/

/***************************************************************************
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 ***************************************************************************/
 
/***************************************************************************
 *     Prevod s italijanske verzije phpBB Foruma: Golac Željko, Alen Ruvic *
 *     pocetak prevoda      : Subota, 28. septembar 2002                   *
 *     web                  : http://www.maglaj.info                       *
 *     e-mail               : mrmot@vizzavi.it, ruval@gmx.ch               *
 ***************************************************************************/
 

// 
// To add an entry to your BBCode guide simply add a line to this file in this format:
// $faq[] = array("question", "answer");
// If you want to separate a section enter $faq[] = array("--","Block heading goes here if wanted");
// Links will be created automatically
//
// DO NOT forget the ; at the end of the line.
// Do NOT put double quotes (") in your BBCode guide entries, if you absolutely must then escape them ie. \"something\";
//
// The BBCode guide items will appear on the BBCode guide page in the same order they are listed in this file
//
// If just translating this file please do not alter the actual HTML unless absolutely necessary, thanks :)
//
// In addition please do not translate the colours referenced in relation to BBCode any section, if you do
// users browsing in your language may be confused to find they're BBCode doesn't work :D You can change
// references which are 'in-line' within the text though.
//
  
$faq[] = array("--","Uvod");
$faq[] = array("Šta je to BB-kod?", "BB-kod je modifikovani HTML kod prilagodjen za potrebe foruma. Moguænost korištenja BB-koda zavisi od toga da li je administrator foruma aktivirao ovu opciju. Ukoliko je korištenje BB-koda od strane administratora dozvoljeno ali Vi lièno ne želite da ga koristite postoji moguænost njegovog blokiranja u momentu pisanja željene poruke birajuæi opciju <b>Iskljuci BB-kod u ovoj poruci</b>. Za razliku od HTML koda od kojeg potièe, tag-ovi su zatvoreni <b>[</b> <b>]</b> zagradama. Korištenjem BB-koda moguæe je personalizirati vlastite poruke odredjujuæi boju, velièinu, format ...<br /><br />napomena: Web-masteri koji poznaju HTML sigurno neæe imati problema u korištenju BB-koda te ih molimo da nam ne zamjere u nastojanju da što slikovitije objasnimo njegovo korištenje uèesnicima foruma koji nisu baš praktièni.<br /><br />Važno je shvatiti princip korištenja tag-ova (jednostavne naredbe koje æe željeni tekst formatirati prema vašim željama) koji je vrlo jednostavan: ono što želite da bude formatirano mora biti unutar dva tag-a, tj. jednog poèetnog i jednog završnog. Najjednostavniji primjer je primjer podebljanog teksta. Da bi ste dobili podebljani tekst potrebna su nam dva tag-a:<ul><b>[b]</b> poèetni tag za podebljana slova <br /><b>[/b]</b> završni tag za podebljana slova</ul>Sve što je potrebno uèiniti je ubaciti željenu rijeè ili tekst <b>izmeðu</b> ova dva navedena tag-a: <br />npr.<b>[b]</b>Moje je ime šef tamne strane mjeseca...<b>[/b]</b><br /><br />Rezultat:<b> Moje je ime šef tamne strane mjeseca...</b>	<br />Napomena:<br />U prozoru koji vam se otvori kada želite ostaviti svoj komentar veæ postoje ubaèene komande u vidu <b>dugmadi</b> (obièno iznad polja gdje se upisuje tekst) te vjerujemo da neæe biti veæih problema pri korištenju BB-koda. ");

$faq[] = array("--","Formatiranje teksta");
$faq[] = array("Kako kreirati tekst sa podebljanim, podvuèenim ili nakošenim slovima?", " <ul><li><b>Podebljana slova </b>æeš dobiti ukoliko željeni tekst postaviš [b]<b>ovdje</b>[/b]</b>, npr. <br /><br /><b>[b]</b>...Lud sam za tobom, ali ovo jeste vreme ludih, i ja æu za nas osedlati strah,<br />A ti me ljubi do zla, dok ne izgubim dah...<b>[/b]</b><br /><br >rezultat:<br /> <b>...Lud sam za tobom, ali ovo jeste vreme ludih, i ja æu za nas osedlati strah,<br />A ti me ljubi do zla, dok ne izgubim dah...</b></li><li>Za podvuèeni tekst tag-ovi su:<b>[u][/u]</b>, npr.:<br /><br /><b>[u]</b>...Ne znaš ti, nema oslobodjenih, svaku tišinu mi granata prošara. <br />Spašen je taj prvi pogodjeni, a svi su drugi veèni taoci košmara... <b>[/u]</b><br /><br />rezultat:<br /> <u>...Ne znaš ti, nema oslobodjenih, svaku tišinu mi granata prošara. <br />Spašen je taj prvi pogodjeni, a svi su drugi veèni taoci košmara... </u></li><li>Tekst sa nakošenim slovima (korzivan) se dobije pomoæu tag-ova <b>[i] [/i]</b>, npr.<br /><br > <b>[i]</b>Gospodar muva, ljubavnik kurvi i kraljica<b>[/i]</b><br /><br /><i>Gospodar muva, ljubavnik kurvi i kraljica</i></li></ul>");

$faq[] = array("Kako promijeniti boju i velièinu slova?", "Tag-ovi za odredjivanje boje i velièine slova su sljedeæi:<br /><br ><b>[color=][/color]</b> za boju<br /><br ><b>[size=][/size]</b>  za velièinu slova.<ul><li>Boja slova se može promijeniti ukoliko se željeni tekst ubaci izmeðu sljedeæih tag-ova: <b>[color=][/color]</b> i to  na dva naèina:  <u><b>a.)</b>njenim imenovanjem </u> (npr. red, blue, yellow, black, itd.; koriste se engleski nazivi boja) ili <u><b>b.)</b> ubacivanjem odgovarajuæeg heksadecimalnog koda koda</u> koji definiše boju kao npr. <span style=\"color:CC66FF \">CC66FF </span>, <span style=\"color:#009900\">#009900 </span>, <span style=\"color:#CC3300\">#CC3300</span>. Pošto je heksadecimalni kod malo komplikovan za pamæenje savjetujemo vam da pokušate eksperimentisati sa kombinacijama slova i brojeva i rezultat æe biti sigurno zanimljiv.Primjer:<br /><br /><b>[color=red]</b>crvena boja<b>[/color]</b><br /><br />ili<br /><br /><b>[color=#FF0000]</b>crvena boja<b>[/color]</b><br /><br />daju isti rezultat: <span style=\"color:red\">crvena boja</span></li><li>Velièina slova (karaktera) se definiše pomoæu tag-ova: <b>[size=] [/size]</b>.Ovaj tag je u zavisnosti od jediniène mjere koja se koristi za odreðivaje velièine te se stoga preporuèuje da se na forumu koriste velièine izmedju  <b>1</b> <i>pixel</i> (predstavlja najmanju vrijednost; skoro da se i ne vidi) i <b>29</b> (velika slova.) npr:<br /><br /><b>[size=9]</b>mala slova<b>[/size]</b><br /><br />trebao bi biti <span style=\"font-size:9px\">mala slova</span><br /><br />dok:<br /><br /><b>[size=24]</b>ogromna slova<b>[/size]</b><br /><br />æe biti <span style=\"font-size:24px\">ogromna slova</span></li></ul>");

$faq[] = array("Da li je moguæe kombinovati tag-ove?", "Da, moguæe je kombinovati tag-ove kako bi tekst bio formatiran prema vašim željama. Pri tome se mora imati na umu jedno jednostavno pravilo a to je da tagovi moraju biti <b>zatvarani</b> (kombinacija [<span style=\"color:red\">/</span> neki tag] ) obrnutim redom od njihovog otvaranja tj. prvi otvarajuci tag ( u ovom primjeru <b>[size]</b> mora biti i zadnji u nizu  zatvarajuæih tag-ova kao <b>[/size]</b>)<br /> <br /> <b><span style=\"color:#CC3300\">[size=18]</span><span style=\"color:#663399\">[color=red]</span><span style=\"color:#CC3366\">[b]</span></b>Pristao sam biæu sve što hoæe...<b><span style=\"color:#CC3366\">[/b]</span><span style=\"color:#663399\">[/color]</span><span style=\"color:#CC3300\">[/size]</span></b>:<br /><br /> <span style=\"color:red;font-size:18px\"><b>Pristao sam biæu sve što hoæe...</b></span><br /><br />Nije da želimo ogranièiti vašu maštu ali preporuèujemo da se ne pretjeruje baš puno u ovim kombinacijama. Tako bi tekst vrlo brzo mogao postati neèitak pa se smisao vašeg komentara može lako previdjeti. Ovakvo formatiranje teksta se preporuèuje ukoliko želite naglasiti nešto i na taj naèin skrenuti pažnju onoga ko èita vaše upise");

$faq[] = array("--","Citiranje izjava i tekst fiksnih karakteristika");
$faq[] = array("Kako citirati nekoga?", "Postoje dva naèina citiranja poruka.<ul><li>Ukoliko želite citirati neèiji prethodno upisani komentar dovoljno je da aktivirate komandu <b>citiraj</b> koja se nalazi u zaglavlju poruke koju želite citirati (ikona <b>quote</b>). Automatski æe se aktivirati tag-ovi  <b>[quote=\"\"][/quote]</b>. Na ovaj naèin æe biti citirana <b>èitava</b> poruka nekog uèesnika.<br />Npr. za citiranje poruke korisnika sa nadimkom <i>Gost</i></>:<br /><br /><b>[quote=\"Gost\"]</b>Ono što je <i>Gost</i> rekao stajaæe ovdje<b>[/quote]</b><br /><br /> Jednom upisanoj poruci na ovakav naèin æe prethoditi sljedeæi tekst: <b>Gost (citat)...</b>kako bi se znalo da je <i>Gost</i> bio citiran. Ne zaboravite da ukoliko želite da bude naveden autor nekog citata njegovo ime <b>mora</b> biti navedeno u navodnicima tag-a <b>[quote=\"\"]</b>.</li><li>Drugi naèin citiranja je još jednostavniji pošto se u ovom sluèaju autor ne treba navoditi. Dovoljno je željeni tekst ubaciti izmedju tag-ova  <b>[quote][/quote]</b>. Primjetiæete da se, za razliku od gornjeg sluèaja, ne koriste navodnici. Nakon upisivanja poruke na forum njoj æe prethoditi automatski dodana poruka kako se radi o nekom citiranom tekstu (<b>Citat</b>).</li></ul>");
$faq[] = array("Prikazivanje teksta u vidu koda ili fiksnog teksta", "Ukoliko želiš pokazati npr.dio nekog koda gdje bi trebale biti navedene korektno komande koje karakterišu dotièni kod, preporuèuje se korištenje tag-a <b>[code][/code]</b>, npr.<br /><br /><b>[code]</b>echo \"Ovo je dio koda\";<b>[/code]</b><br /><br />");

$faq[] = array("--","Liste (popisi)");
$faq[] = array("Kreiranje liste bez reda", "BB-kod podržava dvije vrste lista: <b>liste sa redom</b> i <b>liste bez reda</b> i potièu od njihovih ekvivalenata HTML-koda. Kod liste bez reda elementi liste su poredani sekvencijalno, jedan poslije drugog, svaki u zasebnom redu i predstavljen obièno nekim grafièkim simbolom (taèka, zvjezdica i slièno). Elementi liste nisu numerisani veæ su ubaèeni sluèajnim redom.<br />Komanda BB-koda koja je potrebna za kreiranje ovakve liste je <b>[list][/list]</b>, a svaki element u listi æe biti definisan koristeæi <b>[*]</b>. Ukoliko npr. želite napraviti listu Vaših omiljenih <i>kolaèa</i> trebali bi uèiniti ovako: <br /><br /><b>[list]</b><br /><b>[*]</b>krempita<br /><b>[*]</b>šampita<br /><b>[*]</b>baklava<br /><b>[/list]</b><br /><br />Rezultat je ovaj:<ul><li>krempita</li><li>šampita</li><li>baklava</li></ul>");
$faq[] = array("Kreiranje liste sa redom", "Za razliku od <i>liste bez reda</i>, elementi ove liste jedan precizan red i moguæe je kontrolisati naèin prikazivanja elemenata u listi. Obièno se koriste dva naèina redanja elemenata u listi: <i>numerièki</i> i <i>abecedni</i>. Za kreiranje <i>numerièke liste</i> se koristi tag<b>[list=1][/list]</b>, dok je za abecednu listu taj tag malo drugaèiji: <b>[list=a][/list]</b>. Kao i u listi bez reda, elementi unutar liste se definišu pomoæu <b>[*]</b>. Primjer:<br /><br /><b>[list=1]</b><br /><b>[*]</b>ustani ranom zorom i idi na posao<br /><b>[*]</b>zaradi novac<br /><b>[*]</b>kupi djetetu kompjuter i ostatak (ako ti ga žena veæ nije otela) sakrij <b>:)</b><br /><b>[/list]</b><br /><br />rezultat:<ol type=\"1\"><li>ustani ranom zorom i idi na posao</li><li>zaradi novac</li><li>kupi djetetu kompjuter i ostatak (ako ti ga žena veæ nije otela) sakrij <b>:)</b></li></ol>Primjer abecedne liste: <br /><i>U šta je teže gledati?</i><br /><b>[list=a]</b><br /><b>[*]</b>punicu<br /><b>[*]</b>sunce<br /><b>[*]</b>ženu<br /><b>[/list]</b><br /><br />rezultat:<br /><i>U šta je teže gledati?</i><br /><ol type=\"a\"><li>punicu</li><li>sunce</li><li>ženu</li></ol>");

$faq[] = array("--", "Linkovanje - kako uspostaviti vezu sa nekim drugim web-siteom");
$faq[] = array("Kako se linkovati?", " BB-kod phpBB Foruma omoguæava ralièite naèine za kreiranje URI, <i>Uniform Resource Indicators</i>, bolje poznati kao <i>URL</i>.<ul><li>Prvi naèin je korištenje tag-ova <b>[url=][/url]</b>, što god se upiše poslije  <b>=</b> kreiraæe se saržaj taga koji æe se ponašati kao URL. Npr. ukoliko se želite povezati na internet stranicu grada Maglaja potrebno je uèiniti ovako:<br /><br /><b>[url=http://www.maglaj.info/]</b>Posjeti Maglaj!<b>[/url]</b><br /><br />Na ovaj naèin kreiraæete sljedeæi link: <a href=\"http://www.maglaj.info/\" target=\"_blank\">Posjeti Maglaj!</a>. Klikajuæi potom na navedeni link u novom prozoru æe se otvoriti navedena stranica a Vi æete i dalje ostati unutar Foruma.</li><li>Ukoliko želite da u linku bude prikazan URL (<i>internet adresa</i>)treba postupiti ovako: <br /><br /><b>[url]</b>http://www.maglaj.info/<b>[/url]</b><br /><br />Ovo æe kreirati sljedeæi link: <a href=\"http://www.maglaj.info\" target=\"_blank\">http://www.maglaj.info</a></li><li>phpBB Forum raspolaže jednim instumentom koji æe Vam u mnogome olakšati kreiranje linkova unutar Vaših komentara. Pomoæu <i>Magic Links</i> (<i>èarobni linkovi</i>), se kreiraju automatski linkovi, bez potrebe gore navedenih tag-ova ili <i>http://</i>, pod uslovom da je adresa (<i>URL</i>) sintaksièki ispravno upisana. Ukoliko upišete npr. <i>www.maglaj.info</i> unutar Vaše poruke, to æe automatski biti prevedeno u: <a href=\"http://www.maglaj.info/\" target=\"_blank\">www.maglaj.info</a> i biæe prikazano kao finalni rezultat.</li><li>Ista stvar se dešava i sa e-mail adresama:<br /><br /><b>[email]</b>webmaster@maglaj.info<b>[/email]</b><br /><br />æe biti prikazano kao: <a href=\"emailto:webmaster@maglaj.info\">webmaster@maglaj.info</a><br /> ili posredstvom automatskog kreiranja: otkucajte samo adresu (bez tag-ova) <i>webmaster@maglaj.info</i> i rezultat àe biti isti.</li></ul> Kao i za sve druge tag-ove BB-koda, tako i za URL tag vrijedi pravilo da može ukljuèen unutar nekog drugog tag-a (<b>[img][/img]</b>, <b>[b][/b]</b> itd.). <u>Ne zaboravite važnost redosljeda otvaranja i zatvaranja tag-ova</u>.<br /> Primjer pogrešnog zatvaranja tag-ova:<br /><b><span style=\"color:#FF3300\">[url=http://www.phpbb.com/]</span><span style=\"color:#3300FF\">[img]</span>pogrešno zatvoreni tag-ovi<span style=\"color:#FF3300\">[/url]</span><span style=\"color:#3300FF\">[/img]</span><br /></b>Pravilno zatvoreni tag-ovi:<br /><b><span style=\"color:#FF3300\">[url=http://www.phpbb.com/]</span><span style=\"color:#3300FF\">[img]</span>pravilno zatvoreni tag-ovi<span style=\"color:#FF3300\"><span style=\"color:#3300FF\">[/img]</span>[/url]</span><br /></b> ");

$faq[] = array("--", "Slike unutar komentara?");
$faq[] = array("Kako ubaciti sliku u komentar", "Pomoæu BB-koda vrlo je jednostavno ubaciti neku sliku u Vaš komentar. Potrebno je da je željena slika veæ objavljena na Internetu. Procedura je vrlo jednostavna, potrebno je ubaciti URL slike u odgovarajuæi tag: <b>[img][/img]</b>. Primjer:<br /><br /><b>[img]</b>http://www.phpbb.com/images/phplogo.gif<b>[/img]</b><br /><br />Slika se može ubaciti i unutar tag-a <b>[url][/url]</b> kao u ovom primjeru:<br /><br /><b>[url=http://www.phpbb.com/][img]</b>http://www.phpbb.com/images/phplogo.gif<b>[/img][/url]</b><br /><br />kreira:<br /><br /><a href=\"http://www.phpbb.com/\" target=\"_blank\"><img src=\"templates/subSilver/images/logo_phpBB_med.gif\" border=\"0\" alt=\"\" /></a><br />");

$faq[] = array("--", "Ostalo");
$faq[] = array("Da li je moguæe koristiti personalne tag-ove?", "Ne, bar ne direktno unutar phpBB 2.0. Trudimo se da u iduæoj verziji software-a uèinimo fleksibilnijim korištenje tag-ova.");

$faq[] = array("--","Prevod");
$faq[] = array("Informacije u vezi prevoda.","Prevod za južnoslavenske jezike obezbjedio je <a href=\"http://www.maglaj.info/\" target=\"_blank\"> www.maglaj.info</a> koristeæi italijansku verziju phpBB Foruma a na èemu zahvaljujemo <a href=\"http://www.snowbox.it//\" target=\"_blank\"> www.snowbox.it</a>.  <b><i>Grazie ragazzi!</i></b><br><br>Ukoliko želite koristiti ovaj prevod dovoljno je da nas kontaktirate na jedan od sljedeæih e-mailova:<li> <a href=\"mailto:mrmot@vizzavi.it\">Golac Željko</a></li><li><a href=\"mailto:ruval@gmx.ch\">Ruviæ Alen</a></li><li><a href=\"mailto:webmaster@maglaj.info\">Info.team</a></li><br>Jednu kopiju prevoda za potrebe Vašeg Foruma možete dobiti <a href=\"http://www.maglaj.info/download/lang_bosnia.zip\" target=\"_blank\"><b>ovdje</b></a>.<br> Ukoliko primjetite da u bilo kom dijelu prevoda postoje nejasnoæe ili greške molimo Vas da nam na to skrenete pažnju. I za kraj, jedna poruka autora prevoda:<br> <i><u>Sve je ovo samo igra! Nema tog foruma koji je vrijedan Vaših živaca!</u></i>");

//
// kraj BBcode vodica
//

?>