<?php
/***************************************************************************
 *                          lang_faq.php [english]
 *                            -------------------
 *   begin                : Wednesday Oct 3, 2001
 *   copyright            : (C) 2001 The phpBB Group
 *   email                : support@phpbb.com
 *
 *   $Id$
 *
 *
 ***************************************************************************/

/***************************************************************************
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 ***************************************************************************/
 
// Indonesian Translation: Ivan R. Lanin <ivan@konsep.net>
// Last Update: 2002-11-27 01:26

// 
// To add an entry to your FAQ simply add a line to this file in this format:
// $faq[] = array("question", "answer");
// If you want to separate a section enter $faq[] = array("--","Block heading goes here if wanted");
// Links will be created automatically
//
// DO NOT forget the ; at the end of the line.
// Do NOT put double quotes (") in your FAQ entries, if you absolutely must then escape them ie. \"something\";
//
// The FAQ items will appear on the FAQ page in the same order they are listed in this file
//
 
  
$faq[] = array("--","Masalah Login dan Registrasi");
$faq[] = array("Mengapa saya tak bisa login?", "Sudahkan Anda mendaftar? Serius, Anda harus mendaftar untuk dapat login. Pernahkan Anda di-banned dari forum (pesan mengenai hal ini akan ditampilkan jika betul)? Jika ya, Anda harus menghubungi webmaster atau administrator forum untuk mengetahui mengapa Anda di-banned. Jika Anda telah mendaftar dan tidak di-banned dan Anda masih juga tidak bisa login, cek dan cek ulang username dan password Anda. Biasanya disini letak permasalahannya. Jika masih juga ada masalah, kontak Administrator, mereka mungkin membuat setting konfigurasi yang salah untuk forum diskusi ini.");
$faq[] = array("Mengapa saya harus mendaftar?", "Anda tidak harus mendaftar, hal ini tergantung pada Administrator apakah seseorang harus mendaftar untuk dapat mengirimkan pesan. Bagaimanapun juga, registrasi akan memberikan Anda akses ke berbagai fitur tambahan yang tidak tersedia bagi tamu, seperti gambar Avatar, Pesan Pribadi, mengirim email ke pengguna lain, pendaftaran user group, dll. Proses pendaftaran hanya memakan waktu sebentar, jadi sebaiknya Anda melakukan hal tersebut.");
$faq[] = array("Mengapa saya logout secara otomatis?", "Jika Anda tidak mencek pilihan <em>Login Otomatis</em> sewaktu login, sistem hanya akan mempertahankan login Anda selama waktu tertentu. Hal ini untuk mencegah penggunaan account Anda oleh orang lain secara tak bertanggungjawab. Untuk tetap login, cek pilihan tersebut sewaktu Anda login. Hal ini tidak dianjurkan jika Anda mengakses forum dari komputer publik, seperti pada perpustakaan, warnet, komputer kampus, dll.");
$faq[] = array("Bagaimana saya mencegah username saya tampil pada daftar user yang sedang online?", "Pada bagian profil, Anda akan menemukan pilihan <em>Sembunyikan status online</em>. Jika Anda memilih pilihan ini, sataus Anda hanya akan dapat dilihat oleh Admin atau Anda sendiri. Anda akan dianggap sebagai user tersembunyi.");
$faq[] = array("Saya lupa password saya!", "Jangan panik! Walaupun password Anda tidak bisa dikembalikan, password tersebut dapat direset. Untuk melakukan hal ini, pergi ke halaman login dan klik <u>Lupa Password</u>, ikuti instruksi dan Anda akan kembali online secepatnya.");
$faq[] = array("Saya sudah mendaftar tapi tak bisa login!", "Pertama, cek apakah Anda memasukkan username dan password yang benar. Jika ya, ada dua hal yang mungkin terjadi. Jika COPPA diaktifkan dan Anda mengklik <u>Saya berusia di bawah 13 tahun</u> sewaktu pendaftaran, maka Anda harus mengikuti instruksi yang Anda terima. Jika tidak, cek apakah account Anda perlu diaktivasi? Beberapa forum mengharuskan semua pendaftaran untuk diaktivasi, baik oleh Anda sendiri maupun Administrator sebelum Anda dapat login. Sewaktu Anda mendaftar, Anda akan diberitahu apakah pendaftaran membutuhkan aktivasi. Jika Anda menerima email, ikuti instruksi di dalamnya. Jika tidak, periksa apakah alamat email yang Anda masukkan valid? Salah satu alasan diperlukan aktivasi adalah untuk mengurangi kemungkinan seseorang mengacaukan forum secara anonim. Jika Anda yakin alamat email yang Anda gunakan valid, maka cobalah kontak Administrator.");
$faq[] = array("Saya pernah mendaftar dulu, tapi kini tak bisa login?!", "Alasan utama untuk hal ini adalah; Anda memasukkan username dan password yang salah (cek email yang Anda gunakan sewaktu mendaftar) atau Administrator telah menghapus account Anda karena satu dan lain hal. Jika yang terakhir yang terjadi, mungkin Anda tidak pernah mengirim apapun? Forum diskusi umum menerapkan kebijakan untuk menghapus user yang tidak pernah mengirim apapun untuk mengurangi besar database. Cobalah mendaftarkan diri Anda lagi dan terlibatlah dalam diskusi.");


$faq[] = array("--","Preferensi dan Setting User");
$faq[] = array("Bagaimana mengubah setting saya?", "Semua setting Anda (jika Anda terdaftar) disimpan dalam database. Untuk mengubah setting, klik link <u>Profil</u> (umumnya - tapi tidak selalu - terletak di atas tiap halaman). Halaman ini dapat digunakan untuk mengubah semua setting Anda.");
$faq[] = array("Tampilan waktu tidak benar!", "Catatan waktu hampir pasti benar. Walaupun demikian, waktu yang ditampilkan mungkin merupakan waktu pada zona waktu yang lain daripada zona waktu Anda. Jika hal ini terjadi, Anda harus mengubah setting profil Anda sesuai lokasi Anda, misalnya London, Paris, New York, Sydney, dll. Harap diperhatikan bahwa pengubahan zona waktu, seperti seting lainnya, hanya dapat dilakukan oleh user yang terdaftar. Jadi, jika Anda belum mendaftar, saat ini saat yang tepat untuk melakukannya!");
$faq[] = array("Saya mengubah zona waktu, tapi waktu yang ditampilkan tetap salah!", "Jika Anda yakin telah mengatur zona waktu dengan benar tapi tampilan waktu masih salah, kemungkinan terbesar jawabannya adalah masalah <em>daylight savings time</em> (atau <em>summer time</em> menurut istilah UK atau daerah lain). Forum diskusi tidak dirancang untuk menangani masalah perubahan antara waktu standar dan daylight, sehingga, sewaktu musim panas, mungkin timbul satu jam perbedaan waktu antara waktu server dengan waktu lokal sebenarnya.");
$faq[] = array("Bahasa saya tidak ada dalam daftar!", "Alasan utama bisa karena Admin tidak menginstall bahasa Anda atau orang lain belum menerjemahkan forum ini ke dalam bahasa Anda. Coba tanyakan pada Admin untuk menginstall paket bahasa yang Anda butuhkan. Jika belum tersedia, silakan buat translasi baru sendiri. Informasi selengkapnya dapat dibaca di website phpBB Group (gunakan link pada bagian bawah halaman).");
$faq[] = array("Bagaimana menampilkan gambar di bawah username saya?", "Terdapat dua gambar di bawah username pada tampilan posting. Gambar pertama berhubungan dengan peringkat Anda, biasanya berbentuk bintang atau blok yang menunjukkan berapa banyak posting yang telah Anda buat atau status Anda di forum. Dibawahnya terdapat gambar yang lebih besar yang disebut Avatar, yang umumnya unik atau personal untuk tiap user. Admin berhak menentukan apakah Avatar diijinkan dan mereka memutuskan bagaimana cara penyediaan Avatar. Jika Anda tidak dapat menggunakan Avatar, hal tersebut adalah keputusan Admin. Anda harus menanyakan alasan mereka tidak menyediakan fitur ini (kami yakin pasti alasannya masuk akal!)");
$faq[] = array("Bagaimana saya mengubah rangking saya?", "Umumnya, Anda tidak dapat mengubah kata-kata pada peringkat (tampil di bawah nama Anda pada topik dan pada profil Anda, tergantung style yang digunakan). Kebanyakan forum menggunakan peringkat untuk menunjukkan jumlah posting yang telah Anda buat dan mengenali user tertentu, misalnya moderator dan administrator mungkin memiliki rangking istimewa. Harap jangan merugikan forum dengan mengirimkan hal-hal yang tidak perlu hanya untuk menaikkan rangking Anda. Moderator dan Admin dapat dengan mudah menurunkan nilai posting Anda.");
$faq[] = array("Waktu saya mengklik alamat email seseorang, sistem mengharuskan saya login?", "Maaf, hanya user terdaftar yang dapat mengirimkan email kepada orang lain melalui email form yang disediakan (jika Admin telah mengaktifkan fitur ini). Hal ini untuk mencegak penggunaan sembarangan sistem email oleh user anonim.");


$faq[] = array("--","Masalah Pengiriman Pesan");
$faq[] = array("Bagaimana cara mengirim topik pada forum?", "Mudah saja. Klik tombol yang relevan baik pada halaman forum maupun topik. Anda mungkin harus mendaftar sebelum dapat mengirimkan message. Fasilitas yang disediakan untuk Anda ditampilkan pada bagian bawah halaman forum atau topik (bagian <em>Anda dapat mengirim topik baru, Anda dapat mengirimkan pendapat, dll</em>).");
$faq[] = array("Bagaimana mengubah atau menghapus suatu pesan?", "Kecuali Anda adalah Admin atau moderator forum, Anda hanya dapat mengubah atau menghapus posting Anda sendiri. Anda dapat mengubah suatu posting (kadang hanya untuk waktu yang terbatas setelah pembuatan posting) dengan mengklik tombol <em>Edit</em> untuk posting yang bersangkutan. Jika seseorang telah menjawab posting Anda, Anda akan melihat bagian kecil teks di bawah posting yang menunjukkan berapa kali Anda telah mengubah topik tersebut. Hal ini hanya terjadi jika tidak seorang pun belum menjawab posting Anda, atau jika moderator atau Admin mengubah posting tersebut (mereka harus memberikan pesan mengenai apa yang diubah dan alasan pengubahannya). Harap dicatat bahwa user normal tidak dapat menghapus suatu posting begitu ada yang menjawab posting tersebut.");
$faq[] = array("Bagaimana saya menambahkan Signature pada pesan?", "Untuk menambahkan signatur pada suatu pesan, Anda harus membuat dulu Signatur Anda melalui halaman profil. Begitu dibuat, Anda dapat mencek pilihan <em>Sertakan Signatur</em> pada form posting untuk menambah signatur Anda. Anda juga dapat menambahkan Signatur pada semua posting Anda dengan mencek pilihan yang sama pada halaman profil (Anda masih dapat mencegah penambahan signatur pada tiap posting dengan menghilangkan cek Sertakan Signatur pada form posting)");
$faq[] = array("Bagaimana saya membuat polling?", "Membuat suatu polling mudah dilakukan. Ketika Anda mengirim suatu topik baru (atau mengubah posting pertama suatu topik, jika Anda memiliki hak untuk itu), Anda akan melihat form <em>Buat Polling</em> dibawah form posting utama (jika Anda tidak dapat melihat ini, maka kemungkinan Anda tidak memiliki hak untuk membuat polling). Anda harus memasukkan judul polling, dan paling tidak dua pilihan jawaban (untuk membuat pilihan jawaban, masukkan pertanyaan polling dan klik tombol <em>Tambah Pilihan</em>. Anda juga dapat mengatur waktu untuk polling dimana 0 melambangkan waktu tak terbatas. Batasan jumlah pilihan yang dapat Anda buat diatur oleh administrator.");
$faq[] = array("Bagaimana saya mengubah atau menghapus polling?", "Sebagaimana halnya dengan posting pesan, polling juga hanya dapat diubah oleh pembuatnya, moderator, atau admin. Untuk mengubah suatu polling, klik pesan pertama pada topik (polling selalu berkaitan dengan posting ini). Jika belum ada pemilih untuk polling ini, makan orang-orang yang disebut diatas dapat menghapus polling atau mengubah pilihan polling. Jika telah ada pemilih untuk polling tersebut, hanya moderator atau administrator yang dapat mengubah atau menghapus polling. Hal ini untuk mencegah orang melakukan manipulasi terhadap polling");
$faq[] = array("Mengapa saya tak dapat mengakses suatu forum?", "Beberapa forum dibataasi untuk user atau group tertentu. Untuk melihat, membaca, mengirim, dll, Anda mungkin harus memiliki otorisasi khusus, hanya moderator dan admin yang dapat memberikan hak akses ini. Anda harus mengontak orang-orang tersebut.");
$faq[] = array("Mengapa saya tak dapat memberikan suara pada polling?", "Hanya pengguna terdaftar yang dapat memberikan suara pada polling (untuk mencegah penipuan hasil). Jika Anda telah terdaftar dan masih tidak dapat juga memberikan suara Anda, maka kemungkinan Anda tidak memiliki hak akses untuk melakukan itu.");


$faq[] = array("--","Pengaturan Format dan Tipe Topik");
$faq[] = array("Apa itu BBCode?", "BBCode adalah implementasi khusus dari HTML. Boleh tidaknya penggunaan BBCode dalam posting Anda di forum ditentukan oleh Administrator (selain itu, Anda juga dapat mematikan BBCode untuk setiap posting Anda). BBCode mirip dengan HTML, tag diapit oleh kurung siku [ dan ], bukan &lt; dan &gt; serta memberikan kontrol yang lebih besar untuk apa dan bagaimana tampilan yang diinginkan. Untuk informasi lebih lengkap mengenai BBCode, lihat petunjuk yang dapat Anda akses dari halaman pengiriman pesan.");
$faq[] = array("Dapatkah saya menggunakan HTML?", "Tergantung pada administrator. Mereka memiliki kontrol penuh untuk hal tersebut. Jika Anda diijinkan untuk menggunakan HTML, mungkin hanya beberapa tag tertentu yang diperbolehkan. Hal ini adalah fitur <em>keamanan</em> untuk mencegah orang menyalahgunakan forum dengan menggunakan tag yang dapat merusak tampilan atau berbagai masalah lain. Jika HTML diijinkan, Anda dapat menonaktifkan pilihan ini per tiap kiriman pesan.");
$faq[] = array("Apa itu Smileys?", "Smiley, atau Emoticon adalah gambar kecil yang digunakan untuk menunjukkan perasaan dalam bentuk kode pendek, misalnya :) berarti senang, :( berarti sedih. Daftar lengkap emoticon dapat dilihat pada halaman pengiriman pesan. Usahakan tidak terlalu sering menggunakan smiley. Smiley dapat menyebabkan pesan sulit dibaca dan moderator dapat memutuskan untuk mengubah atau bahkan menghapus pesan tersebut.");
$faq[] = array("Dapatkan saya mengirim gambar?", "Gambar dapat ditampilkan pada pesan Anda. Meskipun demikian, tidak tersedia fasilitas untuk mengirim gambar langsung ke forum. Karenanya, Anda harus menggunakan gambar yang tersedia pada web server yang dapat diakses publik, misalnya http://www.some-unknown-place.net/my-picture.gif. Anda tidak dapat menggunakan gambar yang disimpan pada komputer pribadi Anda (kecuali jika komputer tersebut adalah server yang dapat diakses publik) atau gambar yang tersimpan di belakang suatu mekanisme otentikasi, misalnya mailbox hotmail atau yahoo, situs yang memiliki proteksi password, dll. Untuk menampilkan gambar, Anda dapat menggunakan BBCode [img] atau HTML yang sesuai (jika diijinkan).");
$faq[] = array("Apa yang dimaksud Pengumuman?", "Pengumumuman sering mengandung informasi penting yang harus Anda baca sesegera mungkin. Pengumuman ditampilkan pada bagian atas setiap halaman pada forum dimana pengumuman ini dikirim. Bisa tidaknya Anda mengirimkan pengumuman tergantung pada hak akses yang diatur oleh administrator.");
$faq[] = array("Apa yang dimaksud Topik Tetap?", "Topik Tetap tampil di bawah setiap pengumuman pada tampilan forum dan hanya pada halaman pertama. Seringkali topik ini cukup penting sehingga harus dibaca secepatnya. Seperti juga pengumuman, administrator menentukan hak akses yang diperlukan untuk mengirim topik tetap pada tiap forum.");
$faq[] = array("Apa yang dimaksud Topik Terkunci?", "Topik dikunci oleh moderator atau administrator. Anda tidak dapat menjawab pesan pada topik terkunci dan semua polling yang berhubungan otomatis berakhir. Topik dapat dikunci karena berbagai hal.");


$faq[] = array("--","Level dan Group User");
$faq[] = array("Apa yang dimaksud Administrator?", "Administrator adalah orang yang memiliki tingkat pengaturan tertinggi pada forum. Orang-orang ini mengatur semua aspek operasi forum yang mencakup pengaturan hak akses, mem-banned user, membuat usergroup atau moderator, dll. Mereka juga memiliki hak sebagai moderator pada semua forum.");
$faq[] = array("Apa yang dimaksud Moderator?", "Moderator adalah individu atau grup individu yang tugasnya mengawasi jalannya forum sehari-hari. Mereka memiliki hak untuk mengubah atau menghapus pesan, serta mengunci, membuka, memindahkan, menghapus, dan memecah topik pada forum yang mereka moderasikan. Umumnya moderator bertugas mencegah OOT atau mengirim bahan yang kasar atau tidak patut.");
$faq[] = array("Apa yang dimaksud Usergroups?", "Usergroup adalah cara pengelompokkan user oleh administrator. Tiap user dapat dikelompokkan pada berbagai grup (berbeda dengan kebanyakan sistem forum lainnya) dan tiap group dapat memiliki akses individu. Hal ini membuat administrator mudah untuk mengatur beberapa orang menjadi moderator suatu forum, atau memberikan mereka akses ke forum pribadi, dll.");
$faq[] = array("Bagaimana cara bergabung dengan Usergroup?", "Untuk bergabung dengan usergroup, klik link Group pada bagian atas halaman (tergantung pada desain template), Anda akan dapat melihat seluruh usergroup. Tidak semua group bersifat <em>terbuka</em>. Beberapa bersifat tertutup atau bahkan tersembunyi. Jika suatu group bersifat terbuka, makan Anda dapat mengirim permintaan untuk bergabung dengan menekan tombol yang tersedia. Moderator usergroup harus menyetujui permintaan Anda, mereka mungkin bertanya mengapa Anda ingin bergabung pada group tersebut. Harap tidak mengganggu moderator group jika permintaan Anda ditolak, mereka pasti memiliki alasan untuk itu.");
$faq[] = array("Bagaimana menjadi Moderator Usergroup?", "Usergroup awalnya dibuat oleh admin, mereka juga yang biasanya menunjuk moderator. Jika Anda tertarik untuk membuat usergroup, maka kontak pertama Anda haruslah admin. Coba mengirim pesan pribadi pada mereka.");


$faq[] = array("--","Pesan Pribadi");
$faq[] = array("Saya tak dapat mengirim Pesan Pribadi!", "Ada tiga alasan untuk ini; Anda tidak terdaftar atau belum login, administrator tidak mengijinkan pesan pribadi untuk seluruh forum atau administrator telah melarang Anda mengirim pesan pribadi. Jika masalah terakhir yang terjadi, Anda harus bertanya pada administrator mengapa demikian.");
$faq[] = array("Saya terus menerima Pesan Pribadi yang tak diinginkan!", "Nantinya, kami akan menambahkan daftar penolakan pada sistem pesan pribadi. Untuk saat ini, untuk mencegah Anda selalu menerima pesan pribadi yang tak diinginkan dari seseorang, beritahu admin. Mereka mampu menghilangkan sama sekali kemampuan seorang user mengirimkan pesan pribadi.");
$faq[] = array("Saya menerima email spam dari seseorang di forum ini!", "Maaf atas hal itu. Fitur email pada forum ini menyediakan pengamanan untuk melacak user yang mengirim posting tersebut. Anda harus mengirim email pada administrator dengan salinan lengkap email yang Anda kirim, penting untuk Anda menyertakan header email (informasi lengkap mengenai user yang mengirim email). Admin dapat melakukan tindakan terhadap hal ini.");

//
// These entries should remain in all languages and for all modifications
//
$faq[] = array("--","Seputar phpBB 2");
$faq[] = array("Siapa yang membuat Forum Diskusi ini?", "Program ini (dalam bentuk yang belum diubah) diproduksi, dirilis, dan merupakan hak cipta dari <a href=\"http://www.phpbb.com/\" target=\"_blank\">phpBB Group</a>. Program disediakan dalam bentuk lisensi GNU General Public Licence dan dapat bebas didistribusikan. Lihat link untuk detilnya.");
$faq[] = array("Mengapa fitur X tidak tersedia?", "Program ini dibuat dan dilisensikan oleh phpBB Group. Jika Anda berpikir ada fitur yang pantas ditambahkan, harap kunjungin situs phpbb.com dan lihat komentar dari phpBB Group. Harap jangan mengirim permintaan fitur pada forum di phpbb.com. phpbb Group menggunakan sourceforge untuk menangani penugasan fitur baru. Baca isi forum dan lihat apakah kami sudah mempertimbangkan fitur tersebut.");
$faq[] = array("Siapa yang dapat saya kontak mengenai masalah spam yang berhubungan dengan forum ini?", "Anda harus mengontak administrator forum. Jika Anda tidak dapat menemukan siapa adminnya, Anda harus pertama-tama mengontak moderator dan menanyakan kepada siapa Anda harus mengontak. Jika masih juga tidak mendapat balasan, Anda harus mengontak pemilik domain (gunakan whois), atau jika forum tersedia pada layanan gratis (misalnya yahoo, free.fr, f2s.com, dll), kontak manajemen atau <em>abuse departement</em> mereka. Harap dicatat bahwa phpBB Group tidak memiliki kontrol dan tidak dapat dianggap bertanggung jawab atas bagaimana, dimana, atau oleh siapa forum digunakan. Sama sekali tak beralasan untuk mengontak phpBB Group berhubungan dengan masalah legal (<em>cease and desist, liable, defamatory, comment, dll</em>) yang tidak terkait langsung dengan situs phpbb.com atau program phpBB. Jika Anda mengirim email ke phpBB Group mengenai penggunaan pihak ketiga atas program ini, maka Anda akan mendapatkan jawaban yang tegas atau tak ada jawaban sama sekali.");

//
// This ends the FAQ entries
//

?>