<?php
/***************************************************************************
 *                         lang_faq.php [portuguese_br]
 *                            -------------------
 *   begin                : Wednesday Oct 3, 2001
 *   copyright            : (C) 2001 The phpBB Group
 *   email                : support@phpbb.com
 *
 *   $Id$
 *
 *
 ***************************************************************************/

 /****************************************************************************
 * Traduzido por:
 * JuniorZ rs_junior@hotmail.com || http://www.phpbrasil.rg3.net
 ****************************************************************************/

/***************************************************************************
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 ***************************************************************************/

$faq[] = array("--","Questões de <i>Entrar</i> e <i>Registar</i>");
$faq[] = array("Porque é que não consigo <i>Entrar</i> nos fóruns?", "Registou-se? Você deve <u>Registar</u>-se de forma a poder <u>Entrar</u>. Foi expulso dos fóruns? Surgirá uma mensagem se tal aconteceu. Caso haja uma expulsão deve contactar o 'webmaster' ou o Administrador do fórum e perguntar porquê caso não saiba a razão. Caso esteja registado e não se encontre expulso e mesmo assim não consiga <u>Entrar</u>, verifique novamente se o seu <u>Nome de Utilizador</u> e <u>Senha</u> são os correctos. Normalmente é esse o problema. Caso não saiba mesmo o que se possa passar e não seja nenhuma das razões acima descritas contacte o Administrador do fórum porque poderá acontecer haver alguma configuração errada no sistema.");
$faq[] = array("Porque é que tenho que me <i>Registar</i> de todo?", "Poderá não ser necessário. Está inteiramente ao critério do Administrador dos fóruns se é necessário o registo de forma aos utilizadores afixarem as suas mensagens. Contudo, o registo dá-lhe acesso a funções adicionais e possivelmente fóruns que não estão disponíveis a visitantes que se apresentam no anonimato. Alguns exemplos são o uso e definição de imagens <u>Avatar</u> , uso de <u><b>M</b>ensagens <b>P</b>rivadas</u>, enviar e receber <u>email</u> entre utilizadores, subscrição de <u>Grupos de Utilizadores</u>, etc. São necessários apenas alguns segundos para se fazer o registo como tal é recomendável que o faça.");
$faq[] = array("Porque é que me encontro a ligar automaticamente ao fórum?", "Se não assinalar <u>Ligar-me automaticamente por cada visita</u> antes de carregar em <u>Entrar</u>, o sistema não o irá ligar da próxima vez que visite o fórum. Isto evita o uso abusivo da sua conta por outra pessoa. Para se manter ligado e não necessitar de escrever o seu <u>Nome de Utilizador</u> e <u>Senha</u> assinale essa caixa quando se ligar. Tal não é no entanto recomendável caso aceda aos fóruns num computador partilhado por outros utilizadores, ou seja, bibliotecas, cefé internet ou cyber café, departamento em universidade, etc.");
$faq[] = array("Como posso evitar que o meu <i>Nome</i> de <i>Utilizador</i> apareça na lista de <i>Ligados</i>?", "No seu <u>Perfil</u> há uma opção <u>Esconder o meu indicador de Ligado</u>. Se assinalar <u>Sim</u> apenas você e o Administrador poderão ver que se encontra ligado. Passará a ser tomado pelo sistema do phpBB 2 como um <u>Utilizador Invisível</u>.");
$faq[] = array("Perdi a minha <i>Senha</i>!", "Não entre em pânico! Apesar da sua <u>Senha</u> não poder ser recuperada pela Administração do fórum pode no entanto ser feito como que se nunca a tivesse registado, ou seja, como que se estivesse a ligar pela primeira vez. Para fazer isto premir <u>Entrar</u> e de seguida em <u>Esqueci-me da Senha</u>, e se seguir as instruções voltará a ligar-se em momentos");
$faq[] = array("Registei-me mas não consigo <i>Entrar</i>!", "Primeiro verifique se está a escrever o <u>Nome de Utilizador</u> e <u>Senha</u> correctos. Caso se encontrem bem então uma entre duas coisas poderão estar a acontecer - se o a função de COPPA se encontra activa nos fóruns e você tem menos de 13 anos de idade (e pelo facto carregou no respectivo atalho durante o registo), terá que seguir as instruções que receba. Se isto não é o caso, será que o seu registo necessite ser activado? Alguns administradores pretendem que o registo dos seus novos utilizadores seja activado através de um email, antes que possa efectivamente <u>Entrar</u> nos fóruns. Caso isso aconteça, quando se registou foi informado se a activação seria ou não necessária. Se recebeu um email então siga as suas instruções. Se não recebeu o email, será que o endereço de email é válido? Uma das razões para a activação ser feita é para reduzir o número abusos do sistema por utilizadores <i>disfarçados</i> ou passando pelo anonimato. Se tem a certeza que o endereço de email que forneceu é válido e correcto tente então contactar o Administrador do fórum.");
$faq[] = array("Registei-me no passado mas não consigo mais <i>Entrar</i>?!", "As razóes mais prováveis são; escreveu um <u>Nome de Utilizador</u> ou <u>Senha</u> incorrectos (verifique o email que lhe terá sido enviado quando se registou inicialmente), ou o administrador poderá ter removido o seu registo por algum motivo. É comum administradores removerem registos de utilizadores que nunca colocaram mensagens, de forma a reduzir o tamanho da base de dados. Tente registar-se novamente e envolver-se nos assuntos dos fóruns.");


$faq[] = array("--","Preferências e Configuração de Utilizadores");
$faq[] = array("Como mudo a minha configuração?", "Toda a sua configuração (após o <u>Registar</u>-se) é guardada na base de dados. Para a alterar prima em <u>Perfil</u> (normalmente no topo das páginas, dependendo do estilo de fóruns em uso). A partir daí pode alterar a sua configuração.");
$faq[] = array("Os tempos e datas não são os correctos!", "Os tempos decerto que estão correctos, contudo pode acontecer você estar a ver horas de um fuso horário diferente de onde você normalmente se encontra ou inicialmente programou. Se é esse o caso deve mudar no seu <u>Perfil</u> a opção para o <u>Fuso Horário</u> de forma a abranger a sua área, ou seja, Londres, Paris, Nova Iorque, Sidney, ou onde se encontre. De notar que a mudança do fuso horário bem como a maior parte das opções de perfil só é permitida a utilizadores registados. Se ainda não é o seu caso chegou uma boa altura e razão para o fazer!");
$faq[] = array("Mudei o <i>Fuso Horário</i> mas a hora continua errada!", "Se tem a certeza que o <u>Fuso Horário</u> que escolheu é o correcto mas a hora não é a real, é possível que seja devido a mudança horária para ajustamento de hora diurna e nocturna (ou hora de Verão/Inverno). O phpBB não se encontra desenhado para efectuar essas mudanças automaticamente, como tal devem ser ajustadas manualmente pelos utilizadores.");
$faq[] = array("A língua da minha nacionalidade não se encontra na lista!", "A razão mais provável é o Administrador não ter instalado essa língua ou o phpBB ainda não ter sido traduzido para a mesma. Peça ao Administrador que instale esse 'pacote de língua' e, caso não exista, você poderá criar uma nova tradução. Para mais informação consultar a página oficial do <b>Grupo phpBB</b> (seguir o atalho ao fundo destas páginas)");
$faq[] = array("Como posso mostrar uma imagem por debaixo do meu <i>Nome de Utilizador</i>?", "Deve haver duas imagens na parte inferior de cada Nome de Utilizador quando se vêm as mensagens - a primeira representa o escalão em que o utilizador se encontra, normalmente em forma de blocos ou estrelas indicando a quantidade de mensagens que o utilizador tenha e respectiva designação no escalão, ou o estatuto desse utilizador nos fóruns. Abaixo dessas poderá existir uma imagem maior conhecida como Avatar, que é normalmente única ou pertencente a cada utilizador. Está ao cargo do Administrador dos fóruns permitir ou não a afixação de <u>Avatars</u> bem como a forma em como os utilizadores os possam afixar. Se você não consegue colocar o seu, então possivelmente é decisão do Administrador dos fóruns tendo configurado o sistema para não o permitir. Pergunte-lhe a razão (temos a certeza que existe uma boa justificação!)");
$faq[] = array("Como posso mudar o meu <i>escalão</i>?", "De uma forma geral o utilizador normal não pode alterar directamente o escalão (os escalões aparecem por baixo do Nome de Utilizador em tópicos e no 'Perfil' dependendo no estilo de fórum em uso). A mair parte dos escalões em fóruns indicam o número de mensagens que você tenha colocado ou indicam certo tipo de utilizadores, ou seja, moderadores e administradores poderão ter um escalão especial. Por favor não abuse dos fóruns colocando mensagens desnecessárias apenas para aumentar o seu nível de escalão pois o Moderador ou Administrador poderão tomar alguma atitude contra, caso verifiquem que haja abuso.");
$faq[] = array("Quando carrego no atalho de <i>email</i> de um utilizador aparece-me uma mensagem para <i>Entrar</i>!", "Lamentamos mas apenas utilizadores registados poderão enviar <u>email</u> a pessoas através do formulário exclusivo do fórum (caso o administrador tenha activado essa função). Isso é para evitar o uso malicioso do sistema de email por utilizadores anónimos.");


$faq[] = array("--","Questões na colocação de mensagens");
$faq[] = array("Como posso colocar uma mensagem num fórum?", "Fácil, prima no botão respectivo tanto no fórum como no tópico onde se encontre(dependendo do estilo de fórum em uso, normalmente os botões têm a designação de <u>Nova Mensagem</u>, <u>Novo Tópico</u> ou <u>Responder</u>). Talvez seja necessário o seu registo nos fóruns para poder afixar mensagens. Hexiste uma lista de acções que lhe são permitidas, haja registo ou não, na parte inferior do lado direito da página de cada fórum (<u>Pode colocar mensagens novas, Pode votar, etc.</u>)");
$faq[] = array("Como posso <i>editar</i> ou <i>remover</i> uma mensagem?", "A menos que seja um administrador de fórum você apenas pode <u>editar</u> ou <u>remover</u> as suas próprias mensagens. Pode editar uma mensagem (por vezes apenas por um período limitado após ser colocada) carregando no botão <u>editar</u> na parte superior dessa mensagem (dependendo do estilo de fórum em uso).  Caso alguém tenha já respondido a essa mensagem você encontrará um pequeno texto ao fundo, mencionando que foi editada e eventualmente quantas vezes. Isto não aparece apenas caso essa mensagem não tenha ainda respostas. Também não aparecerá caso a alteração seja efectuada por algum Administrador ou Moderador (possivelmente eles deixarão uma mensagem dizendo o que foi alterado e o motivo). De notar que utilizadores normais não podem remover uma mensagem após alguém já ter colocado uma resposta.");
$faq[] = array("Como adiciono uma <i>assinatura</i> a uma mensagem?", "Para adicionar uma assinatura a uma mensagem deverá primeiro criar uma no seu <u>Perfil</u> no local respectivo. Uma vez criada poderá instruir o fórum, também em <u>Perfil</u>, pata <u>Anexar sempre a minha assinatura</u> às mensagens ou colocá-la apenas quando assim o pretenda, assinalando <u>Adicionar Assinatura</u> na lista de opções por baixo da caixa de escrita de cada mensagem.");
$faq[] = array("Como posso <i>adicionar uma votação</i>?", "Criar uma votação é fácil. Quando afixa um tópico novo (ou edita a primeira mensagem de um tópico, caso tenha permissão para tal) encontra na parte inferior à caixa principal da mensagem um painel com o título <u>Adicionar Votação</u> (se você não vê isto é porque provavelmente não possui permissão para criar votações ou o tópico não é de sua autoria). Deverá escrever um título para a votação no local apropriado e de seguida colocar pelo menos duas <u>Opções de escolha</u> (para adicionar uma opção escreva o que pretende e carregue no botão <u>Adicionar opção de escolha para a votação</u>. Deverá também estipular um limite tempo para a votação, sendo 0 ilimitado. Poderá acontecer haver um limite no número de opções de escolha, estando esse limite ao critério e configuração do Administrador dos fóruns");
$faq[] = array("Como posso <i>editar</i> ou <i>remover</i> uma <i>votação</i>?", "Da mesma forma que as mensagens as votações apenas poderão ser editadas pelo seu autor, um moderador ou o Administrador dos fóruns. Para editar uma votação carregue na primeira mensagem do tópico (esta mensagem é a que tem a votação associada ao tópico). Caso ninguém tenha submetido voto os seus autores podem remover a votação ou editar as suas opções de escolha. Contudo, se os utilizadpres já colocaram votos apenas moderadores e administradores podem editar ou remover essa votação. Isto é para evitar com que sejam alteradas as opções de escolha em votações em curso");
$faq[] = array("Porque não consigo entrar num fórum?", "O acesso a alguns fóruns poderá estar limitado apenas a determinados utilizadores ou grupos. Para verificar, ler, colocar mensagens, etc., você deve necessitar autorização especial. Apenas o moderador desse fórum e um Administrador podem permitir esse acesso. Contacte-os caso ache necessário.");
$faq[] = array("Porque não posso votar?", "Apenas utilizadores registados podem submeter os seus votos (para impedir duplicação nos resultados). Caso você possua registo mas mesmo assim não consegue votar então possivelmente não lhe foi atribuida permissão para tal.");


$faq[] = array("--","Formatos e tipos de Tópicos");
$faq[] = array("O que é <i>BBCode</i>?", "BBCode é uma implementação especial de HTML. Se possa ou não usar BBCode nos fóruns está ao critério do Administrador. (caso lhe seja permitido pode controlar o seu uso em <u>Desactivar BBCode nesta mensagem</u>). O BBCode por si mesmo é similar em estilo ao HTML, as etiquetas são introduzidas entre perêntesis rectos [and] em vez de &lt; and &gt; e proporcionam um maior controle do que e como algo é apresentado. Para mais informações acerca de BBCode veja o guia respectivo, acessível na página das mensagens.");
$faq[] = array("Posso usar <i>HTML</i>?", "Depende se o Administrador o permita, ele tem o controle completo sobre isso. Se lhe é permitodo a si usar HTML provavelmente apenas alguns códigos lhe são acessíveis. Isto é uma medida de <i>segurança</i> para evitar que pessoas abusem do fórum usando códigos que possam destruir o seu formato ou causar outros problemas. Caso o HTML esteja activo você pode desactivá-lo em cada mensagem assinalando <u>Desactivar HTML nesta mensagem</u>.");
$faq[] = array("O que são <i>Smileys</i>?", "Smileys, ou Emoticons são pequenas representações gráficas que podem ser usadas para expressar algum sentimento usando poucos caracteres, ou seja, :) quer dizer feliz, :( quer dizer triste. Uma lista completa de <u>Emoções</u> pode ser vista no formulário junto à caixa de cada mensagem. Tente evitar o uso excessivo dos smileys já que podem tornar uma mensagem ilegível podendo o Administrador ou um moderador remove-los ou apagar a mensagem no seu todo");
$faq[] = array("Posso <i>inserir imagens</i>?", "As imagens podem na verdade aparecer entre as suas mensagens. Contudo, não há presentemente alguma forma de carregar imagens directamente  ao phpBB. Como tal você terá que ligar a imagem armazenada num servidor publicamente acessível, ou seja, http://www.algum-lugar-seu.conhecido.net/minha-imagem.gif. Não pode ligar ao fórum imagens guardadas no seu próprio PC (a menos que esse possua um servider publicamente acessível) nem imagens armazenadas sob mecanismos que requeiram autenticação, como por exemplo caixas de correio electrónico de Hotmail ou Yahoo, páginas protegidas por senha, etc. Para mostrar a imagem pode usar tanto o BBCode [img] como o código apropriado de HTML (se activo).");
$faq[] = array("O que são <i>Anúncios</i>?", "Os Anúncios contém normalmente informação importante e você deve lê-los logo que eles surjam. Os Anúncios sao automaticamente colocados no topo de cada página do fórum em que são afixados. Se você possa ou não fazer uso dessa função depende das permissões que lhe foram dadas, configuradas pelo Administrador.");
$faq[] = array("O que é um tópico <i>Inamovível</i>?", "Tópicos Inamovíveis aparecem por baixo de anúncios nos fóruns e apenas na primeira página. São vulgarmente importantes e como tal devem ser lidos logo que possível. Da mesma forma que os Anúncios está ao critério do Adminsitrador dos fóruns determinar que permissões são necessárias para afixar mensagens Inamovíveis em cada fórum.");
$faq[] = array("O que é um tópico <i>Bloqueado</i>?", "Os tópicos Bloqueados são dessa forma colocados por um moderador ou o Admministrador dos fóruns. Quando um tópico se encontra bloqueado não é mais permitido aos utilizadorescolocar respostas e qualquer eventual votação existente termina automaticamente. Os tópicos podem ser bloquados por várias razões.");


$faq[] = array("--","Níveis de utilizadores e Grupos");
$faq[] = array("O que são <i>Administradores</i>?", "Administradores são pessoas com o nível máximo de controle sobre todos os aspectos dos fóruns. Podem controlar toda a operação dos fóruns, incluindo criar, editar ou remover fóruns, determinar permissões, expulsar utilizadores, criar grupos de utilizadores ou moderadores, etc. Eles possuem igualmente todos os poderes de moderador em todos os fóruns existentes.");
$faq[] = array("O que são <i>Moderadores</i>?", "Moderadores são utilizadores (ou grupos de utilizadores) cujo trabalho é supervisionar diariamente o funcionamento dos fóruns que lhes estejam designados. Eles tem o poder de editar ou remover mensagens, bloquear, desbloquear, mover, remover e subdividir tópicos nos fóruns onde são moderadores. Geralmente os moderadores fiscalizam mensagens que possam ir <i>para além do assunto em discussão<i> ou o uso de material abusivo ou ofensivo.");
$faq[] = array("O que são <i>Grupos de Utilizadores</i>?", "<u>Grupos de Utilizadores</u> são uma forma dos administradores dos fóruns agrupar utilizadores. Cada utilizador pode pertencer a vários grupos (isto difere da maioria dos outros tipos de Quadros de Mensagens) e a cada grupo podem ser dados direitos de acesso individuais. Isto torna mais fácil aos administradores destinar vários utilizadores como moderadores de um determinado fórum ou dar-lhes acesso a um fórum privado, etc.");
$faq[] = array("Como me associo a um <i>Grupo de Utilizadores</i>?", "Para se associar a um Grupo de Utilizadores carregue no atalho de Grupos no topo da página (dependendo do desenho de cada modelo do phpBB no fórum), podendo então ver todos os Grupos. Nem todos os Grupos possuem um <i>acesso aberto</i>, alguns são fechados e alguns poderão inclusivé encontrar-se invisíveis. Se o Grupo se encontra aberto você poderá então solicitar que seja membro carregando no botão apropriado. O moderador do Grupo de Utilizadores necessita aprovar o seu pedido, podendo perguntar-lhe a razão do mesmo. Por favor não insistir perante um Moderador de Grupo caso o seu pedido seja recusado. Eles têm as usas razões.");
$faq[] = array("Como posso vir a ser um <i>Moderador</i> de Grupo?", "Os Grupos de Utilizadores são iniialmente criados pelo Administrador dos fóruns o qual também encarrega alguém de ser Moderador. Se está interessado em criar um Grupo de Utilizadores o seu primeiro ponto de contacto será portanto o Administrador dos Fóruns, ao qual deverá contactar com uma <b>M</b>ensagem <b>P</b>rivada circunstanciada.");


$faq[] = array("--","<b>M</b>ensagens <b>P</b>rivadas");
$faq[] = array("Não consigo enviar <i><b>M</b>ensagens <b>P</b>rivadas<i>!", "Há três razões para que tal possa acontecer; você não está registado nos fóruns e/ou não se encontra ligado, o Adminstrador terá desligado a possibilidade da troca de Mensagens Privadas para todos os fóruns ou impede-o a si por algum motivo de enviar mensagens. Se é este o último caso você deverá perguntar ao Administrador qual a razão, caso não a saiba.");
$faq[] = array("Recebo <i><b>M</b>ensagens <b>P</b>rivadas</i> indesejáveis!", "No futuro iremos adicionar a possibilidade da existência de uma lista de utilizadores a ser ignorados ao sistema de Mensagens Privadas. Por agora, caso você continue a receber mensagens privadas não solicitadas a partir de alguém em particular, informe o Administrador, que poderá inviabilizar qualquer utilizador de enviar Mensagens privadas.");
$faq[] = array("Recebi de alguém neste fórum mensagens de <i>email</i> com assuntos irrelevantes ou abusivos!", "Embora o sistema de email neste fórum possua funções de segurança que tentam detectar utilizadores que enviem esse tipo de mensagens lamentamos que tal tenha acontecido. Você deve participar o acontecido ao Administrador dos fóruns com uma cópia completa do email recebido, sendo muito importante que inclua os cabeçalhos (nesses encontrm-se os detalhes do utilizador que enviou o email). O Administrador poderá então agir em conformidade.");

//
// These entries should remain in all languages and for all modifications
//
$faq[] = array("--","Questões em relação ao programa phpBB 2");
$faq[] = array("Quem escreveu o phpBB 2?", "Este software (na sua forma não modificada) é produzido, publicado e com direitos reservados por <a href=\"http://www.phpbb.com/\" target=\"_blank\">phpBB Group</a>. Está disponível sob a licensa 'GNU General Public Licence' e pode ser distribuido gratuitamente. Verificar o atalho para detalhes");
$faq[] = array("Porque não há a função X?", "Este software foi escrito e licenciado por phpBB Group. Se pensa que alguma função pode ser adicionada visite a nossa página oficial em phpbb.com e veja o que o Grupo phpBB pode dizer sobre o assunto. Por favor não coloque mensagens com pedido de funções no fórum em phpbb.com, o Grupo usa sourceforge para resolver situações relacionadas com funções novas. Por favor ler cuidadosamente esse fórum para ver se  alguma posição foi já por nós tomada para a função em questão, seguindo então o procedimento lá mencionado.");
$faq[] = array("A quem deva eu contactar acerca de questões abusivas e/ou legais relacionadas com este fórum?", "Você deverá contactar o Administrador dos fóruns. Se não conseguir saber quem seja contacte então um dos moderadores pergundando a quem deva expor o assunto. No caso de mesmo assim não obter resposta deve contactar o dono do domínio (faça um 'verifição de whois') ou, caso o fórum se encontre a funcionar num serviço grátis (por exemplo, yahoo, free.fr, f2s.com, etc.), a gerência ou o departamento de abusos desse serviço. Por favor notar que phpBB Group não possui absolutamente nenhum controle e não pode de qualquer maneira ser responsável sobre quando, onde e por quem este fórum é usado. Não há razão em contactar o phpBB Group em relação a qualquer questão legal (interrupção e desistência, de responsabilidade, comentário difamatório, etc.) não directamente relacionado com o 'site' phpbb.com ou o software discreto de phpBB por si próprio. Caso envie algum email a phpBB Group acerca do uso de terceiros deste software, poderá receber uma resposta concisa ou não receber resposta de todo.");

//
// This ends the FAQ entries
//

?>
