<?php
/***************************************************************************
 *                          lang_faq.php [Catalan]
 *                            -------------------
 *   begin                : Sun Jul 14, 2002
 *   copyright            : (C) 2001 The phpBB Group
 *   email                : support@phpbb.com
 *   
 *   $Id$
 *
 *
 ***************************************************************************/

/***************************************************************************
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 ***************************************************************************/
 
// 
// To add an entry to your FAQ simply add a line to this file in this format:
// $faq[] = array("question", "answer");
// If you want to separate a section enter $faq[] = array("--","Block heading goes here if wanted");
// Links will be created automatically
//
// DO NOT forget the ; at the end of the line.
// Do NOT put double quotes (") in your FAQ entries, if you absolutely must then escape them ie. \"something\"
//
// The FAQ items will appear on the FAQ page in the same order they are listed in this file
//

  
$faq[] = array("--","Inici de sessió (login) i registre");
$faq[] = array("Per què no puc iniciar la sessió?", "T'has registrat? Has de registrar-te per tal d'iniciar una sessió. Se t'ha exclòs del fòrum? (si es així t'apareixerà un missatge). Si és així envia un missatge al webmaster o l'administrador del fòrum per saber el perquè. Si t'has registrat i no has estat exclòs verifica que el teu nom d'usuari i contrasenya coincideixin, és el problema més comú. Si estàs segur de que les dades són correctes, envia un missatge a l'administrador del fòrum, és possible que el fòrum estigui mal configurat.");
$faq[] = array("Per què m'he de registrar?", "Potser no calgui, és decisió de l'administrador del fòrum si necessites registrar-te per publicar missatges. No obstant registrar-te et donarà accés a característiques addicionals no disponibles com a usuari invitat, com tenir el teu gràfic personalitzat (avatar), missatgeria privada, enviar correus a altres usuaris, subscripció a grups d'usuaris, etc. Només costa un moment, per tant és molt recomanable.");
$faq[] = array("Per què surto de la meva sessió automàticament?", "Si no actives la casella <i>Iniciar sessió automàticament</i> quan inicies la sessió al fòrum, només et mantindràs dins el sistema durant un temps predeterminat. Això evita l'ús inadequat del teu compte per algú més. Per mantenir-te dintre del sistema activa la casella quan iniciïs la sessió, això no és recomanable si accedeixes al fòrum des d'un ordinador compartit, e.g. biblioteca, cibercafè, universitat, etc.");
$faq[] = array("Com evito aparèixer a les llistes d'usuaris connectats?", "Al teu perfil trobaràs una opció <i>Ocultar el meu estat de connexió</i>, si actives aquesta opció només apareixeràs als administradors i a tu mateix. Se't comptarà com a usuari ocult.");
$faq[] = array("He perdut la meva contrasenya!", "Calma, tot i que no es pot recuperar la teva contrasenya, es pot canviar per una de nova. Per fer-ho ves a la pàgina d'inici de sessió i clica sobre <u>He oblidat la contrasenya</u>, segueix les instruccions i en poc temps podràs tornar a entrar.");
$faq[] = array("M'he registrat però no puc iniciar la sessió!", "Primer verifica que estàs introduint el nom d'usuari i contrasenya correctes. Si tot és correcte poden haver passat dues coses. Si el Sistema de Protecció Infantil (COPPA) està activat i quan t'has registrat has escollit l'opció <u>Sóc menor de 13 anys d'edat</u> llavors tindràs que seguir les instruccions que rebis. Si no és el cas, necessita el teu compte ser activat? Alguns fòrums requereixen que o bé tu o l'administrador activeu el nou compte abans de poder iniciar una sessió. Quan vas registrar-te t'hauria d'haver dit si era necessària l'activació. Si se't va enviar un email segueix-ne les instruccions, si no el vas rebre llavors assegura't que l'adreça que vas entrar sigui vàlida. Una raó per la qual s'utilitza l'activació és per reduir la possibilitat que usuaris malintencionats s'aprofitin del fòrum de forma anònima.");
$faq[] = array("Em vaig registrar fa temps però ara ja no puc iniciar la sessió!", "Les raons més probables són: el nom d'usuari o la contrasenya que has introduït són incorrectes (revisa l'email que vas rebre quan et vas registrar) o bé l'administrador ha esborrat el teu compte per alguna raó. Si aquest és el cas, potser no vas arribar a enviar cap missatge. Sol passar que els fòrums esborrin periòdicament els usuaris que no han publicat res per tal de reduir la mida de la base de dades. Prova de registrar-te de nou i participar en alguna discussió.");


$faq[] = array("--","Preferències d'usuari i configuracions");
$faq[] = array("Com canvio la meva configuració?", "Totes les teves configuracions (si estàs registrat) estan guardades en una base de dades. Per modificar-les clica l'enllaç <u>Perfil</u>, que es troba generalment a dalt de cada pàgina tot i que la ubicació pot canviar. Això et permetrà canviar la teva configuració.");
$faq[] = array("Les hores no són correctes!", "Les hores segurament són correctes però és possible que estiguis veient les hores corresponents a una altra zona horària. Si aquest és el cas, hauries de canviar la configuració del teu perfil per a la zona horària per que es correspongui amb la teva zona e.g. Londres, Paris, New York, Sydney, etc. Tingues present que per canviar la zona horària has d'estar registrat. Per tant, si no estàs registrat, ja és hora que ho facis.");
$faq[] = array("He canviat la zona horària però l'hora segueix estant malament", "Si estàs segur que has seleccionat la zona horària correcta i l'hora encara és diferent, el més probable és que es degui al canvi horari que es fa a l'estiu en alguns països. Els fòrums no estan dissenyats per manejar aquest canvi horari i per tant durant els mesos d'estiu pot diferir de l'hora local real en una hora.");
$faq[] = array("El meu idioma no està a la llista!", "El més probable és que o l'administrador no ha instal·lat el paquet del teu idioma o ningú n'ha fet la traducció del fòrum. Prova de demanar-li a l'administrador del fòrum si pot instal·lar el paquet d'idioma que necessites. Si no existeix llavors ets lliure de crear una nova traducció. Pots trobar més informació a la pàgina web de phpBB Group (clica l'enllaç al final de la pàgina).");
$faq[] = array("Com puc mostrar una imatge sota el meu nom d'usuari?", "Pot haver-hi dos tipus d'imatges sota el teu nom d'usuari en els missatges. La primera és una imatge associada al teu rang, generalment té forma d'estrelles o blocs que indiquen quants de missatges has publicat o el teu status als fòrums. A sota d'aquesta hi pot haver una imatge més gran coneguda com Avatar, que és un gràfic generalment únic i personal per a cada usuari. És decisió de l'administrador dels fòrums permetre l'ús d'avatars i escull la manera en què es poden obtenir. Si no pots utilitzar-los és perquè així ho ha decidit l'administrador, pots preguntar-li les raons per les quals ho ha fet (estem segur que seran bones!)");
$faq[] = array("Com canvio el meu rang?", "Generalment no pots canviar el teu rang directament. La majoria de fòrums utilitzen els rangs per indicar el nombre de missatges que has fet i per identificar determinats usuaris, e.g. moderadors i administradors poden tenir un rang especial. Si us plau no facis un ús abusiu del fòrum enviant missatges de forma innecessària només per incrementar el teu rang, si ho fas probablement el moderador o l'administrador simplement baixin el teu nombre de missatges publicats.");
$faq[] = array("Quan clico sobre l'enllaç d'email a usuaris em demana que iniciï una sessió", "Ho sentim però només els usuaris registrats poden enviar emails a través del formulari d'email que té implementat el fòrum (si l'administrador ha activat aquesta característica). Això es fa per evitar un ús inadequat del sistema d'email per part d'usuaris anònims.");


$faq[] = array("--","Publicació de missatges");
$faq[] = array("Com publico un tema en un fòrum?", "Fàcil, clica el botó adequat a la pantalla del fòrum o tema. És possible que necessitis registrar-te abans de poder publicar missatges, allò que se't permet està llistat al final de les pantalles dels fòrums i dels temes (la llista <i>Pots publicar nous temes, Pots votar a les enquestes, etc.</i>");
$faq[] = array("Com edito o esborro un missatge?", "Si no ets un administrador o moderador del fòrum només pots editar o esborrar els teus propis missatges. Pots editar un missatges (de vegades només durant un període de temps limitat després de ser fet) clicant el botó <i>editar</i> del missatge en qüestió. Si algú ja ha respost al teu missatge trobaràs un petit text sota el teu missatge quan tornis a la pantalla del tema que llista el nombre de vegades que l'has editat. Això no apareixerà si ningú hi ha contestat ni tampoc si són els administradors o els moderadors els que editen el missatge (haurien de deixar un missatge dient què han modificat i per què). Si us plau tingues en compte que els usuaris normals no poden esborrar un missatge un cop algú hi ha contestat.");
$faq[] = array("Com afegeixo una signatura al meu missatge?", "Per afegir una signatura a un missatge primer n'has de crear una, això es fa a través del teu perfil. Un cop creada pots activar l'opció <i>Afegir signatura</i> al formulari de publicació per tal d'afegir-la. També pots afegir la signatura per defecte a tots el missatges activant l'opció corresponent del teu perfil (de totes maneres pots desactivar l'addició de la teva signatura a missatges individuals deseleccionant l'opció afegir signatura al formulari de publicació).");
$faq[] = array("Com creo una enquesta?", "Crear una enquesta és fàcil, quan publiques un tema nou (o edites el primer missatge d'un tema, si hi permís) hauries de veure l'opció <i>Afegir enquesta</i> sota el quadre del missatge principal (si no ho pots veure probablement no tens permís per crear enquestes). Has d'introduir un títol per a l'enquesta i llavors dues opcions com a mínim (per afegir una opció escriu la pregunta i clica sobre el botó <i>Afegir opció</i>). També pots decidir el límit de temps durant el qual l'enquesta estarà activa, 0 és una enquesta que no acaba mai. Hi haurà un límit per al nombre d'opcions que pots llistar que és decidit per l'administrador del fòrum.");
$faq[] = array("Com edito o esborro una enquesta?", "Igual com amb els missatges, les enquestes només poden ser editades per l'usuari que les va crear, un moderador o l'administrador del fòrum. Per editar una enquesta clica sobre el primer missatge del tema (aquest sempre hi té l'enquesta associada). Si ningú ha emès cap vot llavors els usuaris poden esborrar l'enquesta o editar qualsevol opció d'aquesta, no obstant si algú ja hi ha votat només els moderadors i administradors poden editar-la o esborrar-la. Això és per evitar que la gent les falsegi canviant opcions a mitja enquesta.");
$faq[] = array("Per què no puc accedir a algun dels fòrums?", "Alguns fòrums poden estar limitats a determinats grups d'usuaris. Per veure, llegir, enviar missatges, etc. potser necessitis una autorització especial, només el moderador del fòrum i l'administrador poden permetre't l'accés, prova de contactar-hi.");
$faq[] = array("Per què no puc votar a les enquestes?", "Només els membres registrats poden votar a les enquestes (per tal de prevenir el falsejament dels resultats), si t'has registrat i encara segueixes sense poder votar llavors probablement no tinguis els permisos necessaris.");


$faq[] = array("--","Formateig i Tipus de temes");
$faq[] = array("Què és el codi BBCode?", "BBCode és una implementació especial de l'HTML, si pots utilitzar BBCode o no ho decideix l'administrador (també pots deshabilitar-lo per a missatges individuals al formulari de publicació). BBCode té un estil molt similar al de l'HTML, els marcadors van entre claudàtors [ i ] i ofereix un major control sobre què i com es mostra alguna cosa. Per més informació sobre el BBCode mira la guia  a que pots accedir des de la pàgina de publicació.");
$faq[] = array("Puc utilitzar l'HTML?", "Depèn de si l'administrador t'ho permet o no, ell té el control sobre això. Si se't permet utilitzar-lo probablement et trobaràs amb que només funcionen determinats marcadors. Això és una característica de <i>seguretat</i> per evitar que la gent perjudiqui la visualització del fòrum utilitzant marcadors que en trenquin l'estructura. Si l'HTML està habilitat el pots desactivar per a missatges individuals a través del formulari de publicació.");
$faq[] = array("Què són els Smileys?", "Els Smileys o Emoticons son petites imatges que poden ser utilitzades per expressar alguns sentiments utilitzant un petit codi, e.g. :) significa feliç, :( significa trist. La llista completa d'emoticons es pot veure al formulari de publicació. Intenta no abusar-ne però, poden fer ràpidament que un missatge es torni il·legible i un moderador pot decidir treure'ls o eliminar el missatge completament.");
$faq[] = array("Puc ficar imatges als missatges?", "Pots mostrar imatges en els teus missatges. No obstant, de moment no hi ha una manera per pujar directament les imatges al fòrum. Per això has d'enllaçar-la a una imatge emmagatzemada en un servidor web accessible públicament, e.g. http://www.some-unknown-place.net/my-picture.gif. No pots ficar enllaços a imatges emmagatzemades al teu PC (si no és que es tracta d'un servidor accessible públicament) ni imatges emmagatzemades amb mecanismes d'autentificació, e.g. bústies de hotmail, yahoo, pàgines protegides per contrasenya, etc. Per mostrar la imatge utilitza o bé el marcador de BBCode [img] o l'apropiat d'HTML (si està permès).");
$faq[] = array("Què són los Anuncis?", "Els anuncis sovint contenen informació important i els hauries de llegir tan aviat com sigui possible. Els anuncis apareixen a dalt de cada pagina al fòrum on són publicats. Si pots o no publicar un anunci depens dels permisos necessaris, aquests els decideix l'administrador.");
$faq[] = array("Què són els Temes Permanents?", "Els temes permanents apareixen sota els anuncis als fòrums i només a la primera pàgina. Sovint són força importants i els hauries de llegir quan sigui possible. Igual com amb els anuncis l'administrador del fòrum decideix quins permisos es necessiten per publicar temes permanents a cada fòrum.");
$faq[] = array("Què són els Temes Tancats?", "Els temes tancats o bloquejats estan així perquè un moderador o administrador del fòrum ho ha decidit. No pots enviar respostes als temes tancats i qualsevol enquesta que continguessin s'acaba automàticament. Els temes poden ser tancats per moltes raons.");


$faq[] = array("--","Nivells d'usuari i Grups");
$faq[] = array("Què són els Administradors?", "Els administradors són persones a les quals se'ls ha assignat el nivell de control més alt sobre el fòrum sencer. Poden controlar totes les facetes del fòrum com ara permisos, excloure usuaris, crear grups d'usuaris o moderadors, etc. També tenen permisos de moderador a tot el fòrum.");
$faq[] = array("Què són els Moderadors?", "Els moderadors són persones (o grups de persones) el treball dels quals és vigilar la marxa dels fòrums regularment. Poden editar o esborrar missatges i tancar, desbloquejar, moure, esborrar i dividir temes al fòrum que moderen. Normalment els moderadors hi són per evitar que la gent es desviï dels temes o que enviïn missatges ofensius o insultants.");
$faq[] = array("Què són els Grups d'Usuaris?", "Els grups d'usuaris són un mètode per que l'administrador pugui agrupar usuaris. Cada usuari pot pertànyer a diversos grups (això és diferent de molts altres fòrums) i a cada grup se li poden assignar drets d'accés individuals. Això facilita a l'administrador fer moderadors d'un fòrum a un grup d'usuaris o donar-los accés a un fòrum privat.");
$faq[] = array("com puc unir-me a un Grup d'Usuaris?", "Per unir-te a un grup d'usuaris clica l'enllaç de Grups d'Usuaris situat a la capçalera de la pàgina (depenent del disseny de la plantilla) i podràs veure tots els grups d'usuaris. No tots els grups son <i>oberts</i>, alguns estan tancats i d'altres fins i tot poden estar ocults. Si el grup és obert pots demanar unir-t'hi clicant el botó corresponent. El moderador del grup d'usuaris haurà d'acceptar la teva demanda, potser se't demanarà per què vols unir-te al grup. Si us plau no critiquis el moderador d'un grup en el cas de no ser acceptat,  segur que tindran les seves raons.");
$faq[] = array("Com em converteixo en Moderador d'un Grup d'Usuaris?", "Inicialment els grups d'usuaris els crea l'administrador del fòrum i també assigna un moderador. Si estàs interessat en crear un grup d'usuaris hauries de contactar amb l'administrador, prova d'enviar-li un missatge privat.");


$faq[] = array("--","Missatgeria privada");
$faq[] = array("No puc enviar missatges privats!", "Hi ha tres possibles raons: no estàs registrat o no has iniciat una sessió, l'administrador del fòrum ha deshabilitat la missatgeria privada a tot el fòrum o bé t'ha prohibit enviar missatges privats. Si es tracta del darrer cas prova de preguntar-li a l'administrador el perquè.");
$faq[] = array("No paro de rebre missatges privats no desitjats!", "En un futur afegirem una llista per ignorar remitents al sistema de missatgeria privada. De moment, però, si no pares de rebre missatges no desitjats d'algú informa l'administrador del fòrum, ell pot prohibir a un usuari enviar missatges privats.");
$faq[] = array("He rebut spam o correu amb insults d'algú d'aquest fòrum!", "Sentim molt sentir això. La característica d'enviar emails d'aquest fòrum inclou mecanismes de seguretat per localitzar els usuaris que envien aquests missatges. Li hauries d'enviar un email a l'administrador amb una còpia completa de l'email que has rebut, és molt important que inclogui les capçaleres (conté detalls de l'usuari que ha enviat l'email). Ell se'n pot ocupar.");

//
// Les següents entrades haurien de romandre en tots els idiomes i per totes les modificacions
//
$faq[] = array("--","Sobre phpBB 2");
$faq[] = array("Qui ha programat aquest fòrum?", "Aquesta aplicació (en la seva forma original) està produïda, llançada i amb drets d'autor de  <a href=\"http://www.phpbb.com/\" target=\"_blank\">phpBB Group</a>. Està disponible mitjançant la GNU General Public Licence i és de lliure distribució, veure l'enllaç per més detalls.");
$faq[] = array("Per què la característica X no està disponible?", "Aquesta aplicació està escrita i sota llicència a través del phpBB Group. Si creus que s'ha d'incloure una característica visita la pàgina web phpbb.com i mira què hi tenen a dir. Si us plau no enviïs demandes de noves característiques als fòrums de phpbb.com, el Grup utilitza sourceforge per manejar les tasques per incloure noves característiques. Si us plau llegeix els fòrums i per veure quina és la nostra posició, si és que en tenim, respecte una característica donada i llavors segueix el procediment descrit.");
$faq[] = array("Amb qui he de contactar sobre abusos i/o problemes legals relacionats amb aquest fòrum?", "Hauries de contactar amb l'administrador del fòrum. Si no pots esbrinar qui és, primer hauries de contactar amb un dels moderadors del fòrum i preguntar-li amb qui t'hauries de posar en contacte. Si fins i tot així no obtens cap resposta hauries de contactar amb el propietari del domini (fes una cerca whois) o si el fòrum és en un servei gratuït (e.g. yahoo, free.fr, f2s.com, etc.), l'administració o departament d'abús d'aquest servei. Si us plau tingues en compte que el phpBB Group no en té cap control i no pot ser de cap manera responsable de com, on o per qui aquest fòrum és utilitzat. És absolutament inútil contactar amb el phpBB Group en relació amb qualsevol problema legal (comentaris difamatoris, etc.) que no estigui relacionat directament amb la pàgina web phpbb.com o l'aplicació de phpBB mateixa. Si envies un email al phpBB Group sobre un ús aliè d'aquesta aplicació hauries d'esperar una resposta tibant o cap resposta en absolut.");

//
// Això finalitza les entrades del FAQ
//

?>
