<?php
/***************************************************************************
 *                          lang_bbcode.php [Danish]
 *                            -------------------
 *   begin                : Wednesday Oct 3, 2001
 *   copyright            : (C) 2001 The phpBB Group
 *   email                : support@phpbb.com
 *
 *   $Id$
 *
 *
 ***************************************************************************/

/***************************************************************************
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 ***************************************************************************/
 
//
// Translation done by Ken Christensen (Dalixam)
//

  
$faq[] = array("--","Introduktion");
$faq[] = array("Hvad er BBkoder?", "BBKoder er en speciel udgave af HTML. Om du kan benytte BBkode i dine indlæg, er et valg administratoren afgør. Ud over at det kan angives med virkning for hele forumet, kan det også angives ud for hver indlæg, dette kan sættes når indlægget skrives. BBkoden i sig selv en bygget op lige som HTML, der findes en start kode og en slut kode disse er omgivet af hak parenteser [ og ] i stedet for &lt; og &gt; De give en stor kontrol over hvad og hvordan indholdet præsenteres. Afhængig af den template der bruges vil du opdage at det er meget nemt og intuitivt at bruge BBkoder, dette sker gennem den <i>vælg og klik</i> bruger flade som findes og besked feltet når du skriver et nyt indlæg. Selv om der er lavet med denne neme brugerflade kan du stadig få brug for denne lille vejledning.");

$faq[] = array("--","Tekst Formatering");
$faq[] = array("Hvordan man laver skriften fed, kursiv og/eller understreget", "BBKode består af start og slut koder der gør det muligt hurtigt at ændre udseende på skrift typen. Dette kan gøres på følgende mådehis: <ul><li>For at lave en tekst streng fed, placere da disse start/stop koder hhv. foran og bagved teksten <b>[b][/b]</b>, f.eks. <br /><br /><b>[b]</b>Hej<b>[/b]</b><br /><br /> vil blive til <b>Hej</b></li><li> På samme måde kan der laves understregning med disse koder <b>[u][/u]</b>, f.eks.:<br /><br /><b>[u]</b>God Morgen<b>[/u]</b><br /><br />vil blive vist som <u>God Morgen</u></li><li>for at lave kursiv skrives <b>[i][/i]</b>, f.eks.<br /><br />Dette er <b>[i]</b>Fantastisk!<b>[/i]</b><br /><br />vil vises som Dette er <i>Fantastisk!</i></li></ul>");
$faq[] = array("Hvordan ændre man størrelsen og farven", "For at ændre farven på teksten og størrelsen benyttes følgende start / stop koder. Var opmærksom på at udseendet vil være afhængig af slutbrugerens browser og opsætning: <ul><li>Skift af skriftens farve sker ved at omkranse dem af <b>[color=][/color]</b>. Du kan enten angive en farve dette skal dog ske på engelsk (f.eks. red, blue, yellow, osv.) eller du kan angive den hexadecimale 3 dobbelte alternativ, f.eks. #FFFFFF=hvid, #000000=sort, #00FF00=grøn. et eksempel på brugen kunne være at lave en rød tekst:<br /><br /><b>[color=red]</b>Hallo!<b>[/color]</b><br /><br />eller<br /><br /><b>[color=#FF0000]</b>Hallo!<b>[/color]</b><br /><br />Dette vil give <span style=\"color:red\">Hallo!</span></li><li> i begge tilfælde. Tekst størrelsen kan ændres på samme måde ved at bruge <b>[size=][/size]</b>. disee start/stop koder er afhængige af den template som du bruger men det anbefalede format er et tal der angive hvor mange pixel skriften skal være, startende fra 1 (så lille at den ikke kan ses) helt op til 29 (meget stor). For eksempel:<br /><br /><b>[size=9]</b>LILLE<b>[/size]</b><br /><br />vil i almindelighed føre til <span style=\"font-size:9px\">LILLE</span><br /><br />mens:<br /><br /><b>[size=24]</b>KOLOENORM!<b>[/size]</b><br /><br />vil se ud som <span style=\"font-size:24px\">KOLOENORM!</span></li></ul>");
$faq[] = array("Kan jeg kombinere de forskellige koder?", "Ja, og selvfølgelig kan du ,for at fange læserens opmærksomhed skrive som dette:<br /><br /><b>[size=18][color=red][b]</b>SE PÅ MIG!<b>[/b][/color][/size]</b><br /><br />dette vil give et output som vil se ud som dette <span style=\"color:red;font-size:18px\"><b>SE PÅ MIG!</b></span><br /><br />Vi anbefaler dog ikke at lave for meget af den slags tekst! Husk det er op til dig, forfatteren af indlægget at alle koder også afsluttes korrekt med deres tilhørende stop kode(r). F.eks. er følgende ikke en korrekt skrive måde:<br /><br /><b>[b][u]</b>Dette er forkert<b>[/b][/u]</b>");

$faq[] = array("--","Citat og fast bredde tekst");
$faq[] = array("Citere en tekst når der svares", "Dette kan gøres på 2 måder, du kan citere tekst med eller uden reference.<ul><li>Når du benytter citat funktionen til at besvare et indlæg, bør du bemærke at citatet tilføres omkranset af start og slut koderne: <b>[quote=\"\"][/quote]</b>. Denne metode giver dig mulighed for at citere med en reference til en person eller hvad du nu måtte ønske at der skal stå! For eksempel hvis der ønskes at citere en tekst streng som bo har skrevet, skrives:<br /><br /><b>[quote=\"BO\"]</b>Teksten som BO har skrevet placeres her<b>[/quote]</b><br /><br /> der resultat som andre brugere vil se, vil være at der står BO skrev: foran teksten. Husk at du altid <b>skal</b> skrive anførelses tegn \"\" omkring navnet du citere, du er ikke valgfrie.</li><li>Den anden metode giver dig fri mulighed for at citere uden at angive kilde. For at gøre dette omkranses teksten af <b>[quote][/quote]</b> start og stop koderne. når så teksten vises vil der simpelt hen stå, Citat: foran selve teksten.</li></ul>");
$faq[] = array("Skrive kode eller fast brede tekst", "Hvis du ønsker at kunne skrive en tekst hvor i der skal indgå en tekst som til forveksling ligne noget kode, eller hvis teksten skal have fast bredde, f.eks. Courier skrift typen. Skal du omkranse teksten med start / stop koderne <b>[code][/code]</b>, f.eks.<br /><br /><b>[code]</b>echo \"Dette er noget kode\";<b>[/code]</b><br /><br />Al formatering det benyttes inden i <b>[code][/code]</b> blive bevaret og vist når du senere ser indlæget.");

$faq[] = array("--","Lave lister");
$faq[] = array("Lave en unummereret liste", "BBkode understøtter 2 former for lister, unummererede og nummererede. De er i bund og grund det samme som de tilsvarende HTML koder. En unummereret liste viser listens indhold lige efter hinanden, hver liste element indledes med en indrykning med en prik foran. For at lave sådan liste benyttes <b>[list][/list]</b> og hver liste punkt adskilles med <b>[*]</b>. f.eks. for at liste dine favorit farver:<br /><br /><b>[list]</b><br /><b>[*]</b>Rød<br /><b>[*]</b>Blå<br /><b>[*]</b>Gul<br /><b>[/list]</b><br /><br />Dette vil lave følgende liste:<ul><li>Rød</li><li>Blå</li><li>Gul</li></ul>");
$faq[] = array("Lave en nummereret liste", "Den anden type liste er en nummereret liste, som giver dig mulighed for at specificere hvad der skal være foran listens punkter. For at lave en nummereret liste skal du bruge <b>[list=1][/list]</b> eller alternativt <b>[list=a][/list]</b> for at lave en liste der indledes med alfabetet. Lige som med unummererede lister hvert punkt på listen skal adskilles med <b>[*]</b>. F.eks:<br /><br /><b>[list=1]</b><br /><b>[*]</b>Gå til butikken<br /><b>[*]</b>Køb en ny computer<br /><b>[*]</b>Tramp på den når den går i stykker<br /><b>[/list]</b><br /><br />vil se ud som dette:<ol type=\"1\"><li>Gå til butikken</li><li>Køb en ny computer</li><li>Tramp på den når den går i stykker</li></ol>Lige så kan du med en alfabet liste bruge:<br /><br /><b>[list=a]</b><br /><b>[*]</b>Det første svar<br /><b>[*]</b>Det 2 svar<br /><b>[*]</b>Det 3 svar<br /><b>[/list]</b><br /><br />som vises som<ol type=\"a\"><li>Det første svar</li><li>Det 2 svar</li><li>Det 3 svar</li></ol>");

$faq[] = array("--", "Fremstilling af Links");
$faq[] = array("Lave et link til en anden hjemmeside", "phpBB BBKode giver mulighed for flere måder at lave links på (URIs, Uniform Resource Indicators) eller mere kendt som URLs.<ul><li>Den første af disse metoder benytter<b>[url=][/url]</b> start / stop koderne, efter URL= kan udfyldes med stien til den side som linket skal pege på. For eksempel for at lave et link til phpBB.com skal du skrive:<br /><br /><b>[url=http://www.phpbb.com/]</b>Besøg phpBB!<b>[/url]</b><br /><br />Det vil se ud som dette link, <a href=\"http://www.phpbb.com/\" target=\"_blank\">Besøg phpBB!</a> Hvis du prøver dette vil du opdage at linket åbner i et nyt vindue, for at brugerne kan fortsætte med at kigge i forumet hvis de ønsker.</li><li>Hvis du ønsker et URLen skal vises som navnet på linket kan dette gøres ved at lave det på denne måde:<br /><br /><b>[url]</b>http://www.phpbb.com/<b>[/url]</b><br /><br />Det vil give et link der ser således ud, <a href=\"http://www.phpbb.com/\" target=\"_blank\">http://www.phpbb.com/</a></li><li>Tilslut har phpBB også noget kaldet <i>Magiske Links</i>, dette vil gøre alle korrekt indtastede Internet adresser til et link, uden at du angiver nogle start eller stop koder, ej heller det indledende http://. F.eks ved at skrive www.phpbb.com i dit indlæg vil automatisk generere følgende link <a href=\"http://www.phpbb.com/\" target=\"_blank\">www.phpbb.com</a> når indlægget senere vises.</li><li>Det samme gælder for email adresser, du kan enten angive en adresse bestemt ved at skrive:<br /><br /><b>[email]</b>no.one@domain.adr<b>[/email]</b><br /><br />hvilket vil lave denne link <a href=\"emailto:no.one@domain.adr\">no.one@domain.adr</a> eler du kan blot skrive no.one@domain.adr i indlægget. det vil automatisk blive oversat når det vises.</li></ul>Som med alle andre BBKoder kan du angive URLs omkring alle andre koder, såsom <b>[img][/img]</b> (se næste punkt), <b>[b][/b]</b>, osv. Lige som me tekst formaterings koderne er det op til dig at sikre at de korrekte start / stop koder er til stede i den rigtige rækkefølge for eksempel:<br /><br /><b>[url=http://www.phpbb.com/][img]</b>http://www.phpbb.com/images/phplogo.gif<b>[/url][/img]</b><br /><br />er <u>ikke</u> rigtigt hvilket kan føre til at dit indlæg bliver slette, så vær opmærksom.");

$faq[] = array("--", "Indsætte billede i indlæg");
$faq[] = array("Tilføje et billede til et indlæg", "phpBB BBKode indeholder start/stop koder til at vise billeder i dine indlæg. Der er 2 meget vigtige ting at huske på når disse koder bruges; mange brugere ønsker ikke for mange billeder i indlæggene og for det andet det billede som du ønsker at bruge skal allerede være tilgængeligt på Internettet (Det kan ikke kun være på din egen computer, med mindre du køre en webserver!). Det findes p.t. ingen måde hvorpå lokale billeder kan håndteres i phpBB (Alle disse punkter forventes og blive løst i den næste store release of phpBB). For at vise et bilede skal du omkranse dets URL med <b>[img][/img]</b> start og stop koderne. For eksempel:<br /><br /><b>[img]</b>http://www.phpbb.com/images/phplogo.gif<b>[/img]</b><br /><br />Som beskrevet ovenfor kan du omkranse et billede med <b>[url][/url]</b> koder hvis du ønsker, f.eks.<br /><br /><b>[url=http://www.phpbb.com/][img]</b>http://www.phpbb.com/images/phplogo.gif<b>[/img][/url]</b><br /><br />som så vil blive vist således:<br /><br /><a href=\"http://www.phpbb.com/\" target=\"_blank\"><img src=\"http://www.phpbb.com/images/phplogo.gif\" border=\"0\" alt=\"\" /></a><br />");

$faq[] = array("--", "Andre ting");
$faq[] = array("Kan jeg tilføje mine egne start og stop koder?", "Nej, Ikke direkte i phpBB 2.0. Vi forsøger af finde en metode til at tilbyde egne BBkoder i den næste store version");

//
// This ends the BBCode guide entries
//

?>