<?php
/***************************************************************************
 *                          lang_faq.php [english]
 *                            -------------------
 *   begin                : Wednesday Oct 3, 2001
 *   copyright            : (C) 2001 The phpBB Group
 *   email                : support@phpbb.com
 *
 *   $Id$
 *
 *
 ***************************************************************************/

/***************************************************************************
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 ***************************************************************************/
 
// 
// To add an entry to your FAQ simply add a line to this file in this format:
// $faq[] = array("question", "answer");
// If you want to separate a section enter $faq[] = array("--","Block heading goes here if wanted");
// Links will be created automatically
//
// DO NOT forget the ; at the end of the line.
// Do NOT put double quotes (") in your FAQ entries, if you absolutely must then escape them ie. \"something\"
//
// The FAQ items will appear on the FAQ page in the same order they are listed in this file
//
 
  
$faq[] = array("--","Login og Tilmeldings problemer");
$faq[] = array("Hvorfor kan jeg ikke logge ind?", "Er du tilmeldt? Det er absolut nødvendigt at udfylde en tilmelding for at kunne logge ind. Er du udelukket fra dette forum (En besked vil blive vist hvis du er)? Hvis dette er tilfældet bør du kontakte webmaster forumets administrator for at finde ud af hvorfor. Hvis du har udfyldt tilmeldings formen og ikke er låst ude og du stadig ikke kan logge ind skal du kontrollere dit bruger navn og kode ord igen. normalt er det det der er problemet, Hvis ikke dette hjælper kan du kontakte forumets administrator det er måske problemer på siden.");
$faq[] = array("Hvorfor er det nødvendigt at tilmelde sig?"," Det er ikke sikkert at det er nødvendigt, Det er administratoren af forumet der afgør om det er nødvendigt at tilmelde sig, for at skrive indlæg. Tilmelding er dog altid en god ide da dette giver adgang til flere muligheder som ikke er tilgængelige for gæste brugere, dette er funktioner som personligt billede på dine indlæg, private beskeder, sende post til andre tilmeldte brugere, bruger grupper, osv. Det tager kun et øjeblik at tilmelde sig og det anbefales derfor at gøre det.");
$faq[] = array("Hvorfor bliver jeg logge ud hele tiden?", "Hvis du ikke markere <i>Log mig på automatisk ved hvert besøg</i> boksen når du logger ind, vil dette login kun gælde i en begrænset tidsperiode. Dette er til for at forhindre andre i at misbruge din konto. Hvis du ønske hele tiden at være logget på skal du derfor markere denne boks næste gang du logger på, Dette er ikke anbefalelsesværdigt på en computer som også bruges af andre personer, f.eks. Bibliotek, Internet cafe, skole, osv.");
$faq[] = array("Hvordan forhindre jeg at mit navn fremgår af listen, Hvem er på nu?", "I din profil findes en indstilling <i>Skjul min online status</i>, Hvis du vælger <i>ja</i> Vil du kun fremgå af forumets Administratorer og dig selv andre brugere kan ikke se dig. Du vil blive registeret som en skjult bruger.");
$faq[] = array("Jeg har glemt mit kodeord!", "Gå ikke i panik! Selvom det ikke er muligt at finde dit gamle kodeord er det muligt lave et nyt. For at gøre dette skal du gø til login siden og klikke på <u>Jeg har glemt mit kodeord, send nyt kodeord, via email</u>, Følg instruktionen som fremkommer og du skulle gerne kunne logge ind igen i løbet af kort tid");
$faq[] = array("Jeg har tilmeldt mig, men kan ikke logge ind!", "Først bør du kontrollere at du har tastet korrekt ind (husk stor / små bogstaver har betydning). Hvis dette er i orden, kan det være 1 af følgende muligheder. Hvis COPPA understøttelse er slået til på forumet og du har klikket på <u>jeg er under 13 år</u> linket da du tilmeldte dig, skal du følge instruktionen du har modtaget. Hvis dette ikke er tilfældet kan det skyldes at din konto skal aktiveres? Nogle forumer kræver at alle nye tilmeldte brugere skal aktiveres inden de kan benyttes, Enten af dig selv eller af administratoren. Da du tilmeldte dig, skulle du gerne være blevet gjort opmærksom på om aktivering af kontoen var nødvendigt. Hvis du modtog en email, skal du fælge instruktionen, Hvis du ikke modtog nogen email kan det skyldes at email adressen ikke var korrekt? Aktivering benyttes er for at mindske muligheden for at <i>uønskede</i> personer misbruger systemmet ved at give ukorrekte oplysninger. Hvis du er 100% sikker på at du har skrevet den rigtige email, og den virker, så prøv at kontakte forumets administrator.");
$faq[] = array("Jeg har tilmeldt mig for et stykke tid siden, og kan nu ikke logge ind længere?!", "Der kan være flere årsager, den mest sandsynlige årsag er at du indtaster et forkert bruger navn eller kodeord, (Hvis du stadig har emailen som du modtog da du tilmeldte dig kan du se i den). Det kan også skyldes at administratoren har slettet din konto af en eller anden årsag. Hvis dette er tilfældet kan det skyldes at du aldrig skrev nogle indlæg? Det er normal procedure med jævne mellemrum at fjerne brugere som aldrig har skrevet indlæg, for at mindske databasens størrelse. Tilmeld dig igen for at blande dig i diskussionerne.");


$faq[] = array("--","Bruger indstillinger og muligheder");
$faq[] = array("Hvordan ændre jeg min opsætning?", "Alle dine indstillings muligheder (Hvis du er tilmeldt bruger) gemmes i databasen. For at se eller ændre dem, skal du klikke på <u>Profil</u> linket (normalt vis i toppen af siden, men er ikke altid tilfældet). Dette link vil føre dig til en side hvor du kan ændre din opsætning");
$faq[] = array("Tiden er ikke vist korrekt!", "Tiden er næsten med sikkerhed rigtig, det du muligvis ser er en tid i en anden tidzone end den du er i. Hvis det er tilfældet, bør du rette i din profil hvor du kan sætte hvilken tidzone du befinder dig i, f.eks. København, Lodon,Paris, New York, Sydney, osv. Vær opmærksom på at det kun er muligt for tilmeldte brugere at ændre tidzonen, ligesom de fleste andre indstillinger der kun kan ændres af tilmeldte brugere, så hvis ikke du er tilmeldt er det måske på tide at gøre det!");
$faq[] = array("Jeg har ændret tidszonen og tiden er stadig forkert!", "Hvis du er sikker på at du har sat tidzonen rigtigt og der stadig vises en forkert tid, er den mest sandsynlige mulighed at der vises i <i>sommertid</i>. Forumet er ikke designet til at håndtere skiftet mellem sommer/vintertid så i sommerhalvåret kan uret gå forkert i forhold til din lokale tid.");
$faq[] = array("Mit sprog er ikke i listen!", "Det er nok fordi administratoren ikke har installeret det, eller fordi det ikke er oversat endnu. Forsøg at spørge forumets administrator om det er muligt at installere den sprog pakke som du har brug for, Hvis ikke det eksistere kan du altid selv lave oversættelsen, mere information om hvordan dette gøres findes på hos phpBB Gruppens hjemmeside (se link nederst på siden)");
$faq[] = array("Hvordan får jeg vist et billede under mit brugernavn?", "Der findes mulighed for 2 billeder under dit brugernavn når der vises indlæg. Det første er et billede der er tilknyttet det niveau du som tilmeldt bruger har på systemet, normalt udformet som stjerner eller kasser som indikere hvor mange indlæg du har skrevet eller din stilling i forumet. Under dette kan der være et større billede, Dette er normalt et personligt billede. Det er op til forumets administrator om det skal være muligt at have sit eget billede og hvilke billedmuligheder du som bruger har. Hvis ikke du i din personlig profil kan angive et billede er det fordi administratoren har valgt dette sådan, Du kan evt. spørge dem om grunden til dette (de har sikkert en god forklaring!)");
$faq[] = array("Hvordan ændre jeg mit niveau?", "Normalt kan du ikke selv ændre dette (Niveauet vises under dit bruger navn i dine indslag og i din profil). De fleste forumer bruger niveauer til at vise hvor mange indlæg en person har skrevet eller til at identificere bestemte brugere, f.eks. redaktører og Administratorer kan have deres specielle niveau betegnelse. ær venlig ikke at misbruge forum ved at skrive så mange indlæg som muligt blot for at øge dit niveau, Du vil sandsynligvis hurtigt finde ud af at enten redaktørerne eller administratorerne vil sænke dit niveau til laves muligt.");
$faq[] = array("Når jeg kliker på en brugers email, bliver jeg spurgt om at logge ind?", "Ja desværre, kun tilmeldte brugere kun tilmeldte brugere kan sende email, via det indbyggede email system (Hvis administratoren har slået denne funktion til). Dette er til for at forhindre anonyme gæster i at misbruge systemmet.");


$faq[] = array("--","Skive et indlæg");
$faq[] = array("Hvordan skriver jeg et nyt Emne i et forum?", "Nemt, Klik på knappen <i>Nyt Emne</i> på enten forum siden eller emne siden. Det kan være det er nødvendigt at tilmelde sig som bruger før du kan skrive et nyt indlæg, Dine muligheder er altid listet i bunden af forum og emne siden (<i>Du kan skrive nye Emner, Du kan stemme på afstemninger i dette forum osv.<i> listen)");
$faq[] = array("Hvordan retter jeg eller sletter et indlæg?", "Med mindre du er stedets administrator eller forumets redaktør, så kan du kun rette din egne indlæg. Du kan rette et indlæg (nogle gange kun i en begrænset tid efter det er skrevet)ved at klike <i>ret</i> knappen ud for det rette indlæg.  Hvis nogen allerede har svaret på indlægget vil der fremkomme en tekst under indlægget, når du returnere til Emne oversigten, der fortæller antallet af gange du har rettet det. Dette vil kun ske hvis ingen har svaret, Det vil heller ikke ske hvis det er Administratorer eller redaktører der har rettet det (De bør skrive i indlægget, hvad de har rettet og hvorfor). Vær opmærksom på at normale brugere ikke kan slette et indlæg når først der er blevet besvaret på det.");
$faq[] = array("Hvordan tilføjer jeg en underskrift til mine indlæg?", "For et tilføje en underskrift i et indlæg, skal du først oprette en underskrift, dette gøres under din profil. Når den først er lavet, kan du marker boksen <i>Tilføj underskrift</i> når du skriver indlægget. Du kan også vælge at der altid skal tilføjes en underskrift til dine indlæg, ved at markere den til formålet boks under opsætningen af din profil (Du kan stadig undgå at din underskrift kommer med i et specielt indlæg, ved at fjerne markeringen tilføj underskrift inden du indsender indlægget)");
$faq[] = array("Hvordan laver jeg en afstemning?", "At lave en afstemning er nemt, Når du laver et nyt emne (eller hvis du har tilladelse: retter i det første indlæg under et emne) Findes i bunden af siden <i>Tilføj en afstemning</i> (Hvis du ikke kan se dette er det sandsynligvis fordi du ikke har rettighed til at oprette en afstemning) Her skal du tilføje en overskrift som beskriver afstemningen, samt mindst 2 afstemnings muligheder (for at lave en afstemnings mulighed, skal du indtaste den første afstemnings mulighed, for dernæst at klikke på knappen<i> Tilføj afstemnings mulighed</i>. Du kan også angive i hvor lang tid afstemningen skal køre, hvis du ikke angive en tid eller skriver 0, betyder det at den ikke stopper til en bestemt dato. Der vil dog være en grænse for hvor mange afstemnings muligheder du kan oprette, dette sættes af forumets administrator");
$faq[] = array("Hvordan retter eller sletter jeg en afstemning?", "Lige som med andre Emne indlæg, afstemninger kan kun rettes af den person som oprindeligt skrev afstemningen, eller af en redaktør/administrator af forumet. For at rette i en afstemning (teksten) klik på det første indlæg i afstemningen (Det er altid dette indlæg som har tilknyttet afstemningen). Såfremt der ikke er foretaget nogen stemmer, kan der rettes og slettes i afstemnings mulighederne, Hvis der derimod er blevet afgivet stemmer er det kun forumets redaktører/Administratorer der kan rette eller slette en afstemning. Dette er for at forhindre at folk kan manipulere med resultatet ved at ændre i betydningen halvvejs inde i afstemningen");
$faq[] = array("Hvorfor kan jeg ikke få adgang til et forum?", "Nogle forums kan være begrænsede til kun at acceptere bestemte brugere eller grupper. Disse kan igen indeles i Se, læse eller skrive indlæg osv. Det kan være at det forum du forsøger at få adgang til kræver specielle tilladelser, Kun forumets redaktør eller administratoren kan give disse tilladelser, Du bør kontakte dem hvis du mener at du bør have denne rettighed.");
$faq[] = array("Hvorfor kan jeg ikke stemme i en afstemning?", "Kun tilmeldte brugere kan afgive stemme (for at forhinder at der stemmes flere gange af den samme bruger). Hvis du er tilmeldt bruger og stadig ikke kan stemme er det sandsynligvis fordi du ikke har de nødvendige rettigheder.");


$faq[] = array("--","Formatering og Emne typer");
$faq[] = array("Hvad er BBKoder?", "BBKoder er en speciel form for HTML, Om du kan bruge HTML eller BBKoder er noget administratoren af forumet kan sætte op (Du kan også fjerne muligheden for dette per Emne). BBKoder skrive på samme måde som HTML, hvor teksten omgives af en start kode og et slut kode, koderne er omsluttet af hak parenteser [ og ] i stedet for &lt; og &gt; og de tilbyder større kontrol over hvad og hvordan teksten præsenteres. For at få mere information om BBKoder se da hjælpen som ses når der postes et indlæg.");
$faq[] = array("Kan jeg bruge HTML?", "Det afhænger af om administratoren har givet dig ret til dette, Det er dem der har den fulde kontrol over hvem der må få lov til dette. Hvis du har ret til dette vil du muligvis finde ud af at kun bestemte tags virker. Dette er en ekstra <i>sikkerhed</i> for at forhindre personer i at bruge bestemte koder som kan ødelægge indholdet for andre brugere, eller give andre problemer. Hvis du overordnet har mulighed for HTML kan dette slås fra under hvert indlæg når indlægget skrives.");
$faq[] = array("Hvad er Smilies?", "Smilies, er små grafiske ikoner - eller billeder, som kan benyttes til at signaler bestemte følelser, dette gøres igennem en kort tekst kode, f.eks. :) betyder <i>Glad</i>, :( betyder <i>ked af det</i>. Den komplette liste over alle smilies kan ses når det skrives et nyt indlæg. Husk dog at det ikke er god tone at over misbruge smilies, De kan hurtigt gøre et indlæg uoverskueligt, og en redaktør eller administrator kan beslutte at fjerne dem med hård hånd, måske endda selve indlægget");
$faq[] = array("Kan jeg få vist et bilede sammen med mit indlæg?", "Ja det kan de. Der er dog på nuværende tidspunkt ingen facilitet til at uploade dem til forumet. Derfor er det nødvendigt med et link til en anden hjemmeside (komplet URL) hvor billedet altid kan hentes fra, en komplet URL kan f.eks. se ud som http://www.et-eller-andet-sted.dk/billeder/mit-billede.gif. Du kan ikke henvise til billeder på din egen maskine (medmindre disse er på en server der altid er på Internettet) Ej heller billeder gemt bag login funktioner, f.eks. hotmail/yahoo postkasser eller andre kodeords beskyttede steder. For at vise et billede kan du bruge enten BBkode [img] eller anden HTML kode der kan det samme (Hvis tilladt af administrator).");
$faq[] = array("Hvad er Bekendtgørelser?", "Bekendtgørelser indeholder typisk vigtige meddelelser, og du bør hurtigst muligt læse dem. Bekendtgørelser vises altid på toppen af alle sider i det forum hvor de er skrevet til. Om det er muligt for dig at skrive en bekendtgørelse afgøres udfra de tilladelser som du har, disse kan indstilles af administratoren.");
$faq[] = array("Hvad er Opslag?", "Opslag er indlæg som altid er lige under bekendtgørelserne, til forskel fra bekendtgørelserne vises opslag kun på den første side i et forum. De er ofte også temmelig vigtige, og du bør læse dem når du har mulighed for det. Lige som med bekendtgørelser er det forumets administrator der afgør om hvilke tilladelser der er nødvendige for at kunne skrive et opslag i et forum.");
$faq[] = array("Hvad er et låst Emne?", "Låste emner er sat således enten af en administrator eller af en redaktør. Du kan ikke svare på indlæg i sådan et emne, og evt. afstemninger vil ligeledes være slut. Emnet kan være blevet låst af forskellige årsager.");


$faq[] = array("--","Bruger Niveauer og Grupper");
$faq[] = array("Hvad er er Administratorer?", "Administratorer er folk som er tildelt det højeste trin af indstillings muligheder omkring alle forumer på hjemmesiden. Disse personer kan indstille alle mulige ting om forumerne, så som tilladelser, udelukkelse af bestemte brugere, tilføje bruger grupper eller redaktører, osv. De har også samme rettigheder som redaktører under alle forummer.");
$faq[] = array("Hvad er en Redaktør?", "Redaktører er bestemte personer (eller grupper af personer) Hvis job er at holde øje med at forumet køre som det skal. De har retten til at rette eller slette andres indlæg, låse et emne eller låse et emne op igen, flytte eller dele et emne i forumet som de er redaktører for. I almindelig hed er redaktørens opgave at forhindre at folk skriver indlæg som <i>ikke høre hjemme under emnet<i> eller hvis de skriver absurde eller andre aggressive ting.");
$faq[] = array("Hvad er bruger grupper?", "Bruger grupper er noget forumets administrator kan benytte kan indele brugerne i bestemte grupper. Hver bruger kan være medlem af flere grupper (Dette er anderledes fra mange andre forumer) Hver gruppe kan så tildeles forskellige tilladelser. Dette gør det nemmere for Administratoren at tildele flere brugere tilladelser til at være redaktører i et bestemt forum, eller til at give dem adgang til et privat forum, osv.");
$faq[] = array("Hvordan tilmelder jeg mig til en bruger gruppe?", "For et melde sig ind i en gruppe skal du klikke på linket <i>Grupper</i> øverst på siden (Dette kan afhænge lidt af hjemmesidens opbygning),Her findes en liste over alle definerede grupper, ikke alle grupper er såkaldte <i>Åbne grupper</i>, nogle er lukkede og andre kan oven i købet have egenskaben at skjule medlemmerne. Hvis gruppen er en åben gruppe kan du selv tilmelde dig ved at klikke dig frem. Gruppens redaktør skal senere godkende din tilmelding for at den er gyldig, Der kan ske at de skriver tilbage for at spørge hvorfor du ønsker at tilmelde dig gruppen. Plag ikke redaktøren hvis din ansøgning ikke bliver godkendt, De har nok deres grunde.");
$faq[] = array("Hvordan bliver jeg redaktør i en gruppe?", "Bruger grupper laves fra start af af forumets administrator, Det er også dem der tildeler forumernes redaktører. Hvis du er interesseret i at få lavet en bruger gruppe, skal du som det første kontakte administratoren, forsøg med at lægge en privat besked til dem.");


$faq[] = array("--","Private Beskeder");
$faq[] = array("Jeg kan ikke sende private beskeder!", "Der er 3 muligheder; du er ikke tilmeldt og/eller ikke logget ind, administratoren har slået private beskeder fra på dette forum eller administratoren har specifikt fjernet denne funktion fra dine valg. Hvis det er den sidste mulighed kan du spørge administratoren hvorfor dette er gjort.");
$faq[] = array("Jeg bliver ved med at få uønskede private beskeder!", "På nuværende tidspunkt er det ikke muligt at lave en liste over beskeder der skal ignoreres, denne vil blive tilført i en fremtidig version. Så indtil da, hvis du bliver ved med at modtage private beskeder fra en bestem person, kan du informere administratoren, de har muligheden for at lukke for bestemte brugeres mulighed for at sende private beskeder.");
$faq[] = array("Jeg har modtaget en email indeholdende spam, eller andet som jeg ikke ønsker fra en bruger på dette forum!", "Vi er meget kede af at høre dette. Dette forums email system, har indbygget visse sikkerhedsforanstaltninger som hjælper med til at finde sådanne brugere som sender den slags indhold. Du bør sende en kopi af mailen til dette forums administrator, der er meget vigtigt at denne indeholder den såkaldte header (Disse beskriver brugeren som sendte emailen).De vil så gøre hvad de kan for at undgå en lignende situation.");

//
// These entries should remain in all languages and for all modifications
//
$faq[] = array("--","phpBB 2 Spørgsmål");
$faq[] = array("Hvem har skrevet koden til dette forum?", "Koden til dette software (i rettet udgave) er fremstillet , frigivet og copyright <a href=\"http://www.phpbb.com/\" target=\"_blank\">phpBB Group</a>. Det er gjort tilgængeligt for alle og enhver under den såkaldte GNU General Public Licence og må fri distribueres, se evt. linket for flere detaljer");
$faq[] = array("Hvorfor er X funktioner ikke tilstede?", "Koden er skrevet og på licens af phpBB Gruppen. Hvis du mener der er en funktion der mangler, besøg de venligst phpbb.com hjemmeside for at se hvad phpBB gruppen har at sige til om det. Vær venlig ikke at benytte forumet på pgpbb.com, php gruppen benytter sourceforge til at håndtere nye tiltag. Læs venligst igennem hele forumet for at se hvad andre har skrevet, måske er vi allerede i gang, følg derefter de retnings linier der gives der.");
$faq[] = array("Hvem kontakter jeg vedr. misbrug og/eller lovligheden af ting skrevet i dette forum?", "Du bør kontakte administratoren af denne hjemmeside. Hvis du ikke kan finde ud af hvem dette måtte være, skal du forsøge at kontakte en af forumets redaktører for at høre hvem du bør kontakte. Hvis du stadig ikke er i stand til at finde ud af hvem administratoren er kan du forsøge at finde ud af hvem der ejer hjemmesidens navn (ved at lave en whois søgning) eller, hvis denne side køre under en af de mange gratis services såsom: yahoo, ofir.dk free.fr, f2s.com, osv., forsøg da at kontakte deres kundekontor eller misbrugs afdeling . Vær venlig ikke at kontakte phpBB Gruppen da vi absolut ingen kontrol har med indholdet at gøre, og kan ej heller holdes ansvarlige for hvordan, hvor eller af hvem dette forum bliver benyttet. Det er ganske bestem uden mening at kontakte php gruppen i forbindelse med evt. ulovligheder eller for at stoppe/ophøre uansvarlig og ærekrænkende udtalelser, osv. uanset at disse ikke har direkte forbindelse med phpbb.com hjemmeside eller funktionen af softwaren phpBB. Hvis du sender en mail til phpBB Gruppen angående en anden hjemmesides brug af denne software, kan du forvente et kort eller slet ingen svar.");

//
// This ends the FAQ entries
//

?>
