<?php
/***************************************************************************
 *                          lang_faq.php [turkish]
 *                            -------------------
 *   begin                : Wednesday Oct 3, 2001
 *   copyright            : (C) 2001 The phpBB Group
 *   email                : support@phpbb.com
 *
 *   $Id: lang_faq.php,v 1.4 2001/12/15 16:42:08 psotfx Exp $
 *
 *
 ***************************************************************************/

/***************************************************************************
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 ***************************************************************************/
//
// Translation by:
//
// Onur Turgay (postexitus)  :: onurturgay@isnet.net.tr :: http://welcome.to/aaal2000
// Erdem Corapcioglu (erdem) :: erdem@smtg.org         :: http://www.smtg.org
//
// For questions and comments use: onurturgay@isnet.net.tr
//

$faq[] = array("--","Giriþ ve Kayýt sorunlarý");

$faq[] = array("Neden giriþ yapamýyorum?", "Kayýt oldunuz mu? Giriþ yapabilmek için önceden kayýt olmanýz gerek. Yoksa mesaj panosundan banlandýnýz mý (o halde bu anlamda bir mesaj görmeniz gerekir)? Eðer öyleyse, site yöneticisiyle (webmaster) veya pano yöneticisiyle (administrator) irtibata geçip sebebini sorabilirsiniz. Eðer kayýt olduysanýz ve banlanmýþ olmamanýza raðmen giriþ yapamýyorsanýz, tekrar tekrar kullanýcý adýnýzý ve þifrenizi kontrol edin. Genelde hata burada oluyor. Sorun bu deðilse pano yöneticisiyle irtibata geçin, belki mesaj panosu için yanlýþ ayar yapmýþ olabilir.");
$faq[] = array("Neden kayýt olmam gerekiyor?", "Kayýt olmanýza gerek olmayabilirdi aslýnda. Mesaj gönderebilmek için kaydýn þart olmasý, pano yöneticisinin (administator) kararýna baðlý. Ayrýca kayýt olunca bazý özel imkanlara ulaþabilirsiniz. Örneðin mesajlarýnýzýn yanýnda kedinize ait küçük bir resim (avatar) gösterme, özel mesaj gönderme, tanýdýðýnýz kullanýcýlara mail gönderme veya kullanýcý gruplarýna katýlma imkanlarýna misafir kullanýcýlar sahip deðildir. Kayýt iþlemi çok basit olduðu için kaydolmanýz önerilir.");
$faq[] = array("Neden otomatik olarak çýkýþým yapýlýyor?", "Giriþ sayfasýnda gördüðünüz <i>Her zaman otomatik giriþ yap</i> komutunu seçmediðiniz sürece, mesaj panosu sizi sadece belirli bir süre için giriþ yapmýþ kabul eder. Böylece kaydýnýzýn baþkalarý tarafýndan kullanýlmasý önlenir. Giriþinizin devamlý kalmasý için, bu komutu seçmeniz yeterlidir. Fakat baþka þahýslarýnda kullandýðý (örn. herhangi bir kütüphaneye, internet cafeye, üniversiteye vs. ait) bir bilgisayardan giriþ yapýyorsanýz, bu komutu seçmemeniz önerilir.");
$faq[] = array("Kimler Online listesinde ismimin görülmesini nasýl önleyebilirim?", "Þahsýnýza ait profil sayfasýnda <i>Online olduðumu gizle</i> seçeneðini bulabilirsiniz. Buradan <i>Evet</i> 'i seçince online olduðunuzu sadece pano yöneticileri ve kendiniz görebilirsiniz. Bu durumda gizli kullanýcý olarak sayýlýrsýnýz.");
$faq[] = array("Þifremi unuttum!", "Telaþa kapýlmayýn! Eski þifrenizi öðrenmek mümkün olmasa bile, yerine deðiþik bir þifre alabilirsiniz. Giriþ sayfasýný açýp <u>Þifremi unuttum</u> üzerini týklayýn ve tarif edilen iþlemleri uygulayýn. Kýsa sürede tekrar online olduðunuzu göreceksiniz.");
$faq[] = array("Kayýt oldum ama giriþ yapamýyorum!", "Ýlk önce kullanýcý adýnýzý ve þifrenizi doðru yazdýðýnýzý temin edin. Doðru yazýlmýþsa, iki sebep daha olabilir. Eðer COPPA destekleniyorsa ve kaydýnýz esnasýnda <u>13 yaþýndan küçüðüm</u> linkini týkladýysanýz, tarif edilen iþlemleri uygulamanýz gerek. Sebep bu deðilse, kaydýnýzýn onaylanmasý gerekebilir. Bazý mesaj panolarý tüm yeni kayýtlarýn onaylanmasýný þart koþar. Giriþ yapabilmeniz için ya kendiniz yada pano yöneticisi tarafýndan kaydýnýz onaylanmalýdýr. Bu durumda onay gerekçesi, kaydýnýz esnasýnda size bildirilmiþ olmalý. Bu doðrultuda bir e-mail aldýysanýz, tarif edilen iþlemleri uygulamanýz gerek. Eðer böyle bir e-mail almadýysanýz, verdiðiniz e-mail adresinin doðru olup olmadýðýný kontrol edin. Onay gerekçesinin sebebi, <i>kötü amaçlý</i> kullanýcýlarýn anonim kalýp mesaj panosunu suiistimal etmelerini önlemektir. Verdiðiniz e-mail adresinin doðru olduðundan eminseniz, pano yöneticisiyle irtibata geçmeniz gerekir.");
$faq[] = array("Daha önceleri kayýtlýydým ama artýk giriþ yapamýyorum?!", "Bunun en olasý sebebi hatalý kullanýcý adý veya þifre giriþidir (kayýt olduktan sonra aldýðýnýz e-maile bakýp kontrol edin). Belkide pano yöneticisi kaydýnýzý herhangi bir sebepten dolayý silmiþ olabilir. Panoya hiç mesaj gönderdinizmi? Veritabanýnýn kapladýðý alaný küçük tutmak için, mesaj göndermeyen kullanýcýlarýn kaydý genelde belirli bir süre sonra silinir. Tekrar kaydolmayý deneyin ve tartýþmalara katýlýn.");

$faq[] = array("--","Kullanýcý Seçenekleri ve Ayarlarý");
$faq[] = array("Kullanýcý ayarlarýmý nasýl deðiþtirebilirim?", "Eðer kaydolduysanýz bütün ayarlarýnýz veritabanýna kaydedilir. Ayarlarýnýzý deðiþtirmek için (genelde sayfalarýn üst kýsmýnda bulunan) <u>Profil</u> linkini týklayýn. Ayarlarýnýz buradan deðiþtirilir.");
$faq[] = array("Gösterilen saatler yanlýþ!", "Gösterilen saatler büyük bir ihtimalle doðrudur. Fakat gördüðünüz saat, bulunduðunuz yerin saat diliminden farklý olabilir. Bu durumda, <u>Profil</u> linkini týklayýp kendiniz için geçerli saat dilimini seçmeniz gerekir, örn. London, Paris, New York, Sydney vs. Çoðu seçenekler için geçerli olduðu gibi, saat dilimini deðiþtirme imkanýda sadece kayýtlý kullanýcýlara verilmiþtir. Eðer kayýtlý deðilseniz, kaydolmanýn tam zamaný (kelime oyununu baðýþlayýn)!");
$faq[] = array("Deðiþik bir zaman dilimi seçtim ama saatler hala yanlýþ!", "Doðru zaman dilimini seçtiðinizden eminseniz ve saat hala yanlýþ gösteriliyorsa, bunun en olasý sebebi günýþýðýndan yararlanma deðiþimleri olabilir. Örn. yaz aylarýnda görülen saatler, bulunduðunuz ülkenin gerçek saatinden bir saat ileri veya geri olabilir. Mesaj panosu bu deðiþimleri dikkate almaz.");
$faq[] = array("Konuþtuðum lisan listede yok!", "Bunun en olasý sebepleri, ya pano yöneticisinin konuþtuðunuz lisaný destekleyen uzantýyý kurmuþ olmayýþý, yada bu panonun konuþtuðunuz lisana henüz çevrilmiþ olmayýþýdýr. Pano yöneticilerine baþvurup, kendi lisanýnýzý destekleyen uzantýyý kurmalarýný rica edin. Eðer böyle bir uzantý yoksa, panoyu kendi dilinize çevirmekte özgürsünüz. Bu konuda daha geniþ bilgi için sayfalarýn alt kýsmýnda görülen phpBB Group linkini týklayýn.");
$faq[] = array("Ýsmimin altýnda resim (avatar) göstermek için ne yapmalýyým?", "Mesajlarýn görüntülendiði sayfalarda kullanýcý adlarýnýn altýnda iki tür resim görebilirsiniz. Birincisi, kullanýcý derecenizi gösterir ve genelde gönderdiðiniz mesaj sayýsýna baðlý olarak belirli bir sayýda yýldýz veya kare þeklindedir. Bunun altýnda avatar denen biraz daha büyük bir resim görebilirsiniz. Bu resim genelde kullanýcýya ait ve özeldir. Avatar kullanma imkanýný pano yöneticisi saptar. Ayrýca avatar'larýn ne þekilde kullanýlabileceðinide saptar. Avatar kullanamýyorsanýz, pano yöneticisine baþvurup bu imkaný ne sebepten iptal ettiðini öðrenebilirsiniz (bunun önemli bir sebebi olduðundan eminiz!)");
$faq[] = array("Kullanýcý derecemi nasýl deðiþtirebilirim?", "Genelde kullanýcý derecenizi doðrudan deðiþtirmeniz mümkün deðil (kullanýcý derecesi, gönderdiðiniz mesajýn yanýnda bulunan isminizin altýnda ve kullanýcý profili sayfasýnda görülür). Çoðu mesaj panosunda kullanýcý dereceleri, gönderilen mesajlarýn sayýsýný veya yetkili üyeleri belirlemek için kullanýlýr, örn. yöneticiler veya pano yöneticileri özel bir dereceye sahip olabilir. Lütfen gereksiz yere mesaj gönderipte derecenizi yükseltmeye çalýþmayýn, elde edeceðiniz tek sonuç, yöneticilerin mesajlarýnýzýn sayýsýný düþürmesi olacaktýr.");
$faq[] = array("Bir kullanýcýnýn mail linkini týklayýnca giriþ yapmam isteniyor?", "Panoya ait e-mail formuyla maalesef sadece kayýtlý kullanýcýlar mail gönderebiliyor (ayrýca yöneticinin bu iþlevi çalýþtýrmasý gerek). Bunun sebebi, e-mail sisteminin anonim kullanýcýlar tarafýndan suiistimal edilmesini önlemektir.");

$faq[] = array("--","Mesaj Gönderme");
$faq[] = array("Foruma yeni baþlýk nasýl gönderilir?", "Çok basit: forumu veya baþlýðý görüntüleme sayfasýnda <i>Yeni Baþlýk Gönder</i> düðmesini týklayýn. Yeni mesaj göndermeden önce kayýt olmanýz gerekebilir. Forum ve baþlýk sayfalarýnýn alt kýsmýnda yapabileceðiniz bütün iþlemlerin listesini görebilirsiniz (örn. <i>Bu forumda yeni konular açabilirsiniz</i> vs. gibi).");
$faq[] = array("Mesajlar nasýl deðiþtirilir veya silinir?", "Pano yöneticisi veya forum yöneticisi olmadýðýnýz sürece, sadece kendinize ait mesajlarý deðiþtirebilir veya silebilirsiniz. Gönderdiðiniz bir mesajý <i>Mesajý Deðiþtir</i> düðmesini týklayarak deðiþtirebilirsiniz (bu imkan bazen sadece belirli bir süre için mevcuttur). Mesajýnýza birileri cevap göndermiþse eðer, mesajýnýzýn altýnda metni kaç defa deðiþtirdiðinizi gösteren kýsa bir yazý göreceksiniz. Mesajýnýz henüz yanýtlanmamýþsa, bu not görülmez. Ayrýca mesajýnýz pano yöneticileri veya forum yöneticileri tarafýndan deðiþtirilincede bu yazý görülmez (yöneticilerin böyle bir durumda metnin hangi kýsmýný ne sebepten dolayý deðiþtirdiklerini yazmalarý önerilir). Bir mesaja cevap geldikten sonra normal kullanýcýlar tarafýndan silinemez.");
$faq[] = array("Mesaj altýna imza nasýl eklenir?", "Herhangi bir mesaja imzanýzý ekleyebilmek için önce <i>Profil</i> sayfanýza girip bir imza hazýrlamanýz gerek. Daha sonra mesaj gönderme formunun alt kýsmýndaki <i>Ýmzamý ekle</i> seçeneðini seçip mesajýnýza imzanýzý ekleyebilirsiniz. Gönderdiðiniz bütün mesajlara genel bir ayar olarak imzanýzýn eklenmesini istiyorsanýz, <i>Profil</i> sayfasýndaki seçeneði týklayýn. Buna raðmen dilediðiniz her mesaj için imzanýzýn eklenmesini önleyebilirsiniz (mesaj gönderme formunda <i>Ýmzamý Ekle</i> seçeneðini silmeniz yeterli).");
$faq[] = array("Anket nasýl hazýrlanýr?", "Anket hazýrlamak çok basit: yeni bir baþlýk gönderirken (veya bir baþlýðýn ilk mesajýný deðiþtirirken - bu tabi yetkinize baðlý), mesaj gönderme formunun altýnda <i>Anket Ekle</i> formunu göreceksiniz (böyle bir formu göremiyorsanýz, anket ekleme yetkiniz yok demektir). Anket sorusunu ve en az iki tane anket þýkký eklemeniz gerekir. Anket þýkký eklemek için <i>Bu Þýkký Ekle</i> düðmesini týklayýn. Ayrýca anketin gösterim süresinide belirleyebilirsiniz, 0 süresiz demektir. Eklenebilecek anket þýklarýnýn sayýsý sýnýrlýdýr. Bu sýnýrý pano yöneticisi belirler.");
$faq[] = array("Bir anket nasýl deðiþtirilir veya silinir?", "Anketlerde mesajlar gibi sadece gönderen kullanýcý, forum yöneticisi veya pano yöneticisi tarafýndan deðiþtirilebilir. Bir anketi deðiþtirmek için, baþlýðýn ilk mesajýný týklayýn (ilgili anket daima bu mesaja baðlýdýr). Ankete henüz katýlan olmadýysa, hazýrlayan kullanýcý tarafýndan deðiþtirilebilir veya silinebilir. Ankete katýlan olmuþsa, sadece forum ve pano yöneticileri tarafýndan deðiþtirilebilir veya silinebilir. Böylece bir süre sonra þýklarý deðiþtirip anket sonuçlarýný sapýtma olanaðý kalmaz.");
$faq[] = array("Anketlere neden katýlamýyorum?", "Anketlere sadece kayýtlý kullanýcýlar katýlabilir (böylece hile yapma olanaðý önlenmiþ olur). Eðer kayýt olmanýza raðmen anketlere katýlamýyorsanýz, gerekli yetkilere sahip deðilsiniz demektir.");
$faq[] = array("Bazý forumlara neden ulaþamýyorum?", "Bazý forumlar sadece belirli kullanýcýlara veya kullanýcý gruplarýna açýk olabilir. Mesajlarý okumak, görüntülemek, göndermek için vs. özel yetki gerekebilir. Bu yetkiyi sadece ilgili forum yöneticisi veya pano yöneticisi verebilir, bu kiþilere baþvurmalýsýnýz.");

$faq[] = array("--","Biçimlendirme ve Baþlýk Tipleri");
$faq[] = array("BBCode nedir?", "BBCode HTML'in özel bir uygulamasýdýr. Forum'a yazdýðýnýz mesajlarda BBCode kullanabilme imkanýný pano yöneticisi saptar. Ayrýca mesaj gönderme formundaki seçenekler sayesinde dilediðiniz mesajlarda BBCode'ý iptal etmeniz mümkündür. BBCode, HTML'e benzer tarzdadýr fakat tag'ler &lt; ve &gt; yerine köþeli parantez içine alýnýr: [ ve ]. Ayrýca nelerin nasýl görüntülendiði daha iyi kontrol edilebilir. BBCode hakkýnda daha geniþ bilgiler için, mesaj gönderme sayfasýndan ulaþabileceðiniz rehbere bakýnýz.");
$faq[] = array("HTML kullanabilir miyim?", "Pano yöneticisinin müsaade vermesine baðlýdýr, ilgili ayarlarýn tümünü o kontrol eder. Eðer müsaade verilmiþse, büyük ihtimalle sadece bazý tag'lerin çalýþtýðýný göreceksiniz. Böyle olmasý <i>güvenlik</i> içindir. Amaç, pano görüntüsünün bozulmasýný veya daha deðiþik sorunlarýn meydana gelmesini önlemektir. Müsaade verilmiþ olsa bile, mesaj gönderme formundaki seçenekler sayesinde dilediðiniz mesajlarda HTML'i iptal etmeniz mümkündür.");
$faq[] = array("Smiley nedir?", "Smiley veya Emoticon, belirli duygu ifadelerini vermek için kullanýlan iþaretlerdir. Metinde küçük resimler halinde görüntülenir. Örn. :) mutlu, :( ise üzgün anlamýndadýr. Kullanabileceðiniz smileylerin listesini mesaj gönderme formunda görebilirsiniz. Smileyleri aþýrý derecede kullanmamaya özen gösterin, metin yoksa okunmaz hale gelebilir. Bu durumda yönetici smileyleri veya mesajýnýzý tamamýyla silmeye karar verebilir.");
$faq[] = array("Resim gönderebilir miyim?", "Gönderdiðiniz mesajla beraber resimde görüntülenebilir. Fakat þu anda panoya doðrudan resim göndermek mümkün deðildir. Bu yüzden umuma açýk bir web serverinde kayýtlý bir resme link vermeniz gerek, örn. http://www.umuma-acik-server.net/resim.gif. Kendi bilgisayarýnýzda bulunan bir resme link vermeniz mümkün deðil (bilgisayarýnýz umuma açýk bir web serveri olmadýðý sürece). Ayrýca, umuma açýk olmayan ve sadece þifreyle ulaþýlan resimlere link vermek mümkün deðildir (örn. hotmail veya yahoo mailboxlarýnda vs. kayýtlý resimler). Resim görüntülemek için, BBCode'ýn [img] tag'ini yada (müsaade verilmiþse) HTML kullanabilirsiniz.");
$faq[] = array("Duyuru nedir?", "Duyurular çoðu zaman önemli bilgileri içerir, en kýsa zamanda okumanýzý öneririz. Duyurular, ilgili forumun her sayfasýnýn baþýnda görülür. Duyuru gönderebilmeniz için bu yetkiye sahip olmanýz gerek. Yetkilerinizi ise pano yöneticisi saptar.");
$faq[] = array("Sabit baþlýklar nedir?", "Sabit baþlýklar, ilgili forumun ilk sayfasýnda, duyurularýn hemen altýnda görülür. Çoðu zaman önemli bilgileri içerirler, mümkünse okumanýzý öneririz. Duyurular için geçerli olduðu gibi, herhangi bir foruma sabit baþlýk göndermek için gereken yetkileri pano yöneticisi saptar.");
$faq[] = array("Kilitli baþlýklar nedir?", "Bu baþlýklarý forum yöneticisi veya pano yöneticisi kilitler. Kilitli baþlýklarý yanýtlamak mümkün deðildir, içerdikleri anketler otomatik olarak sona erir. Baþlýklar birçok nedenlerden dolayý kilitlenmiþ olabilir.");

$faq[] = array("--","Kullanýcý Seviyeleri ve Gruplarý");
$faq[] = array("Pano yöneticileri (administrator) nedir?", "Pano yöneticileri, panonun her bölümünde en çok yetkiye sahip olan þahýslardýr. Bu kiþiler, panonun hertürlü iþlevini kontrol edebilir: müsaade verme, yetkilendirme, kullanýcý banlama, kullanýcý gruplarý yaratma, forum yöneticisi (moderator) yetkilerini verme vs. Ayrýca bütün forumlarda forum yöneticisi (moderator) yetkilerine sahiptirler.");
$faq[] = array("Forum yöneticileri (moderator) nedir?", "Forum yöneticileri, günlük olarak forumun çalýþmasýný kontrol eden þahýslar veya gruplardýr. Baþlýklarý deðiþtirme ve silme yetkisine sahiptirler. Ayrýca yönettikleri forumdaki baþlýklarý kilitleyebilir, taþýyabilir, silebilir ve bölebilirler. Genelde forum yöneticilerinin görevi, <i>off-topic</i>, yani baþlýk konusuyla ilgisi olmayan yanýtlarýn veya hakaret ve saldýrý niteliðinde metinlerin gönderilmesini önlemektir.");
$faq[] = array("Kullanýcý gruplarý nedir?", "Kullanýcý gruplarý, pano yöneticilerinin kullanýcýlarý grup halinde ayýrabilmesi için öngörülen bir yöntemdir. Her kullanýcý (çoðu panolardan farklý olarak) birçok gruba üye olabilir. Bu þekilde pano yöneticileri belirli kullanýcýlara rahatlýkla forum yöneticisi yetkilerini veya özel forumlara ulaþma yetkisini vs. verebilir.");
$faq[] = array("Bir kullanýcý grubuna nasýl üye olabilirim?", "Bir kullanýcý grubuna üye olmak için, sayfa baþýndaki kullanýcý gruplarý linkini týklayýn. Kullanýcý gruplarýnýn listesini göreceksiniz. Gruplarýn tümü <i>eriþime açýk</i> olmayabilir, bazýlarý kilitli veya gizli olabilir. Pano açýk ise, ilgili düðmeyi týklayarak üye olmak için istekte bulunabilirsiniz. Ýsteðinizin kullanýcý grubu yöneticisi tarafýndan onaylanmasý gerek, örneðin isteðinizin nedenini sorabilir. Ýsteðiniz reddedilirse grup yöneticisini lütfen rahatsýz etmeyin, bunun nedenleri olsa gerek.");
$faq[] = array("Bir kullanýcý grubunun yöneticisi olmak için ne yapmam gerek?", "Kullanýcý gruplarý pano yöneticisi tarafýndan açýlýr. Pano yöneticisi ayný zamanda her grubun yöneticisini saptar. Eðer yeni bir kullanýcý grubu açmak istiyorsanýz, ilk önce pano yöneticisiyle irtibata geçmeniz gerek, kendisine özel mesaj göndermeyi deneyin.");

$faq[] = array("--","Özel Mesajlar");
$faq[] = array("Özel mesaj gönderemiyorum!", "Bunun üç sebebi olabilir: henüz kayýt olmamýþ veya giriþ yapmamýþsýnýz, veya pano yöneticisi bütün pano için özel mesajlarý iptal etmiþ. Üçüncü olanak ise: pano yöneticisi sizin bu imkaný kullanmanýzý önlemiþ olabilir, bu durumda kendisine nedenini sormanýz gerekir.");
$faq[] = array("Ýstemediðim özel mesajlarý almaya devam ediyorum!", "Ýleride özel mesajlar sistemine belirli kiþilerden gelen mesajlarý iptal etme imkanýný ekleyeceðiz. Þimdilik herhangi bir þahýstan istemediðiniz özel mesajlar alýyorsanýz, pano yöneticisine baþvurun. O herhangi bir kullanýcýyý özel mesaj göndermekten men edebilir.");
$faq[] = array("Bu mesaj panosuna kayýtlý birinden spam mail aldým!", "Üzgünüz. Aslýnda bu panonun sunduðu email gönderme iþlevi bundan korunmak için birçok önlemi almýþ bulunuyor. Aldýðýnýz spam mailinin bir kopyasýný pano yöneticisine gönderin. Özellikle aldýðýnýz emailin baþlýk kýsmýný (to (kime), subject (konu) vs.) iletmeyi unutmayýn, bu kýsýmda emaili gönderen kullanýcý hakkýnda bilgiler bulunur. Pano yöneticisi bu bilgilerle meseleyi takip edebilir.");

//
// These entries should remain in all languages and for all modifications
//
$faq[] = array("--","phpBB 2'yle ilgili Konular");
$faq[] = array("Bu mesaj panosunu kim yazdý?", "Bu yazýlým (deðiþtirilmemiþ haliyle) <a href=\"http://www.phpbb.com/\" target=\"_blank\">phpBB Group</a> tarafýndan üretilmiþ ve genel daðýtýma çýkarýlmýþtýr. Tüm eser haklarý phpBB Group'a aittir. Bu eser, GNU General Public Licence antlaþmasýna uygun olarak eriþime açýlmýþtýr. Bu antlaþmaya uyma þartýyla ücretsiz daðýtýlabilir. Daha detaylý bilgiler için üstteki linki týklayýn.");
$faq[] = array("Aradýðým ... özellik neden yok?", "Bu yazýlým phpBB Group tarafýndan yazýlmýþ ve daðýtýma çýkarýlmýþtýr. Eðer herhangi bir özelliðin eksik olduðunu düþünüyorsanýz, lütfen phpbb.com sitesini ziyaret edip phpBB Group'un ilgili düþüncelerini öðrenin. Lütfen phpbb.com sitesindeki panoya yazýp yeni bir özellik isteðinde bulunmayýn. phpbb Group sourceforge aracýlýðýyla yeni özellikler ekler. Lütfen ilgili forumlarý gezip ilk önce phpBB Group'un herhangi bir özellikle ilgili tutumunu öðrenin ve daha sonra burada tarif edilen yöntemle baþvuruda bulunun.");
$faq[] = array("Bu panoyla ilgili hukuki sorunlar için veya suiistimal durumunda kime baþvurabilirim?", "Pano yöneticisine baþvurmanýz önerilir. Pano yöneticisinin kim olduðunu öðrenemezseniz, ilk önce forum yöneticilerinden biriyle irtibata geçip, kime yazmanýz gerektiðini öðrenin. Herhangi bir yanýt alamadýðýnýz takdirde, site sahibine baþvurun (whois aramasýyla sitenin sahibini öðrenebilirsiniz) veya (eðer pano ücretsiz hizmet veren sitelerde çalýþtýrýlýyorsa, örn. yahoo, free.fr, f2s.com vs.) sitenin yönetimine veya suiistimal konularýyla ilgilenen þubesine baþvurun. phpBB Group'un bu panonun nasýl, nerede ve kimler tarafýndan çalýþtýrýldýðýný kontrol etmediðini ve herhangi bir þekilde bundan sorumlu olmadýðýný lütfen dikkate alýn. phpbb.com sitesiyle veya phpBB yazýlýmýyla doðrudan ilgisi olmayan herhangi bir hukuki konuda (ihtiyati tedbir, mali sorumluluk, iftira vs.) phpBB Group'la irtibata geçmek tamamen anlamsýzdýr. Bu yazýlýmýn herhangi üçüncü þahýslar tarafýndan kullanýmýyla ilgili phpBB Group'a e-mail yazarsanýz, çok kýsa yada hiç cevap almamayý beklemeniz gerek.");

//
// This ends the FAQ entries
//

?>