services:
    installer.install_database.create_schema_file:
        class: phpbb\install\module\install_database\task\create_schema_file
        arguments:
            - '@installer.helper.config'
            - '@installer.helper.database'
            - '@filesystem'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%finder.cache%'
        tags:
            - { name: install_database_install, order: 1 }

    installer.install_database.set_up_database:
        class: phpbb\install\module\install_database\task\set_up_database
        arguments:
            - '@installer.helper.config'
            - '@installer.helper.database'
            - '@filesystem'
            - '@installer.helper.iohandler'
            - '%core.root_path%'
        tags:
            - { name: install_database_install, order: 2 }

    installer.install_database.add_tables:
        class: phpbb\install\module\install_database\task\add_tables
        arguments:
            - '@installer.helper.config'
            - '@installer.helper.database'
            - '%core.root_path%'
        tags:
            - { name: install_database_install, order: 3 }

    installer.install_database.add_default_data:
        class: phpbb\install\module\install_database\task\add_default_data
        arguments:
            - '@installer.helper.database'
            - '@installer.helper.config'
            - '@installer.helper.iohandler'
            - '@language'
            - '%core.root_path%'
        tags:
            - { name: install_database_install, order: 4 }

    installer.install_database.add_config_settings:
        class: phpbb\install\module\install_database\task\add_config_settings
        arguments:
            - '@installer.helper.database'
            - '@filesystem'
            - '@installer.helper.config'
            - '@installer.helper.iohandler'
            - '@installer.helper.container_factory'
            - '@language'
            - '%core.root_path%'
        tags:
            - { name: install_database_install, order: 5 }

    installer.install_database.update_user_and_post_data:
        class: phpbb\install\module\install_database\task\update_user_and_post_data
        arguments:
            - '@installer.helper.config'
            - '@installer.helper.container_factory'
            - '@installer.helper.database'
            - '@installer.helper.iohandler'
            - '@language'
        tags:
            - { name: install_database_install, order: 6 }

    installer.module.install_database_collection:
        class: phpbb\di\ordered_service_collection
        arguments:
            - '@service_container'
        tags:
            - { name: service_collection, tag: install_database_install, class_name_aware: true }

    installer.module.database_install:
        class: phpbb\install\module\install_database\module
        parent: installer.module_base
        arguments:
            - '@installer.module.install_database_collection'
        tags:
            - { name: installer_install_module, order: 4 }
