services:
    installer.update_database.update_task:
        class: phpbb\install\module\update_database\task\update
        arguments:
            - '@installer.helper.container_factory'
            - '@filesystem'
            - '@installer.helper.config'
            - '@installer.helper.iohandler'
            - '@language'
            - '%core.root_path%'
        tags:
            - { name: update_database_task, order: 10 }

    installer.module.update_database_collection:
        class: phpbb\di\ordered_service_collection
        arguments:
            - '@service_container'
        tags:
            - { name: service_collection, tag: update_database_task, class_name_aware: true }

    installer.module.update_database:
        class: phpbb\install\module\update_database\module
        parent: installer.module_base
        arguments:
            - '@installer.module.update_database_collection'
            - true
            - false
        tags:
            - { name: installer_update_module, order: 40 }
