services:
    installer.install_finish.populate_migrations:
        class: phpbb\install\module\install_finish\task\populate_migrations
        arguments:
            - '@installer.helper.config'
            - '@installer.helper.container_factory'
        tags:
            - { name: install_finish, order: 1 }

    installer.install_finish.install_extensions:
        class: phpbb\install\module\install_finish\task\install_extensions
        arguments:
            - '@installer.helper.container_factory'
            - '@installer.helper.config'
            - '@installer.helper.database'
            - '@installer.helper.iohandler'
        tags:
            - { name: install_finish, order: 2 }

    installer.install_finish.notify_user:
        class: phpbb\install\module\install_finish\task\notify_user
        arguments:
            - '@installer.helper.container_factory'
            - '@installer.helper.config'
            - '@installer.helper.iohandler'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: install_finish, order: 3 }

    installer.module.install_finish_collection:
        class: phpbb\di\ordered_service_collection
        arguments:
            - '@service_container'
        tags:
            - { name: service_collection, tag: install_finish, class_name_aware: true }

    installer.module.finish_install:
        class: phpbb\install\module\install_finish\module
        parent: installer.module_base
        arguments:
            - '@installer.module.install_finish_collection'
        tags:
            - { name: installer_install_module, order: 6 }
