<?php
/***************************************************************************
 *                          lang_faq.php [românã cu diacritice]
 *                            -------------------
 *   begin                : Wednesday Aug 7, 2002
 *   copyright 1          : (C) Robert Munteanu
 *   copyright 2          : (C) Bogdan Toma
 *   email     1          : rombert@go.ro
 *   email     2          : bog_tom@yahoo.com
 *
 *   $Id$
 *
 *
 ***************************************************************************/

/***************************************************************************
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 ***************************************************************************/
 
// 
// To add an entry to your FAQ simply add a line to this file in this format:
// $faq[] = array("question", "answer");
// If you want to separate a section enter $faq[] = array("--","Block heading goes here if wanted");
// Links will be created automatically
//
// DO NOT forget the ; at the end of the line.
// Do NOT put double quotes (") in your FAQ entries, if you absolutely must then escape them ie. \"something\"
//
// The FAQ items will appear on the FAQ page in the same order they are listed in this file
//
 
  
$faq[] = array("--","Probleme de autentificare ºi înregistrare");
$faq[] = array("De ce nu mã pot autentifica?", "V-aþi înregistrat? Serios vorbind, trebuie sã vã înregistraþi pentru a vã autentifica. Aþi fost exclus de pe site (un mesaj vã apare pentru a vã indica acest lucru) ? Dacã da, ar trebui sã contactaþi adminstratorul site-ului sau forumului pentru a afla motivul. Dacã sunteþi înregistrat ºi nu sunteþi exclus ºi tot nu vã puteþi autentifica, atunci verificaþi foarte bine numele de utilizator ºi parola. De obicei, aceasta este problema. Dacã nici aceasta nu este soluþia, luaþi legãtura cu administratorul forumului pentru cã forumul ar putea fi incorect configurat.");
$faq[] = array("De ce trebuie sã mã înregistrez?", "S-ar putea sã nu fie nevoie, depinde de adminstratorul forumului dacã e nevoie sã vã înregistraþi sau nu. Oricum, înregistrarea vã va oferi acces la opþiuni care nu sunt disponibile utilizatorilor anonimi cum ar fi imagini asociate, mesaje private, trimiterea de email-uri altor utilizatori, înscrierea în grupuri  etc. Dureazã doar câteva momente sã vã înregistraþi , aºa cã vã recomandãm sã vã înregistraþi.");
$faq[] = array("De ce sunt scos afarã din forum automat?", "Dacã nu activaþi opþiunea <i>Autentificã-mã automat la fiecare vizitã</i>, atunci când vã autentificaþi veþi fi autentificat doar pentru o perioadã prestabilitã. Aceastã mãsurã previne ca cineva sã se foloseascã de contul dumneavoastrã. Pentru a rãmâne autentificat, bifaþi aceastã opþiune la autentificare, dar acest lucru nu este recomandat dacã accesaþi forumul de la un calculator utilizat de mai multe persoane, cum ar fi de la o bibliotecã, cafenea internet, facultate etc");
$faq[] = array("Cum fac sã nu îmi aparã numele de utilizator pe listele de utilizatori conectaþi?", "În profilul dumneavoastrã veþi gãsi o opþiune <i>Ascundeþi indicatorul de conectare</i>, ºi dacã veþi seta aceastã opþiune pe <i>Da</i> veþi fi vizibil doar pentru administratori ºi pentru dumneavoastrã. Veþi fi numãrat ca utilizator ascuns.");
$faq[] = array("Mi-am pierdut parola!", "Nu intraþi în panicã! Parola dumneavoastrã nu poate fi refãcutã, dar poate fi resetatã. Pentru a realiza acest lucru, mergeþi la pagina de autentificare ºi folosiþi legãtura <i>Mi-am uitat parola</i>, urmaþi instrucþiunile ºi ar trebui sã puteþi sã vã autentificaþi în scurt timp.");
$faq[] = array("Sunt înregistrat dar nu mã pot autentifica!", "Mai intâi verificaþi dacã aþi introdus numele de utilizator ºi parola corect. Dacã sunt corecte, atunci fie, dacã este activatã opþiunea COPPA ºi aþi dat bifat <i>Sunt de acord cu aceste condiþii ºi declar cã am sub 13 ani</i> la înregistrare, va trebui sã urmaþi instrucþiunile primite, fie contul dumneavoastrã trebuie sã fie activat. Unele forumuri obligã ca toþi utilizatori noi sã îºi activeze conturile , fie cãtre dumneavoastrã personal, fie de cãtre administrator înainte de a vã puteþi autentifica. Când v-aþi înregistrat aþi fi aflat dacã este necesarã activarea. Dacã aþi primit un email atunci urmaþi instrucþiunile. Dacã nu, sunteþi sigur cã aþi specificat corect adresa de mail ? Unul din motivele pentru care activarea este folositã este pentru a preveni abuzul de cãtre utilizatori <i>pirat</i> anonimi. Daca sunteþi sigur cã adresa de mail folositã este corectã atunci încercaþi sã contactaþi administratorul.");
$faq[] = array("M-am înregistrat cu ceva timp în urmã dar nu mã mai pot autentifica?!", "Cele mai probabile motive sunt: aþi folosit un nume de utilizator inexistent sau o parolã greºitã (verificaþi-vã email-ul pe care l-aþi primit când v-aþi înregistrat) sau administratorul a ºters contul dumneavoastrã dintr-un motiv sau altul. Dacã motivul este al doilea, atunci poate nu aþi scris nici un mesaj ? Se obiºnuieºte ca forumurile sã excludã periodic utilizatorii care nu au scris nimic pentru a reduce mãrimea bazei de date. Încercaþi sã vã înregistraþi din nou ºi sã vã implicaþi în discuþii.");


$faq[] = array("--","Preferinþe ºi setãri");
$faq[] = array("Cum îmi schimb setãrile?", "Toate setãrile dumneavoastrã (dacã sunteþi înregistrat) sunt stocate în baza de date. Pentru a le schimba folosiþi legãtura <i>Profil</i> (în general afiºatã în partea superioarã a paginilor dar nu întotdeauna). Acest lucru vã va permite sã vã schimbaþi toate setãrile.");
$faq[] = array("Orele nu sunt corecte!", "Orele sunt aproape sigur corecte, dar ceea ce dumneavoastrã s-ar putea sã vedeþi cã toate orele afiºate sunt într-o zonã cu fus orar diferit faþã de cea în care sunteþi. Dacã este aºa, ar trebui sã vã schimbaþi setarea din profil pentru zona de fus orar în care sunteþi, cum ar fi Bucureºti, Londra, Paris, etc. Vã rugãm, sã observaþi cã schimbarea zonei de fus orar, ca majoritatea setãrilor, poate fi fãcutã doar de utilizatorii înregistraþi. Deci dacã nu sunteþi înregistrat, acesta este un moment bun sã o faceþi, dacã îmi permiteþi jocul de cuvinte!");
$faq[] = array("Am schimbat zona de fus orar ºi ora tot este greºita!", "Dacã sunteþi sigur cã aþi setat zona de fus orar corect ºi ora înca este diferitã, cel mai probabil rãspuns este ora de varã. Programul nu a fost gândit sã se plieze dupã schimbãrile fãcute între ora standard ºi cea de varã aºa cã în timpul lunilor de varã ora poate fi diferitã cu 60 de minute faþã de cea localã realã.");
$faq[] = array("Limba mea nu este în listã!", "Cele mai probabile motive sunt fie cã administratorul nu a instalat limba dumneavoastrã sau cã cineva nu a tradus înca acest program în limba dumneavoastrã. Încercaþi sã îl întrebaþi pe administrator dacã poate instala limba de care aveþi nevoie ºi dacã nu existã, atunci sunteþi liber sã creaþi o nouã traducere. Mai multe informaþii pot si gasite pe site-ul grupului phpBB. Urmãriþi legãtura din partea inferioarã  paginilor)");
$faq[] = array("Cum pot afiºa o imagine sub numele meu de utilizator?", "Pot fi douã imagini sub numele de utilizator când vizualizaþi mesajele. Prima este o imagine asociata cu rangul dumneavoastrã, în general acestea luând forma de stele sau blocuri indicând câte mesaje aþi scris sau statutul dumneavoastrã pe forumuri. Sub aceasta ar putea fi o imagine mai mare cunoscutã sub numele de <i>avatar</i> (imagine asociatã). Aceasta este, în general, unicã sau personalã fiecãrui utilizator. Administratorul decide dacã sã activeze imaginile asociate ºi au posibilitatea de a alege modalitatea prin care imaginile asociate pot fi folosite. Dacã nu puteþi folosi imaginile asociate, atunci aceasta este decizia administratorului ºi ar trebui sã-l întrebaþi pe acesta despre motivele care au dus la aceastã decizie (suntem siguri cã vor fi întemeiate!)");
$faq[] = array("Cum îmi schimb rangul?", "În general nu puteþi schimba direct rangurile (rangul apare direct sub numele dumneavoastrã de utilizator, în mesaje ºi în profilul dumneavoastrã, depinde de stilul folosit). Majoritatea forumurilor folosesc rangurile pentru a indica numãrul de mesaje pe care le-aþi scris ºi pentru a identifica anumiþi utilizatori, cum ar fi moderatorii ºi administratorii. Vã rugãm, sã nu abuzaþi de forum scriind mesaje inutile doar pentru a vã creºte rangul, pentru cã probabil veþi descoperi ca moderatorul sau administratorul vã va scãdea pur ºi simplu numãrul de mesaje scrise.");
$faq[] = array("De ce când folosesc legãtura de email al unui utilizator îmi cere sã mã autentific?", "Doar utilizatorii înregistraþi pot trimite mesaje altor utilizatori prin formularul încorporat de mail (dacã administratorul permite acest lucru). Acest lucru se întamplã pentru a preveni folosirea maliþioasa a sistemului de mesagerie de cãtre utilizatorii anonimi.");


$faq[] = array("--","Probleme de scriere/publicare a mesajelor");
$faq[] = array("Cum deschid un subiect în forum?", "Simplu. Apasaþi pe butonul specific, fie din forum, fie pe ecranul cu subiecte. Este posibil sã fie nevoie sã vã înregistraþi înainte de a scrie un mesaj. Facilitãþile care vã sunt disponibile sunt trecute în partea de jos a ecranului (de genul <i>Puteþi crea un subiect nou în acest forum</i> )");
$faq[] = array("Cum pot modifica sau ºterge un mesaj?", "În afara cazului în care sunteþi administratorul forumului sau moderatorul, puteþi modifica sau ºterge doar mesajele dumneavoastrã. Puteþi modifica un mesaj (uneori doar pentru o scurta perioadã dupã publicare) apãsând butonul <i>modificã</i> pentru mesajul respectiv. Veþi observa o micã secþiune de text sub mesaj când reveniþi la subiect. Aceasta aratã de cate ori l-aþi modificat. Aceasta va apãrea doar dacã nimeni nu v-a rãspuns. De asemenea, nu va apãrea dacã moderatorii sau administratorii modificã mesajul (aceºtia ar trebui sã lase un mesaj în care sã spunã ce au modificat ºi de ce). Observaþi cã utilizatorii normali nu pot modifica un mesaj odatã ce cineva a rãspuns.");
$faq[] = array("Cum pot sã îmi adaug semnatura la mesaj?", "Pentru a adauga o semnaturã trebuie întâi sã vã creaþi una, lucru pe care îl puteþi face accesandu-vã profilul. Odatã ce semnãtura este creatã, puteþi sã bifaþi opþiunea <i>Adaugã semnatura</i> de pe formularul de publicare pentru a vã adãuga semnãtura. Puteþi, de asemenea, sã vã adãugaþi direct semnãtura la toate mesajele bifând opþiunea corespunzatoare din profil (puteþi sã preveniþi adãugarea semnãturii unor anumite mesaje dacã ºtergeþi bifa respectivã din formularul de publicare)");
$faq[] = array("Cum pot crea un sondaj?", "Este uºor sã creaþi un sondaj. Când creaþi un subiect nou (sau modificaþi primul mesaj al unui subiect, dacã aveþi permisiunea), ar trebui sã vedeþi o secþiune <i>Adaugã un chestionar</i> sub zona principalã de publicare (dacã nu vedeþi acest lucru probabil cã nu aveþi privilegiile de acces necesare pentru a crea sondaje). Ar trebui sã introduceþi un titlu pentru chestionar ºi cel puþin douã opþiuni (pentru a alege o opþiune scrieþi întrebarea sondajului ºi apãsaþi pe butonul <i>Adaugã o opþiune</i>). Puteþi sã schimbaþi ºi valabilitatea sondajului, unde perioada 0 înseamnã un sondaj perpetuu. Va exista ºi o limita a numãrului de opþiuni pe care îl puteþi folosi, specificatã de cãtre administrator.");
$faq[] = array("Cum modific sau ºterg un sondaj?", "Ca ºi în cazul mesajelor, sondajele pot fi modificate doar de autor, de moderator sau de un administrator. Pentru a modifica un sondaj efectuaþi un click pe primul mesaj din cadrul subiectului (acesta este întotdeauna asociat cu sondajul). Dacã nimeni nu a votat, atunci poate fi ºters sau modificat, însã dacã cineva a votat deja, doar moderatorul sau administratorul poate modifica sau ºterge sondajul. Acest lucru previne sabotarea sondajelor sau schimbarea inoportunã a opþiunilor."); 
$faq[] = array("De ce nu pot sã accesez un forum?", "Unele forumuri pot fi limitate pentru anumiþi utilizatori sau grupuri. Pentru a vedea, citi, publica, etc. este nevoie probabil de autorizaþie specialã pe care o pot acorda doar moderatorul forumului ºi administratorul. Ar trebui sã luaþi legatura cu ei.");
$faq[] = array("De ce nu pot vota în sondaje?", "Doar utilizatorii înregistraþi pot vota în sondaje (pentru a preveni falsificarea rezultatelor). Daca v-aþi înregistrat ºi tot nu puteþi vota atunci probabil cã nu aveþi drepturile de acces necesare.");


$faq[] = array("--","Formatãri ºi tipuri de mesaje");
$faq[] = array("Ce este codul BB?", "Codul BB este o implementare specialã a HTML-ului. Posibilitatea de a folosi codul BB este datã de decizia administratorului (puteþi dezactiva acest cod de la mesaj la mesaj din formularul de publicare). Codul BB este similar ca stil cu HTML-ul, balizele (tag-urile) sunt închise în paranteze pãtrate [ ºi ] mai degrabã decât &lt; ºi &gt; ºi oferã un control mai bun asupra a ce ºi cum se afiºeazã. Pentru mai multe informaþii despre codul BB, consultaþi ghidul care poate fi accesat de pe pagina de publicare.");
$faq[] = array("Pot folosi HTML?", "Acest lucru depinde de administrator, care are control complet. Dacã vã este permis sã îl folosiþi, probabil cã veþi descoperi cã doar câteva balize funcþioneazã. Aceasta este o masurã de <i>securitate</i> pentru a preîntampina abuzurile care ar duce la distrugerea aºezãrii în paginã sau ar cauza alte probleme. Daca HTML este activat, îl puteþi dezactiva de la mesaj la mesaj din formularul de publicare.");
$faq[] = array("Ce sunt <i>Zâmbetele</i>?", "Zâmbetele sau iconiþele emotive sunt imagini mici care pot fi folosite pentru a exprima anumite sentimente folosind un cod scurt. Spre exemplu :) înseamnã vesel , :( înseamnã trist. Lista completã poate fi vazutã în formularul de publicare. Încercaþi totuºi sã nu îi folosiþi prea mult pentru cã pot face un mesaj ilizibil ºi un moderator se poate hotãrî sã îi scoatã din mesaj sau sã ºteargã mesajul cu totul.");
$faq[] = array("Pot publica imagini?", "Imaginile pot fi afiºate în mesajele dumneavoastrã. Cu toate acestea, nu existã nici o posibilitate în acest forum pentru încarcarea imaginilor direct în forum. De aceea, trebuie sã scrieþi o legaturã cãtre o imagine stocatã pe un server accesibil publicului, cum ar fi <i>http://un.server.oarecare.ro/imaginea-mea.gif</i>. Nu puteþi sã faceþi legatura cu imagini de pe calculatorul dumneavoastrã (doar dacã este un server), nici cu imagini stocate în spatele unui mecanism de autentificare, cum ar fi casuþele de mail, site-uri protejate cu parolã, etc. Pentru a afiºa imaginea, folosiþi fie baliza codului BB [img] sau cod HTML (dacã este permis).");
$faq[] = array("Ce sunt anunþurile?" ,"Anunþurile deseori conþin informaþii importante ºi ar trebui sã le citiþi cât de repede puteþi. Anunþurile apar în partea de sus a fiecãrei pagini în forumul de care aparþin. Dacã puteþi sau nu posta un anunþ depinde de permisiunile necesare, care sunt stabilite de administrator.");             
$faq[] = array("Ce sunt subiectele lipicioase (sticky)?", "Subiectele lipicioase apar sub anunþuri în forum ºi doar pe prima paginã. Deseori sunt destul de importante ºi ar trebui sã le citiþi dacã puteþi. Ca ºi cu anunþurile, administratorul alege ce permisiuni sunt necessre pentru pentru a le publica.");
$faq[] = array("Ce sunt subiectele blocate?", "Subiectele sunt blocate fie de cãtre moderator, fie de cãtre administrator. Nu puteþi rãspunde unui subiect blocat ºi orice chestionar conþinut este închis automat. Subiectele pot fi închise din mai multe motive.");


$faq[] = array("--","Nivele de utilizatori ºi grupuri");
$faq[] = array("Cine sunt administratorii?", "Administratorii sunt cei care au cel mai mare nivel de control asupra întregului forum. Aceºti utilizatori controleazã toate detaliile forumurilor, încluzând permisiunile de acces, excluderea utilizatorilor, crearea grupurilor ºi a moderatorilor, etc. De asemenea, au capacitatea de a modera toate formurile.");
$faq[] = array("Cine sunt moderatorii?", "Moderatorii sunt persoane (sau grupuri de persoane) a cãror menire este sã aibã grijã de forumuri în mod constant. Au permisiunea de a modifica sau ºterge mesajele ºi de a bloca, debloca, muta, ºterge ºi împãrþi subiectele de discuþie în forumurile pe care le modereazã. În mod general, moderatorii existã pentru a avea grijã ca utilizatorii sã nu scrie \"pe lângã subiect\" ºi sã nu scrie materiale abuzive sau ofensatoare.");
$faq[] = array("Ce sunt grupurile de utilizatori?", "Grupurile de utilizatori sunt o modalitate de grupare a utilizatorilor. Fiecare utilizator poate aparþine mai multor grupuri (acest lucru diferã de majoritatea celorlalte programe) ºi fiecare grup are drepturi de acces individuale. Acest lucru uºureazã munca administratorilor dacã doresc ca mai mulþi utilizatori sã modereze un forum sau sã le ofere acces într-un forum privat.");
$faq[] = array("Cum pot sã fac parte dintr-un grup de utilizatori?", "Pentru a intra într-un grup folosiþi legatura de <i>Grupuri de utilizatori</i> din partea de sus a paginii (acest lucru poate fi diferit de la paginã la paginã). Nu toate grupurile sunt deschise, unele sunt închise ºi altele pot fi chiar ascunse. Dacã grupul o permite, puteþi sã cereþi sã fiþi înscris apãsând butonul respectiv. Moderatorul va trebui sã vã aprobe cererea. Este posibil sã vã întrebe care sunt motivele pentru care vã doriþi sã intraþi în grup. Vã rugãm sã nu hãrþuiþi un moderator de grup dacã vã respinge cererea pentru cã are motive întemeiate.");
$faq[] = array("Cum pot deveni moderatorul unui grup de utilizatori?", "Grupurile de utilizatori sunt create de cãtre administrator ºi în acel moment este numit un moderator. Dacã doriþi sã creaþi un grup de utilizatori atunci primul lucru pe care trebuie sã îl faceþi este sã luaþi legatura cu administratorul.");


$faq[] = array("--","Mesaje private");
$faq[] = array("Nu pot trimite mesaje private!", "Existã trei posibile motive: nu sunteþi înregistrat ºi/sau autentificat, administratorul nu a activat mesajele private pentru toþi utilizatorii sau administratorul a restricþionat pentru dumneavoastrã folosirea mesajelor private. În ultimul caz ar trebui sã îl intrebaþi ce motive a avut.");
$faq[] = array("Tot primesc mesaje private nedorite!", "În viitor vom adauga o listã de persoane ale cãror mesaje sã fie ignorate. Deocamdatã dacã primiþi în continuare aceste mesaje anunþaþi administratorul, pentru cã el are posibilitatea de a opri un utilizator sã trimitã mesaje private.");
$faq[] = array("Am primit spam-uri sau mesaje abuzive de la cineva din forum!", "Ne pare rãu sã auzim acest lucru. Formularul pentru trimiterea unui mesaj include mãsuri de siguranþã pentru a observa care utlizatori trimit astfel de mesaje. Ar trebui sã trimiteþi administratorului o copie completã a mesajului primit, inclusiv antetul (acestea oferã detalii despre utilizatorul care a trimis mesajul). Astfel, el poate acþiona.");

//
// These entries should remain in all languages and for all modifications
//
$faq[] = array("--","Întrebãri despre phpBB 2");
$faq[] = array("Cine a scris acest program?", "Acest program (în forma nemodificatã) este produs, lansat ºi aflat sub copyright-ul <a href=\"http://www.phpbb.com/\" target=\"_blank\">grupului phpBB</a>. Este disponibil sub Licenþa Generalã Publicã GNU ºi poate fi distribuit liber; folosiþi legãtura cãtre grup mai multe detalii.");
$faq[] = array("De ce nu este facilitatea X disponibilã?", "Acest program a fost scris ºi licenþiat de cãtre grupul phpBB. În cazul în care consideraþi cã o facilitate trebuie sã fie adaugatã, vã rugãm sã vizitaþi site-ul phpBB.com ºi sã vedeþi ce are de spus grupul phpBB. Vã rugãm sã nu publicaþi cereri de facilitãþi pe forumurile de la phpbb.com, pentru cã grupul phpBB foloseºte sourceforge pentru a delega sarcinile legate de noile facilitãþi. Vã rugãm sã treceþi prin aceste forumuri ºi sã vedeþi, dacã existã, care este poziþia noastrã legatã de o facilitate ºi sã urmaþi procedura explicatã acolo.");
$faq[] = array("Cu cine iau legatura pentru probleme legate de abuzuri ºi/sau juridice legate de acest program?", "Ar trebui sã luaþi legatura cu administratorul forumului. Dacã nu puteþi sã faceþi acest lucru, ar trebui sã încercaþi cu unul din moderatorii de forumuri ºi sã îi intrebaþi cu cine aþi putea lua legatura. Dacã tot nu primiþi rãspuns, ar trebui sã luaþi legãtura cu posesorul domeniului dumneavoastrã (efectuaþi o interogare whois) sau, dacã acesta este pe un domeniu gratuit (yahoo, free.fr, etc.), conducerea sau departamentul pentru abuzuri. Grupul phpBB nu are absolut nici un fel de control ºi nu poate fi tras la rãspundere pentru cum, unde sau de cãtre cine este folosit acest program. Este inutil sã luaþi legatura cu grupul phpBB pentru orice fel de probleme juridice care nu sunt legate direct de pagina phpbb.com sau de program în sine. Dacã trimiteþi un mesaj cãtre grupul phpBB despre orice folosire a unui terþ a acestui program, nu asteptaþi un rãspuns pentru cã nu veþi primi.");

//
// This ends the FAQ entries
//

?>
