<?php

$acl_options  = array(
	'global' => array(
		'a_' 			=> 0,
		'a_auth' 		=> 1,
		'a_backup' 		=> 2,
		'a_ban' 		=> 3,
		'a_clearlogs' 	=> 4,
		'a_email' 		=> 5,
		'a_forum' 		=> 6,
		'a_general' 	=> 7,
		'a_group' 		=> 8,
		'a_post' 		=> 9,
		'a_styles' 		=> 10,
		'a_user' 		=> 11,
		'm_' 			=> 12,
		'm_approve' 	=> 13,
		'm_auth' 		=> 14,
		'm_delete' 		=> 15,
		'm_edit' 		=> 16,
		'm_lock' 		=> 17,
		'm_merge' 		=> 18,
		'm_move' 		=> 19,
		'm_split' 		=> 20,
		'm_unrate' 		=> 21,
		'u_' 			=> 22,
		'u_avatar' 		=> 23,
		'u_sig' 		=> 24,
		'u_pm' 			=> 25,
		'u_email' 		=> 26,
	),
	'local'	=> array(
		'f_' 			=> 0,
		'f_announce' 	=> 1,
		'f_attach' 		=> 2,
		'f_bbcode' 		=> 3,
		'f_delete' 		=> 4,
		'f_download' 	=> 5,
		'f_edit' 		=> 6,
		'f_email' 		=> 7,
		'f_flash' 		=> 8,
		'f_html' 		=> 9,
		'f_ignoreflood' => 10,
		'f_ignorequeue' => 11,
		'f_img' 		=> 12,
		'f_list' 		=> 13,
		'f_poll' 		=> 14,
		'f_post' 		=> 15,
		'f_print' 		=> 16,
		'f_rate' 		=> 17,
		'f_read' 		=> 18,
		'f_reply' 		=> 19,
		'f_search' 		=> 20,
		'f_sigs' 		=> 21,
		'f_smilies' 	=> 22,
		'f_sticky' 		=> 23,
		'f_vote' 		=> 24,
		'm_' 			=> 25,
		'm_approve' 	=> 26,
		'm_auth' 		=> 27,
		'm_delete' 		=> 28,
		'm_edit' 		=> 29,
		'm_lock' 		=> 30,
		'm_merge' 		=> 31,
		'm_move' 		=> 32,
		'm_split' 		=> 33,
		'm_unrate' 		=> 34,
	),
);

?>