services:
    cron.task.core.prune_all_forums:
        class: phpbb_cron_task_core_prune_all_forums
        arguments:
            - %core.root_path%
            - %core.php_ext%
            - @config
            - @dbal.conn
        calls:
            - [set_name, [cron.task.core.prune_all_forums]]
        tags:
            - { name: cron.task }

    cron.task.core.prune_forum:
        class: phpbb_cron_task_core_prune_forum
        arguments:
            - %core.root_path%
            - %core.php_ext%
            - @config
            - @dbal.conn
        calls:
            - [set_name, [cron.task.core.prune_forum]]
        tags:
            - { name: cron.task }

    cron.task.core.queue:
        class: phpbb_cron_task_core_queue
        arguments:
            - %core.root_path%
            - %core.php_ext%
            - @config
        calls:
            - [set_name, [cron.task.core.queue]]
        tags:
            - { name: cron.task }

    cron.task.core.tidy_cache:
        class: phpbb_cron_task_core_tidy_cache
        arguments:
            - @config
            - @cache.driver
        calls:
            - [set_name, [cron.task.core.tidy_cache]]
        tags:
            - { name: cron.task }

    cron.task.core.tidy_database:
        class: phpbb_cron_task_core_tidy_database
        arguments:
            - %core.root_path%
            - %core.php_ext%
            - @config
        calls:
            - [set_name, [cron.task.core.tidy_database]]
        tags:
            - { name: cron.task }

    cron.task.core.tidy_search:
        class: phpbb_cron_task_core_tidy_search
        arguments:
            - %core.root_path%
            - %core.php_ext%
            - @auth
            - @config
            - @dbal.conn
            - @user
        calls:
            - [set_name, [cron.task.core.tidy_search]]
        tags:
            - { name: cron.task }

    cron.task.core.tidy_sessions:
        class: phpbb_cron_task_core_tidy_sessions
        arguments:
            - @config
            - @user
        calls:
            - [set_name, [cron.task.core.tidy_sessions]]
        tags:
            - { name: cron.task }

    cron.task.core.tidy_warnings:
        class: phpbb_cron_task_core_tidy_warnings
        arguments:
            - %core.root_path%
            - %core.php_ext%
            - @config
        calls:
            - [set_name, [cron.task.core.tidy_warnings]]
        tags:
            - { name: cron.task }
