services:
    feed.helper:
        alias: internal.feed.helper

    feed.factory:
        alias: internal.feed.factory

    feed.forum:
        alias: internal.feed.forum

    feed.forums:
        alias: internal.feed.forums

    feed.news:
        alias: internal.feed.news

    feed.overall:
        alias: internal.feed.overall

    feed.topic:
        alias: internal.feed.topic

    feed.topics:
        alias: internal.feed.topics

    feed.topics_active:
        alias: internal.feed.topics_active

    internal.feed.helper:
        class: phpbb\feed\helper
        arguments:
            - @config
            - @user
            - %core.root_path%
            - %core.php_ext%

    internal.feed.factory:
        class: phpbb\feed\factory
        arguments:
            - @service_container
            - @config
            - @dbal.conn

    internal.feed.forum:
        class: phpbb\feed\forum
        scope: prototype
        arguments:
            - @feed.helper
            - @config
            - @dbal.conn
            - @cache.driver
            - @user
            - @auth
            - @content.visibility
            - %core.php_ext%

    internal.feed.forums:
        class: phpbb\feed\forums
        scope: prototype
        arguments:
            - @feed.helper
            - @config
            - @dbal.conn
            - @cache.driver
            - @user
            - @auth
            - @content.visibility
            - %core.php_ext%

    internal.feed.news:
        class: phpbb\feed\news
        scope: prototype
        arguments:
            - @feed.helper
            - @config
            - @dbal.conn
            - @cache.driver
            - @user
            - @auth
            - @content.visibility
            - %core.php_ext%

    internal.feed.overall:
        class: phpbb\feed\overall
        scope: prototype
        arguments:
            - @feed.helper
            - @config
            - @dbal.conn
            - @cache.driver
            - @user
            - @auth
            - @content.visibility
            - %core.php_ext%

    internal.feed.topic:
        class: phpbb\feed\topic
        scope: prototype
        arguments:
            - @feed.helper
            - @config
            - @dbal.conn
            - @cache.driver
            - @user
            - @auth
            - @content.visibility
            - %core.php_ext%

    internal.feed.topics:
        class: phpbb\feed\topics
        scope: prototype
        arguments:
            - @feed.helper
            - @config
            - @dbal.conn
            - @cache.driver
            - @user
            - @auth
            - @content.visibility
            - %core.php_ext%

    internal.feed.topics_active:
        class: phpbb\feed\topics_active
        scope: prototype
        arguments:
            - @feed.helper
            - @config
            - @dbal.conn
            - @cache.driver
            - @user
            - @auth
            - @content.visibility
            - %core.php_ext%
