imports:
    - { resource: services.yml }

parameters:
    profiler.storage.dsn: file:%core.root_path%cache/profiler/

services:
    controller.resolver:
        class: Symfony\Component\HttpKernel\Controller\TraceableControllerResolver
        arguments:
            - @controller.resolver_real
            - @stopwatch

    dispatcher:
        class: Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher
        arguments:
            - @dispatcher_real
            - @stopwatch
        calls:
            - [setProfiler, ["@profiler"]]
            - [addSubscriber, ["@profiler.listener"]]
            - [addSubscriber, ["@profiler.data_collector.request"]]

    profiler:
        class: phpbb\profiler\profiler
        arguments:
            - @profiler.data_collector.collection
            - @profiler.storage

    profiler.data_collector.collection:
        class: phpbb\di\service_collection
        arguments:
            - @service_container
        tags:
            - { name: service_collection, tag: profiler.data_collector   }

    profiler.data_collector.config:
        class: Symfony\Component\HttpKernel\DataCollector\ConfigDataCollector
        tags:
            - { name: profiler.data_collector }

    profiler.data_collector.event:
        class: Symfony\Component\HttpKernel\DataCollector\EventDataCollector
        tags:
            - { name: profiler.data_collector }

    profiler.data_collector.memory:
        class: Symfony\Component\HttpKernel\DataCollector\MemoryDataCollector
        tags:
            - { name: profiler.data_collector }

    profiler.data_collector.request:
        class: Symfony\Component\HttpKernel\DataCollector\RequestDataCollector
        tags:
            - { name: profiler.data_collector }

    profiler.data_collector.router:
        class: Symfony\Component\HttpKernel\DataCollector\RouterDataCollector
        tags:
            - { name: profiler.data_collector }

    profiler.data_collector.time:
        class: Symfony\Component\HttpKernel\DataCollector\TimeDataCollector
        tags:
            - { name: profiler.data_collector }

    profiler.listener:
        class: Symfony\Component\HttpKernel\EventListener\ProfilerListener
        arguments:
            - @profiler

    profiler.storage:
        class: Symfony\Component\HttpKernel\Profiler\FileProfilerStorage
        arguments:
            - %profiler.storage.dsn%

    stopwatch:
        class: Symfony\Component\Stopwatch\Stopwatch
        public: false
