<?php
/***************************************************************************
 *                         lang_faq.php [portuguese]
 *                            -------------------
 *   begin                : Wednesday Oct 3, 2001
 *   copyright            : (C) 2001 The phpBB Group
 *   email                : support@phpbb.com
 *
 *   $Id$
 *
 *
 ***************************************************************************/

 /****************************************************************************
 * Translation by:
 * LuizCB (Pincel) LuizCB@pincel.net || http://pincel.net
 ****************************************************************************/

/***************************************************************************
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 ***************************************************************************/
 
// 
// To add an entry to your FAQ simply add a line to this file in this format:
// $faq[] = array("question", "answer");
// If you want to separate a section enter $faq[] = array("--","Block heading goes here if wanted");
// Links will be created automatically
//
// DO NOT forget the ; at the end of the line.
// Do NOT put double quotes (") in your FAQ entries, if you absolutely must then escape them ie. \"something\"
//
// The FAQ items will appear on the FAQ page in the same order they are listed in this file
//
 
  
$faq[] = array("--","Questões de 'Entrar' e 'Registar'");
$faq[] = array("Porque é que não consigo 'Entrar' nos fóruns?", "Registou-se? Você deve registar-se de forma a poder 'Entrar'. Foi expulso dos fóruns (surgirá uma mensagem se for o caso)? Caso haja uma expulsão deve contactar o 'webmaster' ou o administrador do fórum  e perguntar porquê caso não saiba a razão. Caso esteja registado e não se encontre expulso e mesmo assim não consiga 'Entrar', verifique novamente o seu Nome de Utilizador e Senha são os correctos. Normalmente é esse o problema mas caso tenha a certeza que não é contacte o administrador do fórum porque poderá acontecer haver alguma configuração errada no sistema.");
$faq[] = array("Porque é que me tenho que registar de todo?", "Poderá não ser necessário. Está ao critério do administrador do fórum se é necessário o registo de forma a afixar as suas mensagens. Contudo, o registo dá-lhe acesso a funções adicionais que não estão disponíveis a visitantes que se apresentam no anonimato, como por exemplo o uso e definição de imagens Avatar , uso de Mensagens Privadas, enviar e receber email entre utilizadores, subscrição de Grupos de Utilizadores, etc. São necessários apenas alguns momentos para se fazer o registo como tal é recomendável que o faça.");
$faq[] = array("Porque é que me estou a ligar automaticamente?", "Se não assinalar <i>Ligar-me automaticamente</i> quando premir 'Entrar' o sistema não o irá ligar da próxima vez que visite o fórum. Isto evita o uso abusivo da sua conta por outra pessoa. Para se manter ligado e não necessitar de escrever o seu 'Nome de Utilizador' e 'Senha' assinale essa caixa quando se ligue. Tal não é no entanto recomendável caso aceda aos fóruns num computador partilhado por outros utilizadores, ou seja, bibliotecas, cefé internet ou cyber café, bloco em  universidades, etc.");
$faq[] = array("Como evito que o meu Nome de Utilizador apareça na lista de Ligados?", "No seu Perfil há uma opção <i>Esconder o seu indicador de Ligado</i>. Se assinalar <i>Sim</i> apenas você e administradores podem ver que se encontra ligado. Será tido pelo sistema do phpBB 2 como um Utilizador Invisível.");
$faq[] = array("Perdi a minha Senha!", "Não entre em pânico! Apesar da sua Senha não poder ser recuperada pode no entanto ser colocada como que se nunca a tivesse feito. Para fazer isto ir a 'Entrar', carregar em  <u>Esqueci-me da Senha</u>, seguindo as instruções e voltará a estar ligado em momentos");
$faq[] = array("Registei-me mas não consigo 'Entrar'!", "Primeiro verifique se está a escrever o 'Nome de Utilizador' e 'Senha' correctos. Caso se encontrem bem então uma entre duas coisas poderão estar a acontecer - se o a função de COPPA se encontra activa e você carregou em <u>Tenho menos que 13 anos de idade</u> quando se registou, terá que seguir as instruções que receba. Se isto não é o caso, o seu registo necessita ser activado? Alguns fóruns fazem com que o registo dos seus novos utilizadores seja activado, tanto por si próprio ou pelo administrador, antes que possa 'Entrar'. Caso isso aconteça, quando se registou foi informado se a activação seria ou não necessária. Se recebeu um email então siga as suas instruções. Se não recebeu o email, será que o endereço de email é válido? Uma das razões para a activação ser feita é para reduzir a possibilidade de utilizadores <i>disfarçados</i> abusarem do sistema anonimamente. Se tem a certeza que o endereço de email que forneceu é válido tente então contactar o administrador do fórum.");
$faq[] = array("Registei-me no passado mas não consigo mais 'Entrar'?!", "As razóes mais prováveis são; escreveu um 'Nome de Utilizador' ou 'Senha' incorrectos (verifique o email que lhe terá sido enviado quando se registou inicialmente) ou o administrador removeu o seu registo por algum motivo. Se é este o caso.. será que você não usou o fórum? É normal em alguns fóruns remover registos de utilizadores que nunca colocaram alguma mensagem de forma a reduzir o tamanho da base de dados. Tente registar-se novamente e envolver-se nos assuntos dos fóruns.");


$faq[] = array("--","Preferências e Configuração de Utilizadores");
$faq[] = array("Como mudo a minha configuração?", "Toda a sua configuração (se está registado) é guardada na base de dados. Para a alterar prima em <u>Perfil</u> (normalmente mostrado no topo das páginas). A partir daí pode alterar a sua configuração pessoal");
$faq[] = array("Os tempos e datas não são os correctos!", "Os tempos decerto que estão correctos, contudo pode acontecer você estar a ver horas de um fuso horário diferente do onde você se encontra. Se é esse o caso deve mudar no seu 'Perfil' a opção para o fuso horário de forma a abranger a sua área, ou seja, Londres, Paris, Nova Iorque, Sidney, etc. De notar que a mudança do fuso horário bem como a maior parte das opções de perfil só é permitida a utilizadores registados. Como tal se ainda não se encontra registado é uma boa altura para o fazer!");
$faq[] = array("Mudei o fuso horário mas a hora continua errada!", "Se tem a certeza que o fuso horário que escolheu é o correcto e a hora não é a real é possível que seja devido a mudança horária para ajustamento de hora diurna e nocturna (ou hora de verão como é conhecido em Inglaterra e outros locais). O phpBB não se encontra desenhado para efectuar essas mudanças automaticamente, como tal devem ser ajustadas manualmente pelos utilizadores.");
$faq[] = array("A língua da minha nacionalidade não se encontra na lista!", "A razão mais provável é o administrador não ter instalado essa língua ou o phpBB ainda não foi traduzido para ela. Peça ao administrador do que instale esse 'pacote de língua', caso não exista você poderá criar uma nova tradução. Para mais informação consultar a página oficial do Grupo phpBB (seguir o atalho ao fundo destas páginas)");
$faq[] = array("Como posso mostrar uma imagem por debaixo do meu Nome de Utilizador?", "Devem haver duas imagens na parte inferior de cada Nome de Utilizador quando se vêm as mensagens. A primeira representa o escalão em que o utilizador se encontra, normalmente em forma de blocos ou estrelas indicando a quantidade de mensagens ou o estatuto desse utilizador nos fóruns. Abaixo dessas poderá existir uma imagem maior conhecida como Avatar, que é normalmente única ou pertencente a cada utilizador. Está ao cargo do administrador dos fóruns permitir ou não a afixação de Avatars bem como a forma em como os utilizadores os possam afixar. Se você não consegue colocar o seu Avatar então possivelmente é decisão do administrador dos fóruns. Pergunte-lhe a razão (temos a certeza que existe uma boa justificação!)");
$faq[] = array("Como posso mudar o meu escalão?", "De uma forma geral o utilizador normal não pode alterar directamente o seu escalão (os escalões aparecem por baixo do Nome de Utilizador em tópicos e no 'Perfil' dependendo no estilo de fórum em uso). A mair parte dos escalões em fóruns indicam o número de mensagens que você tenha colocado ou indicam certo tipo de utilizadores, ou seja, moderadores e administradores poderão ter um escalão especial. Por favor não abuse dos fóruns colocando mensagens desnecessárias apenas para aumentar o seu nível de escalão pois o moderador ou administrador poderão baixar essa contagem caso verifiquem que haja abuso.");
$faq[] = array("Quando carrego no atalho de email de um utilizador perguntame para 'Entrar'?", "Lamentamos mas apenas utilizadoresd registados poderão enviar email a pessoas via o formulário exclusivo do fórum (caso o administrador tenha activado essa função). Isso é para evitar o uso malicioso do sistema de email por utilizadores anónimos.");


$faq[] = array("--","Posting Issues");
$faq[] = array("Como posso colocar uma mensagem num fórum?", "Fácil, prima no butão respectivo tanto no fórum como no tópico onde se encontre. Talvez seja necessário o seu registo nos fóruns para poder afixar mensagens. Há uma lista de acções que lhe são permitidas, podendo verificar se essa função se encontra activa para o seu caso particular, no canto inferior direito de cada fórum ou tópico (<i>Pode colocar mensagens novas, Pode votar, etc.<i> list)");
$faq[] = array("Como posso editar ou remover uma mensagem?", "A menos que seja um administrador do fórum você apenas pode editar ou remover as suas próprias mensagens. Pode editar uma mensagem (por vezes apenas por um período limitado após ser colocada) carregando no butão <i>editar</i> na parte inferior dessa mensagem.  Caso alguém tenha já respondido a essa mensagem você encontrará um pequeno texto ao fundo da sua mensagem após a editar, mencionando que foi editada e eventualmente quantas vezes tal foi feito. Isto aparece apenas caso essa mensagem não tenha ainda respostas. Também não aparecerá caso a alteração seja efectuada por algum administrador ou moderador (possivelmente eles deixarão uma mensagem dizendo o que foi alterado e o motivo). De notar que utilizadores normais não podem remover uma mensagem após alguém ter respondido á mesma.");
$faq[] = array("Como adiciono uma assinatura a uma mensagem?", "Para adicionar uma assinatura a uma mensagem deverá primeiro criar uma no seu 'Perfil'. Uma vez criada assinale em <i>Adicionar Assinatura</i> na lista de opções por baixo da caixa de escrita da mensagem. Pode ser também sempre adicionada uma assinatura em todas as suas mensagens desde que tal seja assinalado no seu 'Perfil' (poderá entretanto evitar que a assinatura seja adicionada em alguma mensagem retirando a marca em <i>Adicionar Assinatura</i> na lista de opções por baixo dessa mensagem)");
$faq[] = array("Como posso criar uma votação?", "Criar uma votação é fácil. Quando afixa um tópico novo (ou edita a primeira mensagem de um tópico, caso tenha permissão para tal) encontra na parte inferior á caixa principal da mensagem um painel com o título <i>Adicionar Votação</i> (se você não vê isto é porque provavelmente não possui permissão para criar votações). Deverá escrever um título para a votação no local apropriado e de seguida colocar pelo menos duas opções de escolha (para adicionar uma opção escreva o que pretende e carregue no butão <i>Adicionar opção de escolha para a votação</i>. Deverá também estipular um limite tempo para a votação, sendo 0 ilimitada. Poderá acontecer haver um limite no número de opções de escolha, estando esse limite ao critério e configurado pelo administrador dos fóruns");
$faq[] = array("Como posso editar ou remover uma votação?", "Da mesma forma que as mensagens as votações apenas poderão ser editadas pelo seu autor, um moderador ou o administrador dos fóruns. Para editar uma votação carregue na primeira mensagem do tópico (esta mensagem é a que tem a votação associada ao tópico). Caso ninguém tenha submetido voto os seus autores podem remover a votação ou editar as suas opções de escolha, contudo se os utilizadpres já colocaram votos apenas moderadores e administradores podem editar ou remover essa votação. Isto é para evitar com que sejam alteradas as opções de escolha em votações em curso");
$faq[] = array("Porque não consigo entrar num fórum?", "O acesso a alguns fóruns poderá estar limitado apenas a determinados utilizadores ou grupos. Para verificar, ler, colocar mensagens, etc., você deve necessitar autorização especial. Apenas o moderador desse fórum e um administrador podem podem permitir esse acesso. Contacte-os caso ache necessário.");
$faq[] = array("Porque não posso votar?", "Apenas utilizadores registados podem submeter os seus votos (para impedir duplicação nos resultados). Se você se encontra registado e mesmo assim não consegue votar então possivelmente não possui permissão para tal.");


$faq[] = array("--","Formatos e tipos de Tópicos");
$faq[] = array("O que é BBCode?", "BBCode é uma implementação especial de HTML. Se poderá ou não usar BBCode está ao critério do administrador (você pode desactiva-lo em cada mensagem em 'Desactivar BBCode nesta mensagem'). O BBCode por si mesmo é similar em estilo ao HTML, as etiquetas sao introduzidas entre perêntesis rectos [ and ] em vez de &lt; e &gt; e proporciona um maior controle do que e como algo é apresentado. Para mais informações acerca de BBCode veja o guia respectivo, acessível na página das mensagens.");
$faq[] = array("Posso usar HTML?", "Depende se o administrador o permite, ele tem o controle completo sobre isso. Se lhe é permitodo a si usar HTML provavelmente apenas alguns códigos lhe sáo acessíveis. Isto é uma medida de <i>segurança</i> para evitar que pessoas abusem do fórum usando códigos que possam destruir o seu formato ou causar outros problemas. Caso HTML esteja activo você pode desactiva-lo em cada mensagem em 'Desactivar HTML nesta mensagem'.");
$faq[] = array("O que são Smileys?", "Smileys, or Emoticons são pequenas representações gráficas que podem ser usadas para expressar algum sentimento usando poucos caracteres, ou seja, :) quer dizer feliz, :( quer dizer triste. Uma lista completa de emoções pode ser vista no formulario junto á caixa de cada mensagem. Tente evitar o uso excessivo dos smileys já que podem tornar uma mensagem ilegível e um moderador pode decidir remove-los ou apagar a mensagem no seu todo");
$faq[] = array("Posso afixar imagens?", "As imagens podem na verdade aparecer entre as suas mensagens. Contudo, n\ao h]a presentemente alguma forma de carregar imagens directamente  ao phpBB. Como tal você terá que ligar a imagem armazenada num servidor publicamente acessível, ou seja, http://www.algum-lugar-desconhecido.net/minha-imagem.gif. Não pode ligar ao fórum imagens guardadas no seu próprio PC (a menos que possua um servider publicamente acessível) nem imagens armazenadas sob mecanismos que requeiram autenticação, como por exemplo caixas de correio electrónico de hotmail ou yahoo, páginas protegidas por senha, etc. Para mostrar a imagem pode usar tanto BBCode [img] como o código apropriado de HTML (se activo).");
$faq[] = array("O que são Anúncios?", "Os Anúncios contém normalmente informação importante e você deve le-los logo que eles surjam. Os Anúncios surgem no topo de cada página do fórum em que são afixados. Se você possa ou não fazer uso dessa função depende das permissões que lhe foram conferidas, configuradas pelo administrador.");
$faq[] = array("O que são tópicos Inamovíveis?", "Tópicos Inamovíveis aparecem por baixo de anúncios nos fóruns e apenas na primeira página. São vulgarmente importantes e como tal devem ser lidos logo que possível. Da mesma forma que os Anúncios está ao critério do adminsitrador dos fóruns determinar que permissões são necessárias para afixar mensagens Inamovíveis em cada fórum.");
$faq[] = array("O que são tópicos Bloqueados?", "Os tópicos Bloqueados são dessa forma colocados por um moderador ou o admministrador dos fóruns. Quando um tópico se encontra bloqueado não é permitido aos utilizadores responder com mais mensagens e qualquer eventual votação existente termina automaticamente. Os tópicos podem ser bloquados por várias razões.");


$faq[] = array("--","Níveis de utilizadores e Grupos");
$faq[] = array("O que sáo Administradores?", "Administradores são pessoas com o nível máximo de controle sobre todos os aspectos dos fóruns. Essas pessoas podem controlar todos os aspectos da operação dos fóruns, incluindo determinar permissões, expulsar utilizadores, criar grupos de utilizadores ou moderadores, etc. Eles possuem igualmente todas os poderes de moderador em todos os fóruns existentes.");
$faq[] = array("O que são Moderadores?", "Moderadores são indivíduos (ou grupos de indivíduos) cujo trabalho é supervisionar diariamente o funcionamento dos fóruns que lhe estão designados. Eles tem o poder de editar ou remover mensagens, bloquear, desbloquear, mover, remover e subdividir tópicos nos fóruns onde são moderadores. Geralmente os moderadores fiscalizam mensagens que possam ir <i>para além do assunto em discussão<i> ou o uso de material abusivo ou ofensivo.");
$faq[] = array("O que são Grupos de Utilizadores?", "Grupos de Utilizadores são uma forma dos administradores dos fóruns agrupar utilizadores. Cada utilizador pode pertencer a vários grupos (isto difere da maioria dos outros tipos de Quadros de Mensagens) e cada a grupo podem ser dados direitos de acesso individuais. Isto torna mais fácil aos administradores destinar vários utilizadores como moderadores de um determinado fórum ou dar-lhes acesso a um fórum privado, etc.");
$faq[] = array("Como me associo a um Grupo de Utilizadores?", "Para se associar a um Grupo de Utilizadores carregue no atalho de Grupos no topo da página (dependendo do desenho de cada Modelo de phpBB no fórum), podendo então ver todos os Grupos. Nem todos os Grupos possuem um <i>acesso aberto</i>, alguns são fechados e alguns poderão inclusivé encontrar-se invis]iveis. Se o Grupo se encontra aberto você poderá entao solicitar que seja membro carregando no butão apropriado. O moderador do Grupo de Utilizadores necessita aprovar o seu pedido, podendo perguntar-lhe a razão do seu pedido. Por favor não insistir perante um Moderador de Grupo caso o seu pedido seja recusado. Eles têm as usas razões.");
$faq[] = array("Como posso vir a ser um Moderador de Grupo?", "Os Gruupos de Utilizadores são iniialmente criados pelo administrador dos fóruns o qual também encarrega alguém de ser Moderador. Se está interessado em criar um Grupo de Utilizadores o seu primeiro ponto de contacto será portanto o Administrador dos Fóruns, ao qual deverá contactar com uma 'Mensagem Privada circunstanciada'.");


$faq[] = array("--","Mensagens Privadas");
$faq[] = array("Não posso enviar Mensagens Privadas!", "Há três razões para que tal possa acontecer; você não está registado nos fóruns e/ou não ligado, o Adminstrador ter]a desligado a possibilidade da troca de Mensagens Privadas para todos os fóruns ou o Administrador impede-o por algum motivo de enviar mensagens. Se é este o último caso você deverá perguntar ao Administrador qual a razão, caso não a saiba.");
$faq[] = array("Recebo várias Mensagens Privadas indesejáveis!", "No futuro iremos adicionar uma lista de utilizadores a ser ignorados ao sistema de Mensagens Privadas. Por agora caso você continue a receber mensagens privadas não solicitadas a partir de alguém em particular informe o Administrador, que poderá inviabilizar qualquer utilizador de enviar Mensagens privadas.");
$faq[] = array("Recebi de alguém neste fórum mensagens de email com assuntos irrelevantes ou abusivos!", "Lamentamos que tal tenha acontecido. O sistema de email neste fórum possui funções de segurança que tentam detectar utilizadores quem enviem esse tipo de mensagens. Você deve participar o acontecido ao Administrador  dos fóruns com uma cópia completa do email recebido, sendo muito importante que includa os cabeçalhos (nesses encontrm-se os detalhes do utilizador que enviou o email). O administrador poderá então proceder de acordo.");

//
// These entries should remain in all languages and for all modifications
//
$faq[] = array("--","Questões de phpBB 2");
$faq[] = array("Quem escreveu este Quadro de Mensagens?", "Este software (na sua forma não modificada) é produzido, publicado e com direitos reservados por <a href=\"http://www.phpbb.com/\" target=\"_blank\">phpBB Group</a>. Está disponível sob 'GNU General Public Licence' e pode ser distribuido gratuitamente, verificar o atalho para detalhes");
$faq[] = array("Porque não há a função X?", "Este software foi escrito e licenciado por phpBB Group. Se pensa que alguma função pode ser adicionada visite a nossa página oficial the phpbb.com e veja o que o Grupo phpBB pode dizer sobre o assunto. Por favor não coloque mensagens com pedido de funções no fórum em phpbb.com, o Grupo usa sourceforge para resolver situações relacionadas com funções novas. Por favor ler cuidadosamente esse fórum para ver se, caso alguma, posição foi por nós já tomada para a função em questão e siga então o procedimento lá mencionado.");
$faq[] = array("A quem deva eu contactar acerca de questões abusivas e/ou legais relacionadas com este fórum?", "Você deverá contactar o Administrador dos fóruns. Se não conseguir saber quem o seja contacte então um dos moderadores pergundando então a quem deva expor o assunto. No caso de mesmo assim não obter resposta deve contactar o dono do domínio (faça um 'verifição de whois') ou, caso o fórum se encontre a funcionar num serviço grátis (por exemplo, yahoo, free.fr, f2s.com, etc.), o gerência ou o departamento de abusos desse serviço. Por favor notar que phpBB Group não possui absolutamente nenhum controle  e náo pode de qualquer maneira ser responsável sobre quando, onde e por quem este fórum é usado. Não há qualquer razão em contactar o phpBB Group em relação a qualquer questão legal (interrupção e desistência, de responsabilidade, comentário difamatório, etc.) não directamente relacionado com o 'site' phpbb.com ou o software discreto de phpBB por si próprio. Caso envie algum email a phpBB Group acerca do uso de terceiros deste software poderá receber uma resposta concisa ou não receber resposta de todo.");

//
// This ends the FAQ entries
//

?>