<?php
/***************************************************************************
 *                        lang_bbcode.php [portuguese]
 *                            -------------------
 *   begin                : Wednesday Oct 3, 2001
 *   copyright            : (C) 2001 The phpBB Group
 *   email                : support@phpbb.com
 *
 *   $Id$
 *
 *
 ***************************************************************************/

 /****************************************************************************
 * Translation by:
 * LuizCB (Pincel) LuizCB@pincel.net || http://pincel.net
 ****************************************************************************/

/***************************************************************************
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 ***************************************************************************/
  
$faq[] = array("--","Introdução");
$faq[] = array("O que é BBCode?", "BBCode é uma implementação especial de HTML. A possibilidade em poder usar BBCode nas suas mensagens é determinada pelo Administrador dos fóruns. Adicionalmente, você pode poderá desligar o BBCode em cada mensagem assinalando <b>Desactivar BBCode nesta mensagem</b> abaixo da caixa principal de cada mensagem. BBCode por si mesmo é similar em estilo ao HTML, as etiquetas (tags) são incluidas em parêntesis rectos [ and ] em vez de &lt; e &gt; proporcionando um maior controle do que haja a fazer bem como da sua apresentação. A tarefa de adicionar BBCode às suas mensagen é facilitada pelo uso de um painel colocado imediatamente acima à caixa principal das mensagens, dependendo do modelo de phpBB em uso, onde pode escolher e aplicar os vários itens consoante o código que pretenda aplicar. Apesar da existência desse painel decerto que este guia irá ser-lhe útil.");

$faq[] = array("--","Formatos de Texto");
$faq[] = array("Como criar texto sobrecarregado, itálico e sublinhado", "O BBCode inclúi etiquetas que lhe permitem mudar rapidamente o estilo básico do texto. Isto é possível das seguintes formas: <ul><li>Para tornar uma parte de texto sobrecarregada incluí-la entre <b>[b][/b]</b>, ou seja, <br /><br /><b>[b]</b>Olá<b>[/b]</b><br /><br />passará a ser <b>Olá</b></li><li> Para sublinhar use <b>[u][/u]</b>. Por exemplo:<br /><br /><b>[u]</b>Bom Dia<b>[/u]</b><br /><br />passa a ser <u>Bom Dia</u></li><li> Para tornar o texo itálico use <b>[i][/i]</b>, ou seja,<br /><br />Isto é <b>[i]</b>Óptimo!<b>[/i]</b><br /><br /> resulta em: Isto é <i>Óptimo!</i></li></ul>");
$faq[] = array("Como mudar a cor ou o tamanho do texto", "Para alterar a cor ou o tamanho do texto devem ser usadas as seguintes etiquetas. Ter em mente que a forma como aparecerá no monitor de cada visitante depende do 'browser' ou do sistema que use: <ul><li> A mudança da cor do texto é feita englobando-o em <b>[color=][/color]</b>. Tanto pode especificar o nome de uma cor conhecida (terá que ser em ingês) (por exempllo, red, blue, yellow, etc.) ou especificando o seu valor hexadecimal, ou seja, #FFFFFF, #000000. Por exemplo, para criar texto em vermelho poderá usar:<br /><br /><b>[color=red]</b>Olá!<b>[/color]</b><br /><br />ou<br /><br /><b>[color=#FF0000]</b>Olá!<b>[/color]</b><br /><br /> Ambos resultarão em <span style=\"color:red\">Olá!</span></li><li> A mudança do tamanho do texto pode ser feita de uma forma similar, usando <b>[size=][/size]</b>. Esta etiqueta está dependente do Modelo de phpBB que você se encontre a usar mas o formato recomendado é um valor numérico representando o tamanho de texto em pixels, começando em 1 (tão pequeno que praticamente não se vê) até 29 (enorme). Por exemplo:<br /><br /><b>[size=9]</b>PEQUENO<b>[/size]</b><br /><br /> normalmente surge como <span style=\"font-size:9px\">PEQUENO</span><br /><br />enquanto que <br /><br /><b>[size=24]</b>ENORME!<b>[/size]</b><br /><br />será <span style=\"font-size:24px\">ENORME!</span></li></ul>");
$faq[] = array("Posso combinar etiquetas de formato?", "Sim, claro que pode. Por exemplo, para cativar a atenção de alguém poderá escrever:<br /><br /><b>[size=18][color=red][b]</b>OLHE PARA MIM!<b>[/b][/color][/size]</b><br /><br /> que irá aparecer como <span style=\"color:red;font-size:18px\"><b>OLHE PARA MIM!</b></span><br /><br /> No entanto, não recomendamos o uso de muito texto da forma que acabámos de descrever! Lembre-se que depende de si, o autor da mensagem, assegurar que os códigos sejam colocados correctamente. Por exemplo, isto está incorrecto:<br /><br /><b>[b][u]</b> errado<b>[/b][/u]</b>");

$faq[] = array("--","Citar e produzir texto de largura fixa");
$faq[] = array("Citar texto em respostas", "Há duas formas de reproduzir texto previamente feito (normalmente uma réplica de uma mensagem anterior), com ou sem referência.<ul><li>Quando utiliza a função <b>Citar</b> para responder a uma mensagem no fórum, note que o texto dessa mensagem é adicionado ao corpo da messagem incluído num <b>[quote=\"\"][/quote]</b> bloco. Este método permite-lhe citar com uma referência a uma pessoa ou o que você decida colocar! Por exemplo, para citar uma peça de texto que Mr. Blobby escreveu, você escreverá:<br /><br /><b>[quote=\"Mr. Blobby\"]</b>O texto que Mr. Blobby escreveu irá aqui<b>[/quote]</b><br /><br /> No resultado será adicionado automaticamente, <b>Mr. Blobby escreveu:</b> antes do texto citado. De notar que você <b>tem que</b> incluir aspas \"\" à volta do nome que esteja a citar.</li><li>O segundo método permite-lhe citar algo sem referência a alguém ou algo. Para o fazer, englobe o texto em etiquetas <b>[quote][/quote]</b>. Quando verificar a mensagem verá que simplesmente surge, <b>Citação:</b> antes do texto.</li></ul>");
$faq[] = array("Produzir código ou texto com uma largura fixa", "Se pretende reproduzir uma porção de código ou de facto algo que requeira uma largura fixa, ou seja, tipo de fonte Courier, englobe o texto em etiquetas <b>[code][/code]</b>, como por exemplo<br /><br /><b>[code]</b>echo \"Isto é algum código\";<b>[/code]</b><br /><br />O formato usado entre as etiquetas <b>[code][/code]</b> é preservado quando posteriormente o verificar.");

$faq[] = array("--","Gerar listas");
$faq[] = array("Criar uma lista sem ordem específica", "O BBCode aceita dois tipos de listas, sem ordem e ordenada. São basicamente o mesmo que em HTML. Uma lista sem ordem produz cada item de uma forma sequencial, um a seguir ao outro,  precedendo-o um caracter constante. Para a criar usar <b>[list][/list]</b> e colocar cada item entre essas etiquetas, usando <b>[*]</b> antes de cada um. Por exemplo, para listar as suas cores favoritas, pode escrever:<br /><br /><b>[list]</b><br /><b>[*]</b>Vermelho<br /><b>[*]</b>Azul<br /><b>[*]</b>Amarelo<br /><b>[/list]</b><br /><br /> Isto irá aparecer como:<ul><li>Vermelho</li><li>Azul</li><li>Amarelo</li></ul>");
$faq[] = array("Criar uma lista ordenada", "O segundo tipo de listas, a ordenada, proporciona-lhe controle do que vá aparecer antes de cada item. Para criar uma lista ordenada você usará <b>[list=1][/list]</b> de forma a criar uma lista numérica ou, <b>[list=a][/list]</b>, para uma lista alfabética. Da mesma forma que para o tipo de lista sem ordem os itens são precedidos de <b>[*]</b>. Por exemplo:<br /><br /><b>[list=1]</b><br /><b>[*]</b>Ir às compras<br /><b>[*]</b>Comprar um computador novo<br /><b>[*]</b>Insultar o computador quando fica bloqueado<br /><b>[/list]</b><br /><br />produzirá o seguinte:<ol type=\"1\"><li>Ir às compras</li><li>Comprar um computador novo</li><li>Insultar o computador quando fica bloqueado</li></ol> Enquanto que para uma lista alfabética você usará:<br /><br /><b>[list=a]</b><br /><b>[*]</b>A primeira resposta<br /><b>[*]</b>A segunda resposta<br /><b>[*]</b>A terceira resposta<br /><b>[/list]</b><br /><br />resultando em <ol type=\"a\"><li>A primeira resposta</li><li>A segunda resposta</li><li>A terceira resposta</li></ol>");

$faq[] = array("--", "Criar atalhos");
$faq[] = array("Criar um atalho para outra página/site", "O phpBB BBCode aceita um número variável de formas para criar URIs, Uniform Resource Indicators, melhor conhecidos como URLs.<ul><li>A primeira dessas formas é usando a etiqueta <b>[url=][/url]</b>. O que quer que escreva depois do sinal = faz com que o conteúdo dessa etiqueta aja como um URL. Por exemplo, para fazer uma ligação-atalho à página phpBB.com escreve:<br /><br /><b>[url=http://www.phpbb.com/]</b>Visite phpBB!<b>[/url]</b><br /><br /> Isto irá resultar no atalho seguinte: <a href=\"http://www.phpbb.com/\" target=\"_blank\">Visite phpBB!</a>. Veja que a página irá abrir numa janela nova de forma a que o utilizador possa continuar nos fóruns.</li><li> Se pretende que o URL esteja à vista, faça simplesmente isto:<br /><br /><b>[url]</b>http://www.phpbb.com/<b>[/url]</b><br /><br />Tal resultará no seguinte atalho: <a href=\"http://www.phpbb.com/\" target=\"_blank\">http://www.phpbb.com/</a></li><li> Adicionalmente o phpBB possui algo chamado <i>Atalhos Mágicos</i>, função que permite transformar automaticamente  qualquer URL escrito com um sintaxe correcto num atalho sem ser necessário especificar quaisquer etiquetas ou mesmo o prefixo http://. Por exemplo, escrevendo www.phpbb.com na sua mensagem, automaticamente resultará em <a href=\"http://www.phpbb.com/\" target=\"_blank\">www.phpbb.com</a> quando vir essa mensagem.</li><li> A mesma coisa se aplica aos endereços de email, podendo especificar o endereço. Por exemplo:<br /><br /><b>[email]</b>ninguem@domain.adr<b>[/email]</b><br /><br />que resultará em <a href=\"emailto:ninguem@domain.adr\">ninguem@domain.adr</a>, ou pode apenas escrever ninguem@domain.adr na sua mensagem que será automaticamente convertido em atalho quando a mensagem for guardada.</li></ul>
Como em todos os códigos BBCode aqui apresentados pode misturar URLs com quaisquer outras etiquetas. Como por exemplo, <b>[img][/img]</b> (ver o item seguinte), <b>[b][/b]</b>, etc. Em relação ao formato das etiquetas está totalmente dependente de si assegurar a ordem correcta de início e fecho, por exemplo:<br /><br /><b>[url=http://www.phpbb.com/][img]</b>http://www.phpbb.com/images/phplogo.gif<b>[/url][/img]</b><br /><br /><u>não é</u> correcto, o que pode conduzir à sua mensagem ser removida por algum moderador ou Administrador. Como tal tenha cuidado.");

$faq[] = array("--", "Mostrar imagens em mensagens");
$faq[] = array("Adicionar uma imagem a uma mensagem", "O phpBB BBCode incorpora uma etiqueta para incluir imagens nas suas mensagens. Dois factores muito importantes a recordar quando se usa estas etiquetas: a maioria dos utilizadores não gosta de ver muitas imagens em mensagens; segundo, a imagem que pretende mostrar deve exixtir na internet (por exemplo, não pode existir apenas no seu computador a menos que tenha um servidor de páginas na web, esteja sempre activo e seja publicamente acessível!). Não há presentemente qualquer forma de armazenar imagens localmente, com o phpBB (contamos dar especial atenção a esse assunto na próxima publicação do phpBB). Para mostrar uma imagem você terá que envolver o URL da imagem com as etiquetas <b>[img][/img]</b>. Por exemplo:<br /><br /><b>[img]</b>http://www.phpbb.com/images/phplogo.gif<b>[/img]</b><br /><br /> Como deve ter notado na secção do URL acima, pode englobar uma imagem numa etiqueta <b>[url][/url]</b> se assim o desejar, ou seja, <br /><br /><b>[url=http://www.phpbb.com/][img]</b>http://www.phpbb.com/images/phplogo.gif<b>[/img][/url]</b><br /><br />irá produzir:<br /><br /><a href=\"http://www.phpbb.com/\" target=\"_blank\"><img src=\"http://www.phpbb.com/images/phplogo.gif\" border=\"0\" alt=\"\" /></a><br />");

$faq[] = array("--", "Outros assuntos");
$faq[] = array("Posso adicionar as minhas próprias etiquetas?", "Não, receio que não o possa fazer directamente no phpBB 2.0. Pensamos proporcionar na próxima versão do phpBB etiquetas de BBCode configuráveis.");

//
// This ends the BBCode guide entries
//

?>
