services:
    installer.update_filesystem.check_task:
        class: phpbb\install\module\update_filesystem\task\file_check
        arguments:
            - '@filesystem'
            - '@installer.helper.config'
            - '@installer.helper.iohandler'
            - '@installer.helper.update_helper'
            - '%core.root_path%'
        tags:
            - { name: update_filesystem, order: 10 }

    installer.update_filesystem.diff_files:
        class: phpbb\install\module\update_filesystem\task\diff_files
        arguments:
            - '@installer.helper.container_factory'
            - '@installer.helper.config'
            - '@installer.helper.iohandler'
            - '@installer.helper.update_helper'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: update_filesystem, order: 20 }

    installer.update_filesystem.show_file_status:
        class: phpbb\install\module\update_filesystem\task\show_file_status
        arguments:
            - '@installer.helper.container_factory'
            - '@installer.helper.config'
            - '@installer.helper.iohandler'
            - '@filesystem'
            - '@installer.file_updater.factory'
        tags:
            - { name: update_filesystem, order: 30 }

    installer.update_filesystem.update_files:
        class: phpbb\install\module\update_filesystem\task\update_files
        arguments:
            - '@installer.helper.container_factory'
            - '@installer.helper.config'
            - '@installer.helper.iohandler'
            - '@installer.file_updater.factory'
            - '@installer.helper.update_helper'
            - '%core.root_path%'
        tags:
            - { name: update_filesystem, order: 40 }

    installer.update_filesystem.download_updated_files:
        class: phpbb\install\module\update_filesystem\task\download_updated_files
        arguments:
            - '@installer.helper.config'
            - '@installer.helper.iohandler'
            - '@filesystem'
        tags:
            - { name: update_filesystem, order: 50 }

    installer.module.update_filesystem_collection:
        class: phpbb\di\ordered_service_collection
        arguments:
            - '@service_container'
        tags:
            - { name: service_collection, tag: update_filesystem, class_name_aware: true }

    installer.module.filesystem_update:
        class: phpbb\install\module\update_filesystem\module
        parent: installer.module_base
        arguments:
            - '@installer.module.update_filesystem_collection'
            - true
            - false
        tags:
            - { name: installer_update_module, order: 30 }
