<?php
/***************************************************************************
 *                          lang_faq.php [French]
 *                            -------------------
 *   begin                : Wednesday Oct 3, 2001
 *   copyright            : (C) 2001 The phpBB Group
 *   email                : support@phpbb.com
 *
 *   $Id$
 *
 *
 ***************************************************************************/

/***************************************************************************
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 ***************************************************************************/
 
//
//	Translation produced by Helix
//	http://www.phpbb-fr.com/
//


$faq[] = array("--","Connexion et Enregistrement");  
$faq[] = array("Pourquoi ne puis-je pas me connecter ?", "Vous êtes-vous enregistré ? Plus sérieusement, vous devez vous enregistrer afin de vous connecter. Avez-vous été banni du forum (un message est affiché si vous l'êtes) ? Si oui, vous devriez contacter le webmestre ou l'administrateur du forum pour en découvrir la raison. Si vous vous êtes enregistré et que vous n'êtes pas banni et que vous ne pouvez toujours pas vous connecter, vérifiez et revérifiez vos nom d'utilisateur et mot de passe. C'est généralement de là que vient le problème, si cela ne fonctionne toujours pas, contactez l'administrateur du forum, il se peut que le forum ait été mal configuré.");
$faq[] = array("Pourquoi n'ai-je pas besoin de m'enregistrer ?", "Vous pouvez ne pas en avoir besoin, c'est à l'administrateur de décider si vous avez besoin ou non de vous enregistrer pour poster des messages sur certains forums. Toutefois, l'enregistrement vous donnera accès à des fonctions additionnelles non-disponibles pour les invités tels que le choix d'une image avatar, une messagerie privée, l'envoi d'email à des amis, l'inscription à un groupe d'utilisateurs, etc. L'enregistrement prend seulement quelques instants, il est donc recommandé de le faire.");
$faq[] = array("Pourquoi suis-je déconnecté automatiquement ?", "Si vous ne cochez pas la case <i>Se connecter automatiquement à chaque visite</i> lorsque vous vous connectez, le forum vous gardera seulement connecté pour une période préétablie. Ceci permet d'éviter une utilisation abusive de votre compte par quelqu'un d'autre. Pour rester connecté, cochez la case en vous connectant, ceci n'est pas recommandé si vous accédez au forum en utilisant un ordinateur partagé, ex : bibliothèque, cybercafé, université, etc.");
$faq[] = array("Comment puis-je éviter que mon nom d'utilisateur apparaisse dans la liste des utilisateurs en ligne ?", "Dans votre profil, vous trouverez une option <i>Cacher sa présence en ligne</i>, si vous choisissez <i>Oui</i>, vous n'apparaîtrez qu'uniquement aux yeux des administrateurs ou vous-même. Vous serez compté comme un utilisateur invisible.");
$faq[] = array("J'ai perdu mon mot de passe !", "Ne paniquez pas ! Si votre mot de passe ne peut être retrouvé, il peut par contre être réinitialisé. Pour ce faire, aller sur la page de connexion et cliquez sur <u>J'ai oublié mon mot de passe</u>, puis suivez les instructions et vous devriez pouvoir vous reconnecter en un rien de temps.");
$faq[] = array("Je me suis inscris mais ne peux pas me connecter !", "Premièrement, vérifiez que vous avez entré correctement vos nom d'utilisateur et mot de passe. S'ils ont correctement été entrés, alors il y a deux possibilités. Si le support COPPA est activé et que vous avez cliqué sur le lien <u>J'ai moins de 13 ans</u> au moment de l'enregistrement, alors vous devrez suivre les instructions que vous avez reçu. Si ce n'est pas le cas, alors peut-être que votre compte a besoin d'être activé ? Certains forums requièrent que tous les nouveaux enregistrements soient activés, soit par vous-même, soit par l'administrateur avant de pouvoir vous connecter. Lorsque vous vous êtes enregistré, un message aurait dû vous apprendre si l'activation est requise ou non. Si vous avez reçu un email, suivez alors les instructions qui s'y trouvent, si vous ne l'avez pas reçu, alors êtes-vous bien sûr que l'adresse email que vous avez fourni lors de l'enregistrement est valide ? L'une des raisons pour lesquelles l'activation est utilisée, c'est de réduire les chances de voir des utilisateurs malintentionnés abuser du forum anonymement. Si vous êtes sûr que l'adresse email que vous avez fourni est valide, essayez alors de contacter l'administrateur du forum.");
$faq[] = array("Je me suis enregistré dans le passé, mais ne peux plus me connecter ?!", "Les raisons les plus probables pour ce problème sont : vous avez entré un nom d'utilisateur ou mot de passe incorrect (vérifiez l'email qui vous a été envoyé lorsque vous vous êtes enregistré) ou l'administrateur a supprimé votre compte pour quelque raison. Si vous vous trouvez dans le dernier cas, peut-être alors que vous n'avez rien posté ? Il est habituel pour les forums de supprimer périodiquement les comptes des utilisateurs n'ayant rien posté afin de réduire la taille de la base de données. Essayez de vous enregistrer encore et impliquez-vous dans les discussions.");

$faq[] = array("--","Préférences et paramètres des Utilisateurs");
$faq[] = array("Comment puis-je changer mes préférences ?", "Toutes vos préférences (si vous êtes enregistrés) sont stockées dans la base de données. Pour les modifier, cliquez sur le lien <u>Profil</u> (généralement en haut des pages, mais cela peut ne pas être le cas). Ceci vous permettra de changer toutes vos préférences.");
$faq[] = array("Les heures ne sont pas correctes !", "Les heures sont certainement correctes, toutefois, ce que vous pouvez voir sont les heures affichées dans un fuseau horaire différent du votre. Si c'est le cas, vous devriez changer vos préférences dans votre profil en choisissant le fuseau horaire qui vous convient, ex : Londres, Paris, New York, Sydney, etc. Veuillez noter que changer le fuseau horaire, comme la plupart des autres options peut uniquement être effectué par les utilisateurs enregistrés. Donc, si vous n'êtes pas enregistré, c'est la bonne heure pour le faire, si vous pardonnez le jeu de mots !");
$faq[] = array("J'ai changé le fuseau horaire et l'heure est toujours incorrecte !", "Si vous êtes sûr d'avoir choisi le bon fuseau horaire et que l'heure est toujours différente, la réponse la plus probable est le passage à l'heure d'été. le forum n'a pas été conçu pour gérer le changement entre l'heure d'hiver et l'heure d'été, donc durant l'été, l'heure sera décalée d'une heure par rapport à l'heure locale réelle.");
$faq[] = array("Ma langue n'est pas dans la liste !", "Les raisons les plus probables pour ceci sont que soit l'administrateur n'a pas installé votre langage sur le forum, ou que soit quelqu'un n'a pas encore traduit ce forum dans votre langue. Essayez de demander à l'administrateur du forum s'il peut installer le pack de langue dont vous avez besoin, s'il n'existe pas sentez-vous alors libre de créer une nouvelle traduction. Plus d'informations peuvent être trouvées sur le site web du groupe phpBB (allez voir le lien en bas des pages).");
$faq[] = array("Comment puis-je montrer une image en-dessous de mon nom d'utilisateur ?", "Il peut y avoir deux images sous votre nom d'utilisateur lorsque vous lisez des messages. La première est l'image associée avec votre rang, générallement elles prennent la forme d'étoiles ou de blocs indiquant combien de messages vous avez fait ou votre statut sur le forum. En-dessous de celle-ci peut se trouver une image plus grande nommée avatar, qui est généralement unique ou personnelle à chaque utilisateur. C'est à l'administrateur du forum d'activer les avatars et de choisir la manière dont les avatars seront disponibles. Si vous ne pouvez pas utilisez un avatar, cela voudra alors dire que l'administrateur en a décidé ainsi, vous pouvez le contacter pour lui en demander les raisons (nous sommes sûr qu'elles seront bonnes !).");
$faq[] = array("Comment puis-je changer mon rang ?", "En général, vous ne pouvez pas directement changer le titre d'un rang (le titre d'un rang apparaît sous votre nom d'utilisateur dans les sujets de discussions et dans votre profil selon le thème utilisé). La plupart des forums utilisent les rangs pour indiquer le nombre de messages que vous avez postés, mais aussi pour identifier certains utilisateurs, ex: les modérateurs et administrateurs peuvent avoir un rang spécifique qui leur est propre. Veuillez ne pas poster inutilement sur le forum dans le but d'élever son rang, vous trouverez probablement un modérateur ou administrateur qui vous abaissera simplement le compte de votre nombre total de messages.");
$faq[] = array("Lorsque je clique sur le lien email d'un utilisateur, on me demande de me connecter !", "Désolé, mais seuls les utilisateurs enregistrés peuvent envoyer des emails à des gens via le formulaire d'email intégré au forum (dans le cas où l'administrateur aurait activé cette fonctionnalité). Ceci, pour éviter l'utilisation malveillante du système d'email par des utilisateurs anonymes.");

$faq[] = array("--","Publication");
$faq[] = array("Comment puis-je poster un sujet dans un forum ?", "Facile, cliquez sur le bouton approprié soit sur la page du forum, soit sur la page du sujet. Vous pourriez avoir besoin de vous enregistrer avant de pouvoir poster un message, les droits qui vous sont disponibles sont listés sur le bas de la page du forum ou du sujet (la liste <i>Vous pouvez poster de nouveaux sujets, vous pouvez voter, etc.</i>)");
$faq[] = array("Comment puis-je éditer ou supprimer un message ?", "A moins que vous soyez l'administrateur ou modérateur du forum, vous pouvez seulement éditer ou supprimer vos propres messages. Vous pouvez éditer un message (parfois seulement après un certain temps après qu'il soit posté) en cliquant sur le bouton <i>Editer</i> du message concerné. Si quelqu'un a déjà répondu à votre message, vous trouverez un petit morceau de texte en dessous de votre message en retournant le lire, indiquant le nombre de fois que vous l'avez édité. Ce petit texte n'apparaîtra pas si personne n'a répondu, il n'apparaîtra pas non plus si un modérateur ou un administrateur édite le message (ils devraient laisser un message expliquant ce qu'ils ont modifié et pourquoi). Veuillez noter qu'un utilisateur ne peut pas supprimer un message une fois que quelqu'un y a répondu.");
$faq[] = array("Comment puis-je ajouter une signature à mon message ?", "Pour ajouter une signature à un message, vous devez d'abord en créer une, en allant dans votre profil. Une fois créée, vous pouvez cocher la case <i>Attacher sa signature</i> lors de la composition d'un message pour ajouter votre signature. Vous pouvez aussi ajouter votre signature à tous vos messages en cochant la case appropriée dans votre profil (vous pourrez toujours empêcher d'attacher votre signature à un message en particulier en décochant la case Attacher sa signature lors de sa composition).");
$faq[] = array("Comment puis-je créer un sondage ?", "Créer un sondage est facile, lorsque vous postez un nouveau sujet (ou éditez le premier message d'un sujet, si vous en avez le droit) vous devriez apercevoir une partie <i>Ajouter un sondage</i> dans le formulaire en dessous de la partie <i>Poster un nouveau sujet</i> (si vous ne le voyez pas, c'est que vous n'avez probablement pas le droit de créer des sondages). Vous devez entrer un titre pour le sondage et au moins deux options (pour définir une option, entrez son nom dans le champs appropriée puis cliquez sur le bouton <i>Ajouter l'option</i>. Vous pouvez également définir une date limite pour le sondage, 0 est un sondage infini. Il y a une limite pour le nombre d'options que vous pourrez établir, cette limite est fixée par l'administrateur du forum).");
$faq[] = array("Comment puis-je éditer ou supprimer un sondage ?", "Comme pour les messages, les sondages peuvent uniquement être édités par le posteur d'origine, un modérateur ou un administrateur. Pour éditer un sondage, cliquez sur le bouton 'Editer' du premier message du sujet (il a toujours le sondage associé avec lui). Si personne n'a encore voté, vous pouvez alors supprimer le sondage ou éditer n'importe quelle option du sondage, par contre, si une personne a déjà voté, seuls les modérateurs et administrateurs pourront l'éditer ou le supprimer. Ceci pour éviter aux gens de truquer les sondages en modifiant les options au milieu de la durée du sondage.");
$faq[] = array("Pourquoi ne puis-je pas accéder à un forum ?", "Certains forums peuvent limiter l'accès à certains utilisateurs ou groupes. Pour voir, lire, poster, etc. vous devez avoir une autorisation spéciale, seul le modérateur et l'administrateur du forum peuvent accorder cet accès, vous pouvez les contacter si vous le voulez.");
$faq[] = array("Pourquoi ne puis-je pas voter dans un sondage ?", "Seuls les utilisateurs enregistrés peuvent voter dans un sondage (afin d'éviter le trucage des résultats). Si vous vous êtes enregistrés et que vous ne pouvez toujours pas voter, alors vous n'avez probablement pas les droits d'accès appropriés.");

$faq[] = array("--","Mise en forme et Types de Sujets");
$faq[] = array("Qu'est-ce que le BBCode ?", "Le BBCode est une implémentation spéciale du HTML, l'activation de l'utilisation du BBCode est déterminée par l'administrateur (vous pouvez aussi le désactiver sur un message en particulier lors de sa composition). Le BBCode en lui-même est similaire au styile du HTML, les balises sont contenues dans des crochets [ et ] à la place de &lt; et &gt;, et offrent un meilleur contrôle sur la manière dont quelque chose doit être affichée. Pour plus d'informations sur le BBCode, allez voir le guide, accessible depuis le formulaire de publication.");
$faq[] = array("Puis-je utiliser le HTML?", "Ceci dépend de l'administrateur qui le permet ou non, il a un contrôle complet dessus. Si vous êtes autorisés à l'utiliser, vous vous rendrez certainement comptes que seulement certaines balises fonctionnent. C'est une mesure de <i>sécurité</i> pour éviter aux gens d'abuser du forum en utilisant certaines balises qui pourraient détruire la mise en page ou causer d'autres problèmes. Si le HTML est activé, vous pouvez le désactiver dans un message en particulier lors de sa composition.");
$faq[] = array("Que sont les Smileys ?", "Les Smileys, ou Emoticons sont de petites images qui sont utilisées pour exprimer certains sentiments en utilisant un petit code, ex: :) signifie joyeux, :( signifie triste. Vous pouvez voir la liste complète des emoticons lors de la composition d'un message. Essayez de ne pas utiliser abusivement ces smileys, car ils peuvent vite rendre un message illisible et un modérateur pourrait décider de l'éditer voire même de le supprimer entièrement.");
$faq[] = array("Puis-je poster des Images?", "Vous pouvez montrer des images à l'intérieur de vos messages. Toutefois, il n'y a actuellement pas de moyen pour envoyer directement vos images sur ce forum. Vous devez donc créer un lien vers votre image stockée sur un serveur web public, ex: http://www.quelque-part.net/mon-image.gif. Vous ne pouvez pas créer un lien vers une image stockée sur votre ordinateur (à moins que celui-ci soit un serveur web public), ni une image stockée sur un serveur nécessitant une authentification, ex: les boîtes email Hotmail ou Yahoo, les sites protégés par mot de passe, etc. Pour afficher une image, vous pouvez soit utiliser la balise BBCode [img] ou soit la balise HTML appropriée (si vous y êtes autorisés).");
$faq[] = array("Que sont les Annonces ?", "Les Annonces contiennent le plus souvent d'importantes informations, vous devriez donc les lire dès que possible. Les Annonces apparaîssent en haut de chaque page du forum dans lequel elle ont été postées. Pouvoir poster une annonce dépend des permissions requises, ces permissions sont définies par l'administrateur.");
$faq[] = array("Que sont les Post-it ?", "Les Post-it apparaîssent en-dessous des annonces et seulement sur la première page du forum. Ils sont souvent assez importants, vous devriez donc les lire dès que vous pouvez. Comme pour les annonces, c'est l'administrateur qui détermine les permissions requises pour poster des Post-it dans chaque forum.");
$faq[] = array("Que sont les Sujets de discussions verrouillés ?", "Les Sujets verrouillés sont verrouillés, soit par le modérateur du forum ou soit par l'administrateur. Vous ne pouvez pas répondre aux sujets de discussions verrouillés et les sondages qui y sont contenus sont cessent automatiquement. Les sujets de discussions peuvent être verrouillés pour de maintes raisons.");

$faq[] = array("--","Niveaux des Utilisateurs et Groupes");
$faq[] = array("Qui sont les Administrateurs ?", "Les Administrateurs sont des personnes qui possèdent le plus haut niveau de contrôle sur tout le forum. Ces personnes peuvent contrôler toutes les facettes du forum, ceci inclut le réglage des permissions, le bannissement d'utilisateurs, la création de groupes d'utilisateurs ou de modérateurs, etc. Ils ont également tous les pouvoirs de modérations sur tous les forums.");
$faq[] = array("Qui sont les Modérateurs?", "Les Modérateurs sont des personnes (ou groupes de personnes) dont le but est de veiller au respect du règlement et au bon fonctionnement du forum tous les jours. Ils ont le pouvoir d'éditer ou de supprimer les messages et de verrouiller, déverrouiller, supprimer et diviser les sujets de discussions dans le forum où ils modèrent. Générallement, les modérateurs sont là pour éviter aux gens de faire du <i>hors-sujet<i> ou de poster des messages ne respectant pas le règlement.");
$faq[] = array("Que sont les groupes d'utilisateurs ?", "Les groupes d'utilisateurs est une manière pour l'administrateur de regrouper des utilisateurs. Chaque utilisateur peut appartenir à plusieurs groupes (ceci diffère de la plupart des autres forums) et chaque groupe peut se voir assignés des droits d'accès. Ceci permet à l'administrateur de gérer aisément différents modérateurs d'un forum, ou de donner leur donner accès à un forum privé, etc.");
$faq[] = array("Comment puis-je joindre un groupe d'utilisateurs ?", "Pour joindre un groupe d'utilisateurs, cliquez sur le lien <i>Groupes d'utilisateurs</i> en haut de la page (peut changer suivant le modèle de document), vous pourrez alors voir tous les groupes d'utilisateurs. Tous les groupes ne sont pas <i>ouverts</i>, certains sont <i>fermés</i> et d'autres peuvent avoir leurs effectifs invisibles. Si le groupe est ouvert, vous pouvez demander à le rejoindre en cliquant sur le bouton approprié. Le modérateur du groupe d'utilisateurs devra approuver votre demande, il pourrait vous demander les raisons qui vous poussent à joindre le groupe. Veuillez ne pas harceler un modérateur de groupe s'il désapprouvre votre demande, il a ses raisons.");
$faq[] = array("Comment puis-je devenir le modérateur d'un groupe d'utilisateurs ?", "Les groupes d'utilisateurs sont initiallement créés par l'administrateur, il y assigne également un modérateur. Si vous êtes intéressé par la création d'un groupe d'utilisateurs, la première chose à faire sera de contacter l'administrateur, essayez de lui laisser un message privé.");

$faq[] = array("--","Messagerie Privée");
$faq[] = array("Je ne peux pas envoyer de messages privés !", "Il y trois raisons pour cela : vous n'êtes pas enregistrés et/ou n'êtes pas connecté, l'administrateur a désactivé la messagerie privée pour la totalité du forum ou l'administrateur vous empêche d'envoyer des messages privés. Si vous êtes dans le dernier cas, vous devriez vous adresser à l'administrateur pour en connaître la raison.");
$faq[] = array("Je continue de recevoir des messages privés non-désirés !", "Dans le futur nous ajouterons une liste noire au système de messagerie privée. Pour le moment, si malgré tout, vous continuez à recevoir des messages non-désirés, informez-en l'administrateur, il a le pouvoir d'empêcher complètement un utilisateur d'envoyer des messages privés.");
$faq[] = array("J'ai reçu un email abusif ou de spamming de quelqu'un sur ce forum !", "Nous sommes peinés d'apprendre cela. La fonction d'email intégré au forum inclut des sauvegardes pour essayer de traquer les utilisateurs qui envoient des messages de ce type. Vous devriez envoyer un email à l'administrateur avec une copie complète de l'email que vous avez reçu, il est important à ce que cette copie contienne les en-têtes (ceux-ci fournissent une liste de détails concernant l'expéditeur). Ensuite alors, l'administrateur pourra prendre les mesures répréssives qui s'imposeront.");

//
// These entries should remain in all languages and for all modifications
//
$faq[] = array("--","phpBB 2");
$faq[] = array("Qui a écrit ce forum ?", "Ce logiciel (sous sa forme non-modifiée) est produit, distribué et est sous droits d'auteurs par le <a href=\"http://www.phpbb.com/\" target=\"_blank\">Groupe phpBB</a>. Il est disponible sous la license générale publique GNU et peut être distribué librement, cliquez sur le lien pour plus de détails.");
$faq[] = array("Pourquoi la fonction X n'est pas disponible ?", "Ce programme a été écrit et est sous license du Groupe phpBB. Si vous croyez qu'une fonction doit être ajoutée, veuillez visiter le site web phpbb.com et voir ce que le groupe phpBB en pense. Veuillez ne pas poster de demande de fonctions sur le forum de phpbb.com, le Groupe utilise sourceforge pour s'occuper des nouvelles fonctionnalités.");
$faq[] = array("Qui dois-je contacter à propos des questions d'abus ou de légalité relatif à ce forum ?", "Vous devriez contacter l'administrateur de ce forum. Si vous n'arrivez pas à le contacter, vous devriez d'abord contacter l'un des modérateurs du forum et leur demander avec qui vous devriez prendre contact. Si vous ne recevez toujours pas de réponses, vous devriez contacter le propriétaire du domaine (faite une recherche avec whois) ou, si ce forum fonctionne sur un hébergeur gratuit (ex : yahoo, free.fr, f2s.com, etc.), la direction ou le service des abus de l'hébergeur. Veuillez noter que le Groupe phpBB n'a absolument aucun contrôle et ne peut pas en aucun cas être lié à la manière, au lieu ou à la personne qui utilise ce forum. Cela ne sert asbolument à rien de contacter le Groupe phpBB pour une question de légalité (diffamation, etc.) n'ayant pas un rapport direct avec le site web phpbb.com ou le discret programme qu'est phpBB lui-même. Si vous faites un email à l'intention du Groupe phpBB à propos de tiers personne de l'usage de ce programme, alors vous devriez vous attendre à une tiers-réponse ou pas de réponse du tout.");

//
// This ends the FAQ entries
//

?>